import fs from'node:fs';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{build}from'esbuild';import * as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.WEBSTER_LAKE_QA||'/private/tmp/webster-final-details/lake-life';fs.mkdirSync(work,{recursive:true});if(!fs.existsSync(path.join(work,'node_modules')))fs.symlinkSync(path.join(repo,'node_modules'),path.join(work,'node_modules'));
const compiled=path.join(work,'lake-native.mjs');await build({entryPoints:[path.join(repo,'src/lib/town/lake-life.ts')],outfile:compiled,bundle:true,platform:'node',format:'esm',external:['three'],logLevel:'silent'});const{applyLakeLife,LAKE_LIFE_PROVENANCE:d}=await import(pathToFileURL(compiled).href);
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),release=read(path.join(repo,'data/derived/town/release.json')),assets=path.join(repo,'public/town-assets',release.directory),manifest=read(path.join(assets,'manifest.json'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'REFERENCE_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const report={runtimeSha256:sha(fs.readFileSync(path.join(repo,'src/lib/town/lake-life.ts'))),dataSha256:sha(fs.readFileSync(path.join(repo,'data/derived/town/lake-life.json'))),results:[],failures:[]},tile=manifest.tiles.find(t=>t.id===d.tileId);
for(const lod of tile.lods){const raw=fs.readFileSync(path.join(assets,lod.url));if(sha(raw)!==lod.sha256)throw Error('Source SHA');const scene=(await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),'')).scene;scene.updateMatrixWorld(true);const source=[];scene.traverse(o=>{if(o instanceof THREE.Mesh)source.push({o,g:o.geometry,m:o.material,positions:sha(Buffer.from(o.geometry.getAttribute('position').array.buffer))});});const result=applyLakeLife(scene,tile.id,tile.origin,lod.level,lod.sha256);const failures=[];for(const x of source)if(x.o.geometry!==x.g||x.o.material!==x.m||sha(Buffer.from(x.g.getAttribute('position').array.buffer))!==x.positions)failures.push('Source changed');
 const waters=source.filter(x=>[x.o.name,x.o.parent?.name,...(Array.isArray(x.m)?x.m:[x.m]).map(m=>m.name)].some(n=>/water/i.test(n??''))).map(x=>x.o);const ray=new THREE.Raycaster(),samples=[];for(const u of[-9,0,9])for(const v of[-2.4,0,2.4]){const x=d.point[0]+Math.cos(d.angle)*u+Math.sin(d.angle)*v,z=-d.point[1]-Math.sin(d.angle)*u+Math.cos(d.angle)*v;ray.set(new THREE.Vector3(x-tile.origin[0],1000,z-tile.origin[2]),new THREE.Vector3(0,-1,0));const hit=ray.intersectObjects(waters,false)[0];samples.push({u,v,height:hit?.point.y});if(!hit||Math.abs(hit.point.y-d.height)>.4)failures.push('Missing/wrong water surface');}
 const r={level:lod.level,sourceSha256:lod.sha256,sourceMeshes:source.length,...result,waterMeshes:waters.length,waterSamples:samples,failures};report.results.push(r);report.failures.push(...failures);console.log(r);
}
report.status=report.failures.length?'FAIL':'PASS';fs.writeFileSync(path.join(work,'native-audit.json'),JSON.stringify(report,null,2));if(report.failures.length)process.exitCode=1;
