// @vitest-environment node
import{describe,it,expect,vi}from'vitest';
import*as THREE from'three';
import catalog from '../../../../data/derived/town/arrival-grounds.json';
import{applyArrivalGrounds}from'../arrival-grounds';
import type{V3}from'../contracts';
const tileId='-8_-7',row=catalog.tiles[tileId],origin=row.origin as V3;
function fixture(){const group=new THREE.Group(),g=new THREE.PlaneGeometry(250,250,4,4).rotateX(-Math.PI/2).translate(125,40,-125),p=g.getAttribute('position');for(let i=0;i<p.count;i++)p.setY(i,40+p.getX(i)*.01+p.getZ(i)*.02);g.computeVertexNormals();const m=new THREE.MeshStandardMaterial(),mesh=new THREE.Mesh(g,m);mesh.name='terrain_1';group.add(mesh);return{group,g,m,mesh};}
function added(group:THREE.Group){const meshes:THREE.Mesh[]=[];group.getObjectByName('Photo-informed campus arrivals')?.traverse(o=>{if(o instanceof THREE.Mesh)meshes.push(o);});return meshes;}
describe('dated campus arrivals',()=>{
 it('keeps source arrays, materials and ownership while draping every paving vertex on the retained sloping terrain',()=>{const a=fixture(),source=a.g.getAttribute('position').array.slice(),gd=vi.spyOn(a.g,'dispose'),md=vi.spyOn(a.m,'dispose');const report=applyArrivalGrounds(a.group,tileId,origin,0,row.lods[0].sha256)!;expect(report.status).toBe('applied');expect(report.plantings).toBeGreaterThan(2);expect(a.mesh.geometry).toBe(a.g);expect(a.g.getAttribute('position').array).toEqual(source);expect(a.mesh.material).toBe(a.m);expect(gd).not.toHaveBeenCalled();expect(md).not.toHaveBeenCalled();for(const mesh of added(a.group)){const p=mesh.geometry.getAttribute('position'),n=mesh.geometry.getAttribute('normal'),m=mesh.material as THREE.MeshStandardMaterial;expect(m.map).toBeNull();for(let i=0;i<p.count;i++){expect(Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i))).toBe(true);expect(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))).toBeCloseTo(1,5);if(m.userData.surfaceRole==='paving'){const gap=p.getY(i)-(40+p.getX(i)*.01+p.getZ(i)*.02);expect(gap).toBeGreaterThan(.01198);expect(gap).toBeLessThan(.01802);}}}expect(a.group.userData.environmentTreeExclusions).toBeUndefined();expect(a.group.userData.environmentGrassExclusions.length).toBeGreaterThan(0);});
 it('is repeat safe and retains a consistent complete surface at every LOD while thinning only tiny planting geometry',()=>{for(let level=0;level<3;level++){const a=fixture(),result=applyArrivalGrounds(a.group,tileId,origin,level,row.lods[level].sha256),children=a.group.children.length;expect(applyArrivalGrounds(a.group,tileId,origin,level,row.lods[level].sha256)).toBe(result);expect(a.group.children).toHaveLength(children);if(level===2)expect(result!.plantings).toBe(0);else expect(result!.plantings).toBeGreaterThan(0);expect(result!.geometryBytes).toBeLessThan(100000);}});
 it('rejects wrong source or origin and leaves unsupported scenes untouched',()=>{for(const input of['source','origin','empty']){const a=fixture();if(input==='empty')a.mesh.name='buildings';const result=applyArrivalGrounds(a.group,tileId,input==='origin'?[0,0,0]:origin,0,input==='source'?'bad':row.lods[0].sha256);expect(result!.status).toBe(input==='empty'?'no-support':'source-mismatch');expect(a.group.children).toHaveLength(1);expect(added(a.group)).toHaveLength(0);expect(a.group.userData.environmentGrassExclusions).toBeUndefined();}expect(applyArrivalGrounds(new THREE.Group(),'missing',[0,0,0],0,'bad')).toBeUndefined();});
 it('cancels an attached scene transform when registering native tile geometry',()=>{const a=fixture(),b=fixture();b.group.position.set(777,60,-900);b.group.rotation.y=.36;applyArrivalGrounds(a.group,tileId,origin,0,row.lods[0].sha256);applyArrivalGrounds(b.group,tileId,origin,0,row.lods[0].sha256);const x=added(a.group),y=added(b.group);expect(x.length).toBe(y.length);for(let k=0;k<x.length;k++){const p=x[k].geometry.getAttribute('position'),q=y[k].geometry.getAttribute('position');expect(p.count).toBe(q.count);for(let i=0;i<p.count;i++){expect(q.getX(i)).toBeCloseTo(p.getX(i),4);expect(q.getY(i)).toBeCloseTo(p.getY(i),4);expect(q.getZ(i)).toBeCloseTo(p.getZ(i),4);}}});
});
