// @vitest-environment node
import {describe,it,expect} from 'vitest';
import * as THREE from 'three';
import {applyBathhouse,buildBathhouse,BATHHOUSE as row} from '../bathhouse';
function source(){const group=new THREE.Group(),g=new THREE.BoxGeometry(4,4,4),m=new THREE.MeshStandardMaterial();g.clearGroups();m.name='V2 inferred | concrete_wall';const mesh=new THREE.Mesh(g,m);mesh.position.set(-744-row.origin[0],50-row.origin[1],492-row.origin[2]);group.add(mesh);return group;}
describe('Memorial Beach source-constrained bathhouse',()=>{
 it('rejects a different tile revision without deleting its existing building',()=>{const group=source(),mesh=group.children[0];expect(applyBathhouse(group,row.tileId,row.origin,0,'different')?.status).toBe('source-mismatch');expect(group.children).toEqual([mesh]);});
 it('protects reference geometry inside the same footprint and makes replacement idempotent',()=>{const group=source(),kept=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial());kept.position.copy(group.children[0].position);(kept.material as THREE.Material).name='Reference building';group.add(kept);const geometry=kept.geometry;const r=applyBathhouse(group,row.tileId,row.origin,0,row.lods[0].sha256)!;expect(r.status).toBe('applied');expect(r.ids).toEqual([row.id]);expect(kept.geometry).toBe(geometry);expect(kept.parent).toBe(group);expect(applyBathhouse(group,row.tileId,row.origin,0,row.lods[0].sha256)).toBe(r);expect(r.peak).toBeLessThan(row.sourcePeak);expect(r.triangles).toBeGreaterThan(500);});
 it('has an upward closed roof envelope with no gap under vertical rays across the mapped roof',()=>{
  const built=buildBathhouse(new THREE.Vector3(),0);built.group.updateMatrixWorld(true);const roofs=built.group.children.filter(o=>(o as THREE.Mesh).material instanceof THREE.Material&&((o as THREE.Mesh).material as THREE.Material).userData.surfaceRole==='roof');
  const f=row.frame;let checked=0;for(const t of row.roof){const u=t.reduce((s,p)=>s+p[0],0)/3,v=t.reduce((s,p)=>s+p[2],0)/3,h=t.reduce((s,p)=>s+p[1],0)/3,x=f.start[0]+f.tangent[0]*u+f.outward[0]*v,n=f.start[1]+f.tangent[1]*u+f.outward[1]*v;const hits=new THREE.Raycaster(new THREE.Vector3(x,60,-n),new THREE.Vector3(0,-1,0)).intersectObjects(roofs);expect(hits.length).toBeGreaterThan(0);expect(hits[0].point.y).toBeCloseTo(h,3);checked++;}expect(checked).toBeGreaterThan(20);
 });
 it('retains the documented opening arrangement at every LOD without extra texture downloads',()=>{expect(row.walls.filter(w=>[0,6].includes(w.sourceEdge))).toHaveLength(2);expect(row.walls.filter(w=>[7,11].includes(w.sourceEdge))).toHaveLength(2);for(let level=0;level<3;level++){const r=buildBathhouse(new THREE.Vector3().fromArray(row.origin),level);r.group.traverse(o=>{if(o instanceof THREE.Mesh){expect(o.geometry.getAttribute('position').array.every(Number.isFinite)).toBe(true);expect((o.material as THREE.MeshStandardMaterial).map).toBeNull();}});expect(r.triangles).toBeLessThan(4000);expect(r.group.children.length).toBeLessThan(16);}});
});
