// @vitest-environment node
import {describe,it,expect} from 'vitest';
import * as THREE from 'three';
import {applyCampStructures,CAMP_STRUCTURES} from '../camp-structures';
const row=CAMP_STRUCTURES.rows[0];
function source(){const group=new THREE.Group();const p=row.outline.slice(0,3).flatMap(p=>[p[0]-row.origin[0],row.sourceBase+1-row.origin[1],-p[1]-row.origin[2]]);const g=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.computeVertexNormals();const m=new THREE.MeshStandardMaterial();m.name='V2 inferred | siding';group.add(new THREE.Mesh(g,m));return group;}
function terrain(group:THREE.Group){const p=[[300,50,-750],[700,50,-750],[700,50,-490],[300,50,-490]];const a=p.map(([x,y,n])=>[x-row.origin[0],y-row.origin[1],-n-row.origin[2]]),g=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute([a[0],a[1],a[2],a[0],a[2],a[3]].flat(),3));g.computeVertexNormals();const m=new THREE.MeshStandardMaterial();m.name='Realism aerial viewport512 | ground_test.jpg';group.add(new THREE.Mesh(g,m));}
function dispose(group:THREE.Object3D){const gs=new Set<THREE.BufferGeometry>(),ms=new Set<THREE.Material>();group.traverse(o=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m);}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
describe('aerial-matched camp structure interpretations',()=>{
 it('rejects a changed source/LOD or origin without mutation',()=>{for(const [sha,origin]of [['bad',row.origin],[row.lods[0].sha256,[row.origin[0]+.1,...row.origin.slice(1)]]] as const){const group=source(),mesh=group.children[0] as THREE.Mesh,g=mesh.geometry;terrain(group);const result=applyCampStructures(group,row.tileId,origin,0,sha)!;expect(result.status).toBe('source-mismatch');expect(mesh.geometry).toBe(g);expect(group.children).toHaveLength(2);dispose(group);}});
 it('does not remove a source body if current terrain cannot support its replacement',()=>{const group=source(),mesh=group.children[0] as THREE.Mesh;expect(applyCampStructures(group,row.tileId,row.origin,0,row.lods[0].sha256)!.status).toBe('no-support');expect(mesh.parent).toBe(group);dispose(group);});
 it('replaces only matched inferred bodies once, with usable inferred door/roof height and no new textures',()=>{const group=source(),original=group.children[0];terrain(group);const p=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial());(p.material as THREE.Material).name='Reference | protected pavilion';group.add(p);const protectedGeometry=p.geometry;const r=applyCampStructures(group,row.tileId,row.origin,0,row.lods[0].sha256)!;expect(r.ids).toEqual([row.id]);expect(original.parent).toBeNull();expect(p.geometry).toBe(protectedGeometry);expect(r.placements[0].floor).toBeCloseTo(50.2,5);expect(r.placements[0].peak-r.placements[0].floor).toBeCloseTo(2.53,6);expect(applyCampStructures(group,row.tileId,row.origin,0,row.lods[0].sha256)).toBe(r);group.traverse(o=>{if(o instanceof THREE.Mesh&&o.userData.category==='camp-structures'){expect(o.userData.townCrafted).toBe(true);const m=o.material as THREE.MeshStandardMaterial;expect(m.map).toBeNull();expect(m.userData.townCrafted).toBe(true);}});dispose(group);});
 it('documents aerial identification separately from inferred facade/height and retains the major institutions',()=>{expect(CAMP_STRUCTURES.rows).toHaveLength(16);expect(new Set(CAMP_STRUCTURES.rows.map(r=>r.id)).size).toBe(16);expect(CAMP_STRUCTURES.rows.some(r=>['171749_866853','171785_866902'].includes(r.id))).toBe(false);for(const r of CAMP_STRUCTURES.rows){expect(r.observed).toMatch(/not established/);expect(r.inferred).toMatch(/authored/);expect(r.sourceDate).toContain('2011');}});
});
