// @vitest-environment node
import{describe,it,expect,vi}from'vitest';import*as THREE from'three';import domains from'../../../../data/derived/town/cemetery-road-domains.json';import{applyCemeteryRoadFinish}from'../cemetery-roads';
function fixture(){const group=new THREE.Group(),x=-1588.4055948119633,n=712.08855;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([x,5,-n,x+.1,5,-n,x,5,-n-.1,0,5,0,.1,5,0,0,5,-.1],3));g.computeVertexNormals();g.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,0,1,0,0,1,0,0,1],2));const material=new THREE.MeshStandardMaterial();material.name='Drive road | warm yellow paint';const yellow=new THREE.Mesh(g,material);group.add(yellow);const white=new THREE.Mesh(g,new THREE.MeshStandardMaterial());white.material.name='Drive road | chalk white paint';group.add(white);return{group,g,yellow,white};}
describe('Cemetery internal road appearance',()=>{
 it('removes only inferred yellow triangles within registered internal domains and preserves shared source buffers, white paint and other roads',()=>{
  const {group,g,yellow,white}=fixture(),original=Object.fromEntries(Object.entries(g.attributes).map(([k,v])=>[k,v.array.slice()])),dispose=vi.spyOn(g,'dispose');const result=applyCemeteryRoadFinish(group,'-7_2',[0,0,0],domains.sourceManifestSha256);expect(result).toEqual({removedTriangles:1,meshes:1});expect(yellow.geometry.index!.array).toEqual(new Uint16Array([3,4,5]));expect(white.geometry).toBe(g);expect(dispose).not.toHaveBeenCalled();for(const[k,v]of Object.entries(original))expect(yellow.geometry.getAttribute(k).array).toEqual(v);expect(applyCemeteryRoadFinish(group,'-7_2',[0,0,0],domains.sourceManifestSha256)).toBe(result);
 });
 it('requires the pinned source release and leaves unrelated tiles unchanged',()=>{for(const[tile,sha]of[['-7_2','x'],['0_0',domains.sourceManifestSha256]]){const {group,yellow,g}=fixture();expect(applyCemeteryRoadFinish(group,tile,[0,0,0],sha).removedTriangles).toBe(0);expect(yellow.geometry).toBe(g);}});
});
