// @vitest-environment node
import {describe,expect,it,vi} from 'vitest';
import * as THREE from 'three';
import data from '../../../../data/derived/town/church-roof-finish.json';
import {applyChurchRoofFinish} from '../church-roof-finish';
function fixture(level=0){const group=new THREE.Group(),parent=new THREE.Group();parent.name='buildings';group.add(parent);const meshes=[...data.lods[level].meshes,...data.skinTiles['-12_-4'].lods[level].meshes].map(row=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(row.vertices*3),3));g.setAttribute('normal',new THREE.Float32BufferAttribute(new Float32Array(row.vertices*3),3));g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(row.vertices*2),2));g.setIndex(Array.from({length:row.triangles*3},()=>0));const m=new THREE.MeshStandardMaterial();m.name=row.material;const mesh=new THREE.Mesh(g,m);mesh.name=row.name;if(row.parent==='landmarks'){let landmarks=group.getObjectByName('landmarks');if(!landmarks){landmarks=new THREE.Group();landmarks.name='landmarks';group.add(landmarks);}landmarks.add(mesh);}else parent.add(mesh);return mesh;});return{group,meshes};}
describe('pinned church eave repair',()=>{
 it('preflights every mesh and source identity atomically before any mutation',()=>{for(const failure of['hash','roof','count']){const{group,meshes}=fixture(),original=meshes.map(m=>m.geometry);if(failure==='roof')meshes[1].name='Protected observed roof';if(failure==='count')meshes[1].geometry.setIndex([0,1,2]);expect(applyChurchRoofFinish(group,data.tileId,0,failure==='hash'?'bad':data.lods[0].sha256)?.status).toBe('source-mismatch');meshes.forEach((m,i)=>expect(m.geometry).toBe(original[i]));expect(group.userData.churchRoofFinish).toBeUndefined();}});
 it('borrows all materials/textures and applies once per source group',()=>{const{group,meshes}=fixture();const materials=meshes.map(m=>m.material),geometry=meshes.map(m=>m.geometry),dispose=materials.map(m=>vi.spyOn(m,'dispose'));const result=applyChurchRoofFinish(group,data.tileId,0,data.lods[0].sha256);expect(result?.status).toBe('applied');const current=meshes.map(m=>m.geometry);expect(applyChurchRoofFinish(group,data.tileId,0,data.lods[0].sha256)).toBe(result);meshes.forEach((m,i)=>{expect(m.material).toBe(materials[i]);expect(m.geometry).toBe(current[i]);expect(m.geometry).not.toBe(geometry[i]);expect(dispose[i]).not.toHaveBeenCalled();});});
 it('does not touch adjacent tiles or a different release',()=>{const{group,meshes}=fixture();const old=meshes[0].geometry;expect(applyChurchRoofFinish(group,'-13_-5',0,data.lods[0].sha256)).toBeUndefined();expect(meshes[0].geometry).toBe(old);expect(applyChurchRoofFinish(group,data.tileId,4,data.lods[0].sha256)?.status).toBe('source-mismatch');});
});
