// @vitest-environment node
import{describe,it,expect,vi}from'vitest';
import*as THREE from'three';
import{readFileSync,readdirSync}from'node:fs';import{createHash}from'node:crypto';
import type{GLTFLoader,GLTFParser,GLTFLoaderPlugin}from'three/examples/jsm/loaders/GLTFLoader.js';
import{installLeafAtlasOverride,leafAtlasTextureURL,LEAF_ATLAS}from'../leaf-atlas-loader';
import {decodeCoverPNG}from'../cover-data';
import release from '../../../../data/derived/town/release.json';
function fixture(failArt=false,failBoth=false,bitmap=false){let plugin:GLTFLoaderPlugin|undefined;const image={width:512,height:512,close:vi.fn()},texture=new THREE.Texture(image),load=vi.fn((url:string,done:(v:object)=>void,_progress:unknown,error:(e:Error)=>void)=>{if(failBoth||(failArt&&url.includes('/town-finish/')))error(new Error('404'));else done(bitmap?image:texture);});const parser={json:{textures:[{source:0}],images:[{uri:LEAF_ATLAS.sourceUri}]},options:{path:`https://example.test/town-assets/${release.directory}/models/`},textureLoader:{load,isImageBitmapLoader:bitmap},loadTextureImage:(_i:number,_source:number,delegate:THREE.Loader)=>new Promise<THREE.Texture>((resolve,reject)=>{(delegate as unknown as {load:typeof load}).load('unused',v=>resolve(bitmap?new THREE.Texture(v as ImageBitmap):v as THREE.Texture),undefined,reject);})}as unknown as GLTFParser;const register=vi.fn((factory:(p:GLTFParser)=>GLTFLoaderPlugin)=>{plugin=factory(parser);return loader;}),loader={register}as unknown as GLTFLoader;installLeafAtlasOverride(loader);return{parser,loader,register,plugin:plugin!,load,image,texture};}
describe('pinned leaf atlas request override',()=>{
 it('keeps the existing decoder, sampler path and shared image identity before pooling',async()=>{for(const bitmap of[false,true]){const f=fixture(false,false,bitmap),texture=await f.plugin.loadTexture!(0)!;expect(f.load).toHaveBeenCalledTimes(1);expect(f.load.mock.calls[0][0]).toBe('https://example.test'+LEAF_ATLAS.url);expect(leafAtlasTextureURL(texture)).toBe('https://example.test'+LEAF_ATLAS.url);expect(leafAtlasTextureURL(texture.clone())).toBe('https://example.test'+LEAF_ATLAS.url);expect(f.image.close).not.toHaveBeenCalled();installLeafAtlasOverride(f.loader);expect(f.register).toHaveBeenCalledTimes(1);}});
 it('falls back to the exact original source URL and does not mislabel it as the art image',async()=>{const f=fixture(true),texture=await f.plugin.loadTexture!(0)!;expect(f.load).toHaveBeenCalledTimes(2);expect(leafAtlasTextureURL(texture)).toBe(`https://example.test/town-assets/${release.directory}/textures/leaf-cluster.png`);expect(f.image.close).not.toHaveBeenCalled();const failed=fixture(true,true);await expect(failed.plugin.loadTexture!(0)).rejects.toThrow('404');expect(failed.load).toHaveBeenCalledTimes(2);});
 it('ignores every other source image and release',()=>{const f=fixture();f.parser.json.images[0].uri='../textures/brick.png';expect(f.plugin.loadTexture!(0)).toBeNull();f.parser.json.images[0].uri=LEAF_ATLAS.sourceUri;f.parser.options.path='https://example.test/town-assets/different/models/';expect(f.plugin.loadTexture!(0)).toBeNull();expect(f.load).not.toHaveBeenCalled();});
 it('binds the shipped vector derivative and original source hashes without changing texture dimensions',()=>{const bytes=readFileSync('public'+LEAF_ATLAS.url),hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');const decoded=decodeCoverPNG(bytes);for(let y=0;y<512;y++)for(let x=0;x<512;x++)if(x<8||x>=504||y<8||y>=504)expect(decoded.data[(y*512+x)*4+3]).toBe(0);expect(bytes.length).toBe(LEAF_ATLAS.bytes);expect(hash(bytes)).toBe(LEAF_ATLAS.sha256);expect(bytes.readUInt32BE(16)).toBe(512);expect(bytes.readUInt32BE(20)).toBe(512);expect(hash(readFileSync('scripts/art_finish/foliage/leaf-cluster.svg'))).toBe(LEAF_ATLAS.originalVectorSha256);expect(readdirSync('public/town-finish/v1/art').filter(n=>n.endsWith('.png'))).toEqual([LEAF_ATLAS.url.split('/').pop()]);expect(LEAF_ATLAS.replacement.coverage).toBeGreaterThan(.20);expect(LEAF_ATLAS.replacement.coverage).toBeLessThan(LEAF_ATLAS.original.coverage);});
});
