// @vitest-environment node
import {describe,it,expect}from'vitest';import*as THREE from'three';
import {Batch,type Frame}from'../crafted-frontages';
import{buildPrincessCanopy,PRINCESS_FINISH_BASIS}from'../princess-details';
import{applyLakeLife,LAKE_LIFE_PROVENANCE as d}from'../lake-life';
const frame:Frame={start:[0,0],tangent:[1,0],outward:[0,-1],structId:'boat-test',tileId:'0_0'};
describe('physically connected Princess details',()=>{
 it('uses a closed outward canopy volume with the same modest span',()=>{for(let level=0;level<3;level++){const b=new Batch(new THREE.Vector3(),level);buildPrincessCanopy(b,frame,0);const result=b.finish();let volume=0;result.group.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const p=o.geometry.getAttribute('position');for(let i=0;i<p.count;i+=3){const a=new THREE.Vector3().fromBufferAttribute(p,i),c=new THREE.Vector3().fromBufferAttribute(p,i+1),e=new THREE.Vector3().fromBufferAttribute(p,i+2);volume+=a.dot(c.cross(e))/6;}});expect(volume).toBeCloseTo(12.8*5.75*.08,3);}});
 it('has a clear stairwell with connected treads instead of a roof or cabin through the flight',()=>{for(let level=0;level<3;level++){const group=new THREE.Group();applyLakeLife(group,d.tileId,d.origin,level,(d.sourceLods as Record<string,string>)[String(level)]);group.updateMatrixWorld(true);const s=PRINCESS_FINISH_BASIS.stair,ray=new THREE.Raycaster(),meshes:THREE.Mesh[]=[];group.traverse(o=>{if(o instanceof THREE.Mesh)meshes.push(o);});for(let i=0;i<s.steps;i++){const u=s.front-(i+.5)*(s.front-s.rear)/s.steps,v=s.centerV,x=d.point[0]+Math.cos(d.angle)*u+Math.sin(d.angle)*v,z=-d.point[1]-Math.sin(d.angle)*u+Math.cos(d.angle)*v;ray.set(new THREE.Vector3(x-d.origin[0],d.height+8,z-d.origin[2]),new THREE.Vector3(0,-1,0));const hit=ray.intersectObjects(meshes,false)[0];expect(hit,`tread${i} LOD${level}`).toBeDefined();expect(hit.point.y-d.height).toBeCloseTo(s.bottom+(i+1)*(s.top-s.bottom)/s.steps,4);}}});
 it('documents observed forms separately from the authored dimensions',()=>{expect(PRINCESS_FINISH_BASIS.photoSHA256).toBe(d.source.photoSHA256);expect(PRINCESS_FINISH_BASIS.inference).toContain('authored');expect(PRINCESS_FINISH_BASIS.observed).toContain('Three arched pilot-house front windows');});
});
