// @vitest-environment node
import{describe,it,expect,vi}from'vitest';import*as THREE from'three';import{removeUnpavedRoadPaint}from'../road-unpaved-paint';
function rectangle(x0:number,y0:number,x1:number,y1:number,height:number){return[[x0,y0,height],[x1,y0,height],[x1,y1,height],[x0,y0,height],[x1,y1,height],[x0,y1,height]];}
function mesh(points:number[][],name:string,code?:number){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(points.flatMap(p=>[p[0],p[2],-p[1]]),3));g.setAttribute('normal',new THREE.Float32BufferAttribute(points.flatMap(()=>[0,1,0]),3));const m=new THREE.MeshStandardMaterial();m.name=name;if(code!==undefined)m.userData.townRoadSurfaceType=code;return new THREE.Mesh(g,m);}
function fixture(){const group=new THREE.Group(),road=mesh(rectangle(0,0,8,10,5),'Drive road | asphalt | gravel inventory surface',2),paint=mesh(rectangle(3.8,1,4.2,9,5.021),'Drive road | warm yellow paint');group.add(road,paint);return{group,road,paint};}
describe('Whole-area source-registered unpaved markings',()=>{
 it('removes only supported yellow/white road paint, leaving all vertex buffers, road shapes and source materials intact',()=>{const{group,road,paint}=fixture(),white=mesh(rectangle(.2,1,.3,9,5.018),'Drive road | chalk white paint'),finished=mesh(rectangle(3.5,1,3.6,9,5.018),'Finished road | solid yellow centerline'),protectedPaint=mesh(rectangle(2,1,2.2,9,5.021),'Parking | bay line');group.add(white,finished,protectedPaint);const attrs={...paint.geometry.attributes},original=paint.geometry,dispose=vi.spyOn(original,'dispose'),roadGeometry=road.geometry,material=paint.material;const r=removeUnpavedRoadPaint(group);expect(r).toMatchObject({removedTriangles:6,meshes:3,pavedVetoes:0});expect(paint.geometry.index?.count).toBe(0);for(const[name,a]of Object.entries(attrs))expect(paint.geometry.getAttribute(name)).toBe(a);expect(road.geometry).toBe(roadGeometry);expect(paint.material).toBe(material);expect(protectedPaint.geometry.index).toBeNull();expect(dispose).toHaveBeenCalledOnce();expect(removeUnpavedRoadPaint(group)).toBe(r);});
 it.each([undefined,5])('retains a painted intersection with overlapping paved/unknown asphalt code%s',code=>{const{group,paint}=fixture(),original=paint.geometry;group.add(mesh(rectangle(0,4,8,6,5),'Drive road | asphalt',code));expect(removeUnpavedRoadPaint(group)).toMatchObject({removedTriangles:0,pavedVetoes:2});expect(paint.geometry).toBe(original);});
 it('retains crossing paint at another elevation and does not turn bridge projections into evidence',()=>{const{group,paint}=fixture();paint.position.y=10;expect(removeUnpavedRoadPaint(group).removedTriangles).toBe(0);});
 it('requires the whole area to be covered, not only the three corners or road nearest to the center',()=>{const group=new THREE.Group();group.add(mesh(rectangle(0,0,3.9,10,5),'registered earth',1),mesh(rectangle(4.1,0,8,10,5),'registered earth',1));const p=mesh(rectangle(3.8,1,4.2,9,5.021),'Drive road | warm yellow paint');group.add(p);const before=p.geometry;expect(removeUnpavedRoadPaint(group)).toMatchObject({removedTriangles:0,retainedTransitionTriangles:2});expect(p.geometry).toBe(before);});
 it('preserves an original shared geometry still referenced by an ineligible sibling',()=>{const{group,paint}=fixture(),old=paint.geometry,other=new THREE.Mesh(old,new THREE.MeshStandardMaterial()),dispose=vi.spyOn(old,'dispose');group.add(other);expect(removeUnpavedRoadPaint(group).removedTriangles).toBe(2);expect(other.geometry).toBe(old);expect(dispose).not.toHaveBeenCalled();});
});
