// @vitest-environment node
import{describe,it,expect,vi}from'vitest';import*as THREE from'three';import fs from'node:fs';import{createHash}from'node:crypto';
import catalog from'../../../../data/derived/town/road-materials-index.json';
import{applyRoadMaterialFinish,validRoadMaterialPacket,type RoadMaterialPacket}from'../road-material-finish';import{applyArtMaterial}from'../art-materials';
const sourceSha='a'.repeat(64);
function stamp(g:THREE.BufferGeometry){let h=2166136261;for(const a of[g.getAttribute('position'),g.index])if(a)for(const b of new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength))h=Math.imul(h^b,16777619)>>>0;return h.toString(16).padStart(8,'0');}
function triangles(g:THREE.BufferGeometry){const p=g.getAttribute('position'),out=[];for(let i=0;i<(g.index?.count??p.count);i+=3)out.push([0,1,2].map(k=>g.index?.getX(i+k)??i+k).join(','));return out.sort();}
function fixture(indexed=true){const group=new THREE.Group(),geometry=new THREE.PlaneGeometry(20,10,3,1);if(!indexed){const other=geometry.toNonIndexed();geometry.dispose();return from(other);}return from(geometry);function from(g:THREE.BufferGeometry){const m=new THREE.MeshStandardMaterial({color:new THREE.Color().setRGB(.16,.12,.09),map:new THREE.DataTexture(),normalMap:new THREE.DataTexture(),normalScale:new THREE.Vector2(1,1)});m.name='Drive road | asphalt';const mesh=new THREE.Mesh(g,m);mesh.name='roads';group.add(mesh);const packet:RoadMaterialPacket={version:1,tileId:'1_1',level:0,sourceManifestSha256:catalog.sourceManifestSha256,sourceSha256:sourceSha,meshes:[{name:mesh.name,parent:group.name,geometryStamp:stamp(g),assignments:[[0,2],[2,5],[4,1]]}]};return{group,mesh,geometry:g,material:m,packet};}}
describe('Source-registered road inventory materials',()=>{
 it('validates every compact emitted packet, hash, source ownership and count without the ignored source archive',()=>{const names=[];for(const[tile,row]of Object.entries(catalog.tiles))for(const[level,ref]of Object.entries(row.levels)){names.push(ref.url.split('/').pop()!);const raw=fs.readFileSync('public'+ref.url),p=JSON.parse(raw.toString());expect(raw.length).toBe(ref.bytes);expect(createHash('sha256').update(raw).digest('hex')).toBe(ref.sha256);expect(validRoadMaterialPacket(p,tile,Number(level))).toBe(true);expect(p.meshes.reduce((s:number,m:{assignments:unknown[]})=>s+m.assignments.length,0)).toBe(ref.count);}expect(fs.readdirSync('public/town-evidence/v1/road-materials').filter(n=>n.endsWith('.json')).sort()).toEqual(names.sort());});
 it.each([true,false])('preserves all source triangles and attributes with indexed=%s, including untouched asphalt',indexed=>{const{group,mesh,geometry,material,packet}=fixture(indexed),attrs={...geometry.attributes},before=triangles(geometry),dispose=vi.spyOn(geometry,'dispose');const r=applyRoadMaterialFinish(group,'1_1',[0,0,0],0,sourceSha,packet)!;expect(r).toMatchObject({triangles:3,meshes:1,rejectedMeshes:0,materialVariants:3,byType:{1:1,2:1,5:1}});expect(triangles(mesh.geometry)).toEqual(before);for(const[n,a]of Object.entries(attrs))expect(mesh.geometry.getAttribute(n)).toBe(a);expect(mesh.material).toContain(material);expect(dispose).toHaveBeenCalledOnce();expect(applyRoadMaterialFinish(group,'1_1',[0,0,0],0,sourceSha,packet)).toBe(r);});
 it('uses the normalized art base exactly once, retains aggregate shading and maps, and never recolors the original',()=>{const{group,mesh,material,packet}=fixture(),sourceColor=material.color.clone();applyRoadMaterialFinish(group,'1_1',[0,0,0],0,sourceSha,packet);const finished:THREE.Material|THREE.Material[]=mesh.material;if(!Array.isArray(finished))throw new Error('Expected mixed road materials');const gravel=finished.find(m=>m.userData.townRoadSurfaceType===2);if(!(gravel instanceof THREE.MeshStandardMaterial))throw new Error('Expected gravel standard material');expect(gravel.color.toArray()).toEqual([.735,.695,.605]);expect(gravel.roughness).toBe(1);expect(gravel.normalScale.toArray()).toEqual([.38,.38]);expect(gravel.map).toBe(material.map);expect(gravel.normalMap).toBe(material.normalMap);expect(gravel.userData.townArt.kind).toBe('asphalt');const key=gravel.customProgramCacheKey(),color=gravel.color.clone();applyArtMaterial(gravel);expect(gravel.customProgramCacheKey()).toBe(key);expect(gravel.color).toEqual(color);expect(gravel.normalScale.toArray()).toEqual([.38,.38]);expect(material.color).toEqual(sourceColor);expect(material.userData.townArt).toBeUndefined();});
 it('retains a geometry and material still shared by another source mesh',()=>{const{group,mesh,geometry,material,packet}=fixture(),other=new THREE.Mesh(geometry,material);other.name='protected sibling';group.add(other);const gd=vi.spyOn(geometry,'dispose'),md=vi.spyOn(material,'dispose');applyRoadMaterialFinish(group,'1_1',[0,0,0],0,sourceSha,packet);expect(mesh.geometry).not.toBe(geometry);expect(other.geometry).toBe(geometry);expect(other.material).toBe(material);expect(gd).not.toHaveBeenCalled();expect(md).not.toHaveBeenCalled();});
 it('fails closed for stale identities, invalid assignments, non-asphalt and incomplete material groups',()=>{for(const mutate of[(f:ReturnType<typeof fixture>)=>f.packet.sourceSha256='b'.repeat(64),(f:ReturnType<typeof fixture>)=>f.packet.meshes[0].geometryStamp='12345678',(f:ReturnType<typeof fixture>)=>f.packet.meshes[0].assignments[0][0]=999,(f:ReturnType<typeof fixture>)=>f.material.name='Protected photo',(f:ReturnType<typeof fixture>)=>f.geometry.addGroup(0,3,0)]){const f=fixture();mutate(f);const r=applyRoadMaterialFinish(f.group,'1_1',[0,0,0],0,sourceSha,f.packet)!;expect(r.rejectedMeshes).toBe(1);expect(f.mesh.geometry).toBe(f.geometry);expect(f.mesh.material).toBe(f.material);}const{packet}=fixture();(packet.meshes[0].assignments as unknown[])=[null];expect(validRoadMaterialPacket(packet,'1_1',0)).toBe(false);});
});
