import fs from 'node:fs';import os from 'node:os';import{fileURLToPath,pathToFileURL}from'node:url';import path from 'node:path';import{createHash}from'node:crypto';import{gzipSync}from'node:zlib';import{build}from'esbuild';import * as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const here=path.dirname(fileURLToPath(import.meta.url));
const site=path.resolve(here,'../../..');
const work=process.env.WEBSTER_PARKING_AUDIT_DIR?path.resolve(process.env.WEBSTER_PARKING_AUDIT_DIR):fs.mkdtempSync(path.join(os.tmpdir(),'webster-parking-audit-'));
fs.mkdirSync(work,{recursive:true});
const dependencies=path.join(work,'node_modules');
if(!fs.existsSync(dependencies))fs.symlinkSync(path.join(site,'node_modules'),dependencies,'dir');
if(fs.realpathSync(dependencies)!==fs.realpathSync(path.join(site,'node_modules')))throw Error('Audit dependency directory points to a different runtime.');
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');
function readPublic(ref){const raw=fs.readFileSync(path.join(site,'public',ref.url.replace(/^\//,'')));if(raw.length!==ref.bytes)throw Error('Asset size mismatch '+ref.url);if(ref.sha256&&sha(raw)!==ref.sha256)throw Error('Asset hash mismatch '+ref.url);return JSON.parse(raw);}
const compiled=path.join(work,'compiled.mjs');
await build({entryPoints:[path.join(here,'entry.ts')],outfile:compiled,bundle:true,platform:'node',format:'esm',external:['three'],logLevel:'silent'});
const{applyParkingFinish,layoutParking,validParkingPacket,applyMeasuredBridgeSurface,applyTerrainFinish,applyRoadFinish,validateRoadFinish}=await import(pathToFileURL(compiled).href);
const release=read(site+'/data/derived/town/release.json'),base=site+'/public/town-assets/'+release.directory,manifest=read(base+'/manifest.json'),catalog=read(site+'/data/derived/town/paved-surfaces-index.json'),terrainIndex=read(site+'/data/derived/town/terrain-finish-index.json'),roadIndex=read(site+'/data/derived/town/road-finish-index.json');
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'AUDIT_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const mats=o=>Array.isArray(o.material)?o.material:[o.material],vec=new THREE.Vector3(),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function meshHash(o){const g=o.geometry;return sha(Buffer.concat([...Object.entries(g.attributes).flatMap(([k,a])=>[Buffer.from(k),Buffer.from(a.array.buffer,a.array.byteOffset,a.array.byteLength)]),...(g.index?[Buffer.from(g.index.array.buffer,g.index.array.byteOffset,g.index.array.byteLength)]:[]),Buffer.from(JSON.stringify([g.groups,o.matrix.toArray(),mats(o).map(m=>m.uuid)]))]));}
function triangles(group,origin){const result=[];group.updateMatrixWorld(true);const inv=group.matrixWorld.clone().invert();group.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const isTerrain=/^terrain(?:\b|_)/i.test(o.name),g=o.geometry,p=g.getAttribute('position'),mat=mats(o),total=g.index?.count??p.count,matrix=inv.clone().multiply(o.matrixWorld);for(const part of g.groups.length?g.groups:[{start:0,count:total,materialIndex:0}]){const apron=/parking apron asphalt/.test(mat[part.materialIndex??0]?.name??'');if(!isTerrain&&!apron)continue;for(let i=part.start;i+2<Math.min(total,part.start+part.count);i+=3){const tri=[0,1,2].map(k=>{vec.fromBufferAttribute(p,g.index?g.index.getX(i+k):i+k).applyMatrix4(matrix);return[vec.x+origin[0],-vec.z-origin[2],vec.y+origin[1]];});if(Math.abs(cross(...tri))>1e-8)result.push({tri,apron});}}});return result;}
function supportIndex(tris){const grid=new Map();for(const row of tris){const xs=row.tri.map(p=>p[0]),ys=row.tri.map(p=>p[1]);for(let x=Math.floor(Math.min(...xs)/5);x<=Math.floor(Math.max(...xs)/5);x++)for(let y=Math.floor(Math.min(...ys)/5);y<=Math.floor(Math.max(...ys)/5);y++){const key=x+','+y,list=grid.get(key)??[];list.push(row);grid.set(key,list);}}return p=>{const heights=[];for(const{tri,apron}of grid.get(Math.floor(p[0]/5)+','+Math.floor(p[1]/5))??[]){const[a,b,c]=tri,d=cross(a,b,c),u=cross(a,p,c)/d,v=cross(a,b,p)/d;if(u>=-1e-5&&v>=-1e-5&&u+v<=1.00001)heights.push({z:a[2]+u*(b[2]-a[2])+v*(c[2]-a[2]),apron});}return heights;};}
const report={sourceIndexSha256:sha(fs.readFileSync(site+'/data/derived/town/paved-surfaces-index.json')),parkingRuntimeSha256:sha(fs.readFileSync(site+'/src/lib/town/parking-finish.ts')),terrainIndexSha256:sha(fs.readFileSync(site+'/data/derived/town/terrain-finish-index.json')),terrainRuntimeSha256:sha(fs.readFileSync(site+'/src/lib/town/terrain-finish.ts')),roadRuntimeSha256:sha(fs.readFileSync(site+'/src/lib/town/road-finish.ts')),sourceManifestSha256:sha(fs.readFileSync(base+'/manifest.json')),scope:'Native GLTFLoader: all 24 parking tiles at LOD0/1/2. Exact source geometry, UVs and normals; texture pixels stubbed. Final per-LOD terrain packets from the complete town index, measured bridge corrections and road finishing are applied before parking.',tiles:[],failures:[]},exported={lots:{},tiles:[]};
for(const[tid,ref]of Object.entries(catalog.lotAssets)){
 const packet=readPublic(ref);if(!validParkingPacket(packet,tid))throw Error('Actual packet rejected '+tid);for(const lot of packet.lots)exported.lots[lot.id]={lot,bays:layoutParking(lot)};
 const tile=manifest.tiles.find(t=>t.id===tid),road=roadIndex.tiles[tid]?validateRoadFinish(readPublic(roadIndex.tiles[tid]),tid):undefined;
 for(const lod of tile.lods){
  const terrainRef=terrainIndex.tiles[tid]?.levels[String(lod.level)],terrain=terrainRef?readPublic(terrainRef):undefined;
  if(terrainRef&&terrain.levels.find(row=>row.level===lod.level)?.sourceSha256!==lod.sha256)throw Error('Terrain packet is not bound to this source LOD: '+tid+'/'+lod.level);
  const raw=fs.readFileSync(base+'/'+lod.url),gltf=await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),pathToFileURL(path.dirname(base+'/'+lod.url)+path.sep).href),scene=gltf.scene,fail=[];applyMeasuredBridgeSurface(scene,tid,tile.origin);const tr=applyTerrainFinish(scene,tid,tile.origin,lod.level,terrain);if(tr.rejected)fail.push('Terrain patch rejected');if(terrainRef&&tr.replacedTriangles!==terrainRef.replacedTriangles)fail.push('Terrain replacement count differs from final index');applyRoadFinish(scene,tid,tile.origin,lod.level,road);scene.updateMatrixWorld(true);const original=new Map();scene.traverse(o=>{if(o instanceof THREE.Mesh)original.set(o,meshHash(o));});const source=triangles(scene,tile.origin),heights=supportIndex(source);const result=applyParkingFinish(scene,tid,tile.origin,packet),paint=scene.children.find(o=>o.name==='Finished parking | authored bays');let normalError=0,unsupported=0,maxHeightError=0,belowSupport=0,geometry=[];
  for(const[o,h]of original)if(meshHash(o)!==h)fail.push('Protected source changed '+o.name);
  const allGeometry=[];
  for(const [surface,offset,kind]of [[paint,.014,'paint'],[scene.children.find(o=>o.name==='Finished parking | tree planting beds'),.012,'beds'],[scene.children.find(o=>o.name==='Finished parking | asphalt'),.006,'paving']]) {
   if(!surface)continue;const vertices=[],p=surface.geometry.getAttribute('position'),n=surface.geometry.getAttribute('normal');for(let i=0;i<p.count;i++){const point=[p.getX(i)+tile.origin[0],-p.getZ(i)-tile.origin[2],p.getY(i)+tile.origin[1]];vertices.push(point);normalError=Math.max(normalError,Math.abs(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))-1));if(!point.every(Number.isFinite))fail.push('Nonfinite '+kind);}
   for(let i=0;i<vertices.length;i+=3){const t=vertices.slice(i,i+3),p=[0,1,2].map(k=>(t[0][k]+t[1][k]+t[2][k])/3),hits=heights(p);if(!hits.length){unsupported++;continue;}const max=Math.max(...hits.map(r=>r.z)),closest=Math.min(...hits.map(r=>Math.abs(p[2]-r.z-offset)));maxHeightError=Math.max(maxHeightError,closest);if(p[2]<max-.001)belowSupport++;}
   if(kind==='paint')geometry=vertices;allGeometry.push({kind,vertices});
  }
  if(normalError>1e-4)fail.push('Nonunit normals '+normalError);if(unsupported)fail.push('Unsupported paint '+unsupported);if(maxHeightError>.002)fail.push('Paint height gap '+maxHeightError);if(belowSupport)fail.push('Paint below higher support '+belowSupport);if(applyParkingFinish(scene,tid,tile.origin,packet)!==result)fail.push('Not idempotent');
  const row={tileId:tid,level:lod.level,sourceSha256:sha(raw),...result,terrainPacket:terrainRef??null,terrainPatch:tr,sourceMeshCount:original.size,normalError,unsupported,maxHeightError,belowSupport,failures:fail};report.tiles.push(row);if(fail.length)report.failures.push(row);exported.tiles.push({tileId:tid,level:lod.level,paintVertices:geometry,surfaces:allGeometry});console.log(JSON.stringify(row));
  const materials=new Set(),textures=new Set(),geometries=new Set();scene.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const m of mats(o)){materials.add(m);for(const value of Object.values(m))if(value instanceof THREE.Texture)textures.add(value);}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());
 }
}
if(report.parkingRuntimeSha256!==sha(fs.readFileSync(site+'/src/lib/town/parking-finish.ts')))report.failures.push({issue:'Runtime changed during audit'});if(report.terrainIndexSha256!==sha(fs.readFileSync(site+'/data/derived/town/terrain-finish-index.json')))report.failures.push({issue:'Terrain index changed during audit'});report.status=report.failures.length?'FAIL':'PASS';report.summary={tileLods:report.tiles.length,terrainAppliedCases:report.tiles.filter(r=>r.terrainPatch.meshes>0).length,replacedTerrainTriangles:report.tiles.reduce((s,r)=>s+r.terrainPatch.replacedTriangles,0),uniqueLots:Object.keys(exported.lots).length,bays:Object.values(exported.lots).reduce((s,r)=>s+r.bays.length,0),surfaceTriangles:report.tiles.reduce((s,r)=>s+r.triangles,0)};fs.writeFileSync(work+'/native-report.json',JSON.stringify(report,null,2));fs.writeFileSync(work+'/native-geometry.json.gz',gzipSync(JSON.stringify(exported)));console.log('FINAL',report.status,report.summary);if(report.failures.length)process.exitCode=1;
