import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import sharp from'sharp';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../..'),out=path.join(repo,'public/town-finish/v1/art');fs.mkdirSync(out,{recursive:true});const sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p)),release=read(path.join(repo,'data/derived/town/release.json')),old=fs.readFileSync(path.join(repo,'public/town-assets',release.directory,'textures/leaf-cluster.png'));
const random=n=>{const q=Math.sin(n*123.127+7.35)*43567.391;return q-Math.floor(q);},shapes=[],veins=[],branches=[];let leaves=0;
function leaf(x,y,angle,length,width,seed){const lobed=seed%4===0,points=[];for(const side of[1,-1]){const samples=Array.from({length:19},(_,i)=>(side===1?i:18-i)/18);for(const t of samples){const breadth=Math.pow(Math.sin(Math.PI*t),.80)*width*.5*(lobed?1+.12*Math.sin(t*Math.PI*7):1+.035*Math.sin(t*Math.PI*13));points.push([t*length,side*breadth*(1+.07*Math.sin(t*6+seed))]);}}const dark=seed%5===0?'#516837':seed%3===0?'#607847':'#58723e',light=seed%3===0?'#728549':'#647d43';const d=points.map((p,i)=>(i?'L':'M')+p.map(n=>n.toFixed(2)).join(',')).join(' ')+' Z';shapes.push(`<g transform="translate(${x.toFixed(2)},${y.toFixed(2)}) rotate(${angle.toFixed(2)})"><path d="${d}" fill="${dark}"/><path d="${d}" fill="${light}" opacity=".18"/><path d="M1,0 Q${length*.42},${width*.035} ${length*.93},0" fill="none" stroke="#a2a85d" stroke-width=".75" opacity=".30"/>${[.28,.46,.64,.79].map(t=>`<path d="M${length*t},0 Q${length*(t+.06)},${width*.11} ${length*(t+.09)},${width*.30*Math.sin(Math.PI*t)} M${length*t},0 Q${length*(t+.06)},${-width*.11} ${length*(t+.09)},${-width*.30*Math.sin(Math.PI*t)}" fill="none" stroke="#89994f" stroke-width=".50" opacity=".23"/>`).join('')}</g>`);leaves++;}
branches.push('<path d="M252,485 C240,357 260,216 260,30" stroke="#666139" stroke-width="4.5" fill="none"/>');
let seed=0;
for(let tier=0;tier<10;tier++)for(const side of[-1,1]){const y=441-tier*39+(random(tier*3+side+21)-.5)*30,extent=100+Math.sin(tier/10*Math.PI)*48+(random(tier+side+32)-.5)*34,ex=254+side*extent,ey=y-48-13*random(tier+43);branches.push(`<path d="M${254},${y} Q${254+side*extent*.51},${y-18} ${ex},${ey}" stroke="#676d3d" stroke-width="${2.2-tier*.06}" fill="none"/>`);for(let q=0;q<3;q++){const f=.32+q*.29,x=254+side*extent*f,cy=y+(ey-y)*f,angle=side===1?(-40+(q%2)*65):(-140-(q%2)*65),len=54+random(seed+73)*21,w=25+random(seed+81)*7;leaf(x,cy,angle+(random(seed+101)-.5)*35,len,w,seed++);}}
for(let i=0;i<4;i++)leaf(260+(random(i+99)-.5)*9,52+i*23,-95+(i%2?30:-25),53+random(i)*16,25,i+90);
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><g transform="translate(24,35) scale(.90,.86)">${branches.join('')}${shapes.join('')}</g></svg>\n`;fs.writeFileSync(path.join(here,'leaf-cluster.svg'),svg);const png=await sharp(Buffer.from(svg)).resize(512,512).png({compressionLevel:9}).toBuffer(),hash=sha(png),file=`leaf-cluster-${hash.slice(0,12)}.png`;fs.writeFileSync(path.join(out,file),png);for(const previous of fs.readdirSync(out))if(/^leaf-cluster-[0-9a-f]{12}\.png$/.test(previous)&&previous!==file)fs.unlinkSync(path.join(out,previous));
const raw=await sharp(png).ensureAlpha().raw().toBuffer(),original=await sharp(old).ensureAlpha().raw().toBuffer(),stats=b=>{let opaque=0;const rgb=[0,0,0];for(let i=0;i<b.length;i+=4)if(b[i+3]>=97){opaque++;for(let c=0;c<3;c++)rgb[c]+=b[i+c];}return{opaquePixels:opaque,coverage:opaque/(512*512),meanSRGB:rgb.map(v=>v/opaque/255)};};
const manifest={version:1,sourceManifestSha256:release.manifestSha256??'37fbef34bc2a4467997252be75b4c43174a6a7b2d39963614cadd8d787e56105',sourceUri:'../textures/leaf-cluster.png',sourceSha256:sha(old),url:'/town-finish/v1/art/'+file,sha256:hash,bytes:png.length,width:512,height:512,originalVectorSha256:sha(svg),leafShapes:leaves,evidence:'ART-040. Original authored curved broadleaf cluster, regional late-summer interpretation; no photographed tree or verified species. Finer leaf shapes replace the source atlas stars without changing twig anchors, card geometry, UVs or texture dimensions.',original:stats(original),replacement:stats(raw)};fs.writeFileSync(path.join(repo,'data/derived/town/leaf-atlas.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify(manifest,null,2));
