import fs from'node:fs';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{gzipSync}from'node:zlib';import{build}from'esbuild';import * as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.WEBSTER_UTILITY_QA||'/private/tmp/webster-final-details/utilities';fs.mkdirSync(work,{recursive:true});fs.mkdirSync(path.join(work,'geometry'),{recursive:true});if(!fs.existsSync(path.join(work,'node_modules')))fs.symlinkSync(path.join(repo,'node_modules'),path.join(work,'node_modules'));
const compiled=path.join(work,'utility-native.mjs');await build({entryPoints:[path.join(repo,'scripts/utility_site_details/entry.ts')],outfile:compiled,bundle:true,platform:'node',format:'esm',external:['three'],logLevel:'silent'});const{applyUtilitySiteDetails,excludedTreeAnchors,planDistanceSquared,applyTerrainFinish,applyRoadFinish,validateRoadFinish}=await import(pathToFileURL(compiled).href);
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),fileSha=p=>sha(fs.readFileSync(p)),data=read(path.join(repo,'data/derived/town/utility-site-details.json')),release=read(path.join(repo,'data/derived/town/release.json')),assets=path.join(repo,'public/town-assets',release.directory),manifest=read(path.join(assets,'manifest.json'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'REFERENCE_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const report={version:1,scope:'Actual GLTFLoader all WWTP tile LODs; exact retained source geometry, materials and transforms. New geometry normals/winding/envelopes and actual tree-exclusion indices. Terrain and body triangles exported for independent plan-intersection proof.',sourceManifestSha256:fileSha(path.join(assets,'manifest.json')),runtimeSha256:fileSha(path.join(repo,'src/lib/town/utility-site-details.ts')),dataSha256:fileSha(path.join(repo,'data/derived/town/utility-site-details.json')),results:[],failures:[]};
function stamp(mesh){const g=mesh.geometry,attrs=Object.entries(g.attributes).map(([name,a])=>[name,a.count,a.itemSize,sha(Buffer.from(a.isInterleavedBufferAttribute?a.data.array.buffer:a.array.buffer))]);return sha(Buffer.from(JSON.stringify([attrs,g.index?sha(Buffer.from(g.index.array.buffer)):null,g.groups,mesh.matrixWorld.toArray(),(Array.isArray(mesh.material)?mesh.material:[mesh.material]).map(m=>m.uuid)])));}
for(const tileId of [...new Set(data.rows.map(r=>r.tileId))]){const tile=manifest.tiles.find(t=>t.id===tileId),rows=data.rows.filter(r=>r.tileId===tileId);for(const lod of tile.lods){const raw=fs.readFileSync(path.join(assets,lod.url));if(sha(raw)!==lod.sha256)throw Error('Source SHA mismatch');const scene=(await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),'')).scene;const surfaceStages=[];if(process.env.UTILITY_WITH_SURFACE_FINISH==='1'){
 const terrain=read(path.join(repo,'data/derived/town/terrain-finish-index.json')).tiles[tile.id]?.levels[String(lod.level)];if(terrain){const bytes=fs.readFileSync(path.join(repo,'public',terrain.url));if(sha(bytes)!==terrain.sha256)throw Error('Terrain packet SHA');const packet=JSON.parse(bytes);surfaceStages.push({name:'terrain',sha256:terrain.sha256,report:applyTerrainFinish(scene,tile.id,tile.origin,lod.level,packet)});}
 const road=read(path.join(repo,'data/derived/town/road-finish-index.json')).tiles[tile.id];if(road){const bytes=fs.readFileSync(path.join(repo,'public',road.url));if(sha(bytes)!==road.sha256)throw Error('Road packet SHA');const rows=validateRoadFinish(JSON.parse(bytes),tile.id);surfaceStages.push({name:'road',sha256:road.sha256,report:applyRoadFinish(scene,tile.id,tile.origin,lod.level,rows)});}
 }scene.updateMatrixWorld(true);const before=[];scene.traverse(o=>{if(o instanceof THREE.Mesh)before.push({o,g:o.geometry,m:o.material,hash:stamp(o)});});
 const result=applyUtilitySiteDetails(scene,tile.id,tile.origin,lod.level,lod.sha256),failures=[];scene.updateMatrixWorld(true);for(const b of before)if(b.o.geometry!==b.g||b.o.material!==b.m||stamp(b.o)!==b.hash)failures.push('Source object altered '+b.o.name);
 if(result.status!=='applied'||result.ids.length!==rows.length)failures.push('Unmatched');if(applyUtilitySiteDetails(scene,tile.id,tile.origin,lod.level,lod.sha256)!==result)failures.push('Idempotence');
 let maxNormalError=0,minWinding=1,degenerate=0,maxOutsetM=0,minimumY=Infinity,maximumY=-Infinity;const meshes=[],sourceTriangles=[];
 scene.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const g=o.geometry,p=g.getAttribute('position'),n=g.getAttribute('normal');if(o.userData.category==='utility-site'){
  meshes.push({name:o.name,sourceIds:o.userData.sourceIds,positions:Array.from(p.array)});const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),actual=new THREE.Vector3(),given=new THREE.Vector3();
  for(let i=0;i<p.count;i++){const x=p.getX(i)+tile.origin[0],y=p.getY(i)+tile.origin[1],north=-(p.getZ(i)+tile.origin[2]);if(![x,y,north].every(Number.isFinite))failures.push('Nonfinite');minimumY=Math.min(minimumY,y);maximumY=Math.max(maximumY,y);maxOutsetM=Math.max(maxOutsetM,Math.sqrt(Math.min(...rows.map(r=>planDistanceSquared(r.outline,x,north)))));maxNormalError=Math.max(maxNormalError,Math.abs(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))-1));}
  for(let i=0;i<p.count;i+=3){a.fromBufferAttribute(p,i);b.fromBufferAttribute(p,i+1).sub(a);c.fromBufferAttribute(p,i+2).sub(a);actual.crossVectors(b,c);if(actual.length()<1e-8){degenerate++;continue;}minWinding=Math.min(minWinding,actual.normalize().dot(given.fromBufferAttribute(n,i)));}
 }else{const ix=g.index,count=ix?.count??p.count,mats=Array.isArray(o.material)?o.material:[o.material];for(const part of g.groups.length?g.groups:[{start:0,count,materialIndex:0}])for(let i=part.start;i<Math.min(count,part.start+part.count);i+=3){const pts=[0,1,2].map(k=>{const v=new THREE.Vector3().fromBufferAttribute(p,ix?ix.getX(i+k):i+k).applyMatrix4(o.matrixWorld).add(new THREE.Vector3(...tile.origin));return[v.x,-v.z,v.y];});const bounds=[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1])),Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))];if(rows.some(r=>{const x=r.outline.map(p=>p[0]),y=r.outline.map(p=>p[1]);return bounds[0]<=Math.max(...x)+.2&&bounds[2]>=Math.min(...x)-.2&&bounds[1]<=Math.max(...y)+.2&&bounds[3]>=Math.min(...y)-.2;}))sourceTriangles.push({material:mats[part.materialIndex??0].name,category:o.parent?.name||o.name,points:pts});}}
 });
 if(maxNormalError>1e-5||minWinding<.99||degenerate||maxOutsetM>.05)failures.push('Geometry QA '+JSON.stringify({maxNormalError,minWinding,degenerate,maxOutsetM}));if(minimumY<Math.min(...rows.map(r=>r.base))-.001||maximumY>Math.max(...rows.map(r=>r.rim+r.railHeightM))+.04)failures.push('Height envelope');
 const treeRef=tile.treeFile,treeRaw=fs.readFileSync(path.join(assets,treeRef.url));if(sha(treeRaw)!==treeRef.sha256)throw Error('Tree SHA mismatch');const treeRows=JSON.parse(treeRaw),excluded=[...excludedTreeAnchors(treeRows,tile.origin,scene.userData.environmentTreeExclusions)];if(excluded.join()!=='126')failures.push('Unexpected tree exclusion '+excluded);
 const exportPath=path.join(work,'geometry',`${tile.id}-${lod.level}.json.gz`),blob=gzipSync(Buffer.from(JSON.stringify({tileId:tile.id,level:lod.level,origin:tile.origin,meshes,sourceTriangles})));fs.writeFileSync(exportPath,blob);
 const entry={surfaceStages,tileId,level:lod.level,origin:tile.origin,sourceSha256:lod.sha256,...result,sourceMeshesRetained:before.length,sourceTreeFileSha256:treeRef.sha256,sourceTreeCount:treeRows.length,excludedTreeIndices:excluded,maxNormalError,minWinding,degenerate,maxOutsetM,minimumY,maximumY,geometryExport:{path:exportPath,sha256:sha(blob),bytes:blob.length},failures};report.results.push(entry);if(failures.length)report.failures.push(entry);console.log(JSON.stringify(entry));const gs=new Set(),ms=new Set(),ts=new Set();scene.traverse(o=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v instanceof THREE.Texture)ts.add(v);}}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());
}}
report.status=report.failures.length?'FAIL':'PASS';fs.writeFileSync(path.join(work,'utility-native-audit.json'),JSON.stringify(report,null,2));console.log(report.status);if(report.failures.length)process.exitCode=1;
