const CONSTRAINTS =
  'No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no liquid droplets, no steam, no exposed silicon touching coolant, no RGB lighting, no shallow depth of field, no fisheye distortion, no extreme perspective, no missing module symmetry unless intentionally specified, no extra memory stacks.';

export const SCENE_THREE_ASSET_PROMPTS = {
  assetA: `One vendor neutral liquid cooled AI compute tray partially extracted from a rack, straight three quarter top view with minimal perspective distortion, dark graphite metal chassis, service handle visible, front edge clean, no labels, no logos, no text, no human hands, premium data center engineering realism, MGX inspired proportions, dense and precise industrial detailing, neutral gray background, tray centered with generous padding, cinematic but restrained lighting, designed as a zoom bridge from rack scale to board scale. ${CONSTRAINTS}`,
  assetB: `The exact same compute tray as the reference image, same camera, same scale, same background, top shell removed, internal hardware visible, four large liquid cooled accelerator regions arranged cleanly, two CPU regions, tray manifold and cold plate plumbing visible, edge networking modules and accessory boards present, fan zones only in lower power areas, no text, no labels, no logos, no neon, no gaming motherboard aesthetics, high trust technical illustration with realistic industrial materials. ${CONSTRAINTS}`,
  assetC: `The exact same opened compute tray and same camera as reference, engineering x ray illustration, cold plates semi transparent, compute board and component footprints visible below, selected accelerator module area visually clear and centered for later overlays, believable board power delivery regions around accelerator sites, high speed connector regions at board edges, manifold lines still visible, no text, no labels, no logos, premium museum quality technical cutaway, accuracy prioritized over drama. ${CONSTRAINTS}`,
  assetD: `Single vendor neutral AI compute board isolated on neutral matte background, exact top orthographic, extracted from a liquid cooled compute tray, multiple accelerator module sites, fabric or switch blocks, host side compute regions, networking edge I O, and visible power delivery zones, dark PCB with restrained copper and nickel details, no text, no labels, no logos, no impossible routing, no consumer motherboard styling, ultra crisp technical illustration. ${CONSTRAINTS}`,
  assetE: `One modern AI accelerator module isolated from its board, exact top orthographic macro view, module substrate and local board context visible, meaningful surrounding power delivery components, high speed interconnect pads or connector regions at edges, package cover area centered and clean, data center hardware realism, no text, no labels, no logos, no decorative branding, premium technical product photography merged with engineering illustration. ${CONSTRAINTS}`,
  assetF: `One modern HBM accelerator package, exact top orthographic macro, package lid removed or transparent enough to reveal internal structure, one central compute die region and exactly five surrounding HBM stack footprints on the same package in a believable asymmetrical Hopper class shipping product arrangement, dark package substrate, interposer hint below, edge package contacts and link exits, no text, no labels, no logos, no six stack symmetry, no consumer GPU look, scientific instrument clarity. ${CONSTRAINTS}`,
  assetG: `Exploded side cutaway of the same accelerator package and cooling stack, perfectly centered, engineering cross section, from bottom upward show board, package attach region, substrate or interposer, central compute die, adjacent HBM stacks, lid or heat spreader, thin thermal interface layer, and cold plate above with internal serpentine or microchannel like coolant passages, inlet and outlet tubes entering the cold plate, coolant fully confined inside the cold plate only, no liquid touching silicon, no immersion look, no labels, no logos, no text, clean premium technical illustration. ${CONSTRAINTS}`,
  assetH: `The same accelerator package geometry and same side cutaway framing as the reference liquid cooled stack, but replace the cold plate with a passive fin stack optimized for front to back system airflow, show soft airflow ribbons moving through the fins, no liquid hardware, no tiny attached fans, data center passive accelerator cooling not gaming GPU cooling, no text, no labels, no logos, same material palette and camera as the liquid cooled version. ${CONSTRAINTS}`,
  assetI: `The same modern AI accelerator package from the top view, package frame and HBM stacks still visible but dimmed, central compute die enlarged and visually isolated as the next zoom target, outer package geometry fading softly into background, no text, no labels, no logos, no dramatic effects, designed as a clean visual bridge into an internal die architecture scene. ${CONSTRAINTS}`,
} as const;
