const CONSTRAINTS_TAIL =
  'No text generation inside image, no numbers, no brand marks, no impossible cable routing, no sci fi glow, no exaggerated liquid tubing, no floating UI elements, no human hands, no dust, no dramatic depth of field, no fisheye lens, no extreme perspective distortion.';

export const SCENE_TWO_ASSET_PROMPTS = {
  rackRow: `Wide 16 by 9 engineering hero illustration of four vendor neutral high density AI racks in a modern data center aisle, camera straight on at human chest height, all racks aligned perfectly, dark graphite rack frames, one center rack subtly brighter than the others, front views only, MGX inspired rack scale geometry, repeating thin compute trays, distinct switch tray regions, small management area near the top, clear power conversion region, no logos, no text, no people, no cables on the floor, no glowing sci fi effects, no neon, no RGB, realistic but restrained industrial lighting, deep charcoal environment, enough empty negative space on the left for website copy, crisp edges, premium technical illustration style. ${CONSTRAINTS_TAIL}`,
  rackFront: `Single vendor neutral AI rack, exact front elevation, orthographic and perspective free, centered, isolated on matte dark gray background, rack scale AI system inspired by current liquid cooled MGX designs, repeated compute tray openings, distinct internal switch tray zones, small management modules near top, visible but understated power shelf region, dark anodized metal, subtle vent perforations, perfect symmetry, no cables, no labels, no text, no logos, no transparent door, minimal shadow, engineering illustration, ultra crisp, clean industrial realism. ${CONSTRAINTS_TAIL}`,
  rackRear: `Same rack as previous image, exact rear elevation, orthographic and perspective free, same scale and camera distance as matching front elevation, centered on same matte dark gray background, rear service side visible, vertical liquid manifolds, coolant inlets and outlets, cable management spines, cable cartridge area, power bus bar channel, service access structure, restrained hose stubs or quick disconnect fittings, no labels, no text, no logos, no humans, no decorative reflections, premium technical illustration, clean industrial realism. ${CONSTRAINTS_TAIL}`,
  rackExploded: `Exploded axonometric technical rendering of a vendor neutral rack scale AI rack, frame, compute trays, switch trays, management modules, power shelves, rear manifolds, bus bar, and cable spines separated cleanly along the depth axis, every module perfectly aligned to original rack geometry, dark graphite metals with neutral surfaces only, no text, no labels, no logos, no floating fantasy parts, no extreme perspective, museum quality engineering cutaway, highly legible separation between front modules and rear infrastructure, suitable for vector overlays. ${CONSTRAINTS_TAIL}`,
  rackHybridCutaway: `Single vendor neutral AI rack partial cutaway, front half opaque and rear half semi transparent, selected compute trays visible inside, selected CPU and GPU locations hinted as warm internal zones, cyan coolant path infrastructure visible only in rear manifolds and tray cold plate regions, soft white airflow cues around networking, storage, and power shelf regions, absolutely no liquid touching bare chips, no immersion tank appearance, no steam, no water droplets, no labels, no text, no logos, precise technical illustration with premium cinematic finish. ${CONSTRAINTS_TAIL}`,
  rackAirCooled: `Single air cooled AI server rack, three quarter front view but still technically clean, passive accelerator cards housed inside server nodes, strong front to back airflow cues, perforated front surfaces, visible fan wall or chassis airflow architecture, no liquid manifolds, no hoses, dark graphite data center materials, no logos, no text, no people, no gaming aesthetics, no colorful LEDs, quiet engineering realism, designed to contrast with a liquid cooled rack. ${CONSTRAINTS_TAIL}`,
  trayExtracted: `One compute tray partially extracted from a rack scale AI rack, tray centered and larger than rest of rack, rails visible, rear connector region suggested, coolant interface region implied but not exaggerated, other rack modules dimmed behind it, same graphite material palette as previous assets, no loose cables, no labels, no text, no logos, premium service manual realism with cinematic clarity, intended as a zoom bridge into board and package level scenes. ${CONSTRAINTS_TAIL}`,
} as const;
