export const SCENE_FIVE_ASSET_PROMPTS = {
  sceneFourBridge:
    'Exact same advanced compute die silhouette and camera as the previous scene, top orthographic, package context barely ghosted around the die, on package memory shapes very faint, die centered and dominant, dark neutral silicon and graphite palette, no labels, no logos, no text, no glowing activity yet, calm premium semiconductor realism, designed as a transition from architecture map to workload animation, large empty space below the die reserved for a future vector token strip, no fantasy circuitry, no sci fi lighting. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  prefillHero:
    'Wide premium technical scene plate for an interactive web explainer, centered advanced compute die underlay with subtle district texture but no explicit blocks, generous empty right margin reserved for a vector key and value cache wall, generous lower margin reserved for a vector token by layer grid, dark matte background, restrained silicon reflections only, no labels, no numbers, no logos, no perspective distortion, no activity lines, museum quality engineering aesthetic. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  layerInspector:
    'Clean dark glass and graphite technical panel background for a decoder only transformer layer inspector, rectangular and orthographic, subtle internal structure only, no labels, no icons, no text, no fake equations, premium scientific instrument aesthetic, designed to accept vector overlays for normalization, query key value projections, masked attention, output projection, and feed forward stages. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  causalPanel:
    'Orthographic square technical panel with a faint lower triangular field suggested only through material treatment and lighting, no visible tokens, no labels, no text, no numbers, no grid coordinates, no mathematical symbols, dark glass and ceramic palette, clean enough for crisp vector overlays, no neon, no heat map colors, premium lab instrument style. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  cacheWall:
    'Tall narrow premium technical panel intended for a key and value cache wall, orthographic, subtle horizontal and vertical segmentation hints only, dark graphite and smoked glass materials, no text, no labels, no numbers, no icons, no glowing cells, no memory chip photography, designed to accept vector rows and columns later. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  chunkedCompare:
    'Split scene technical underlay for comparing full prefill and chunked prefill, two identical dark panels side by side with matching geometry, each with a reserved lower strip for token blocks and a reserved upper region for tiny timing lanes, no text, no labels, no numbers, no fake charts, exact same camera and lighting on both halves, premium systems engineering aesthetic. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  cachedPrefix:
    'Technical underlay for a cached prefix comparison, one wide orthographic panel with a faint distinction between a left prefix region and a right uncached suffix region, no tokens visible yet, no labels, no text, no numbers, dark neutral palette, subtle sense of stored memory on the left and fresh work area on the right, designed for vector overlays. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
  sceneSixBridge:
    'Same advanced compute die and same camera as the reference underlay, but with one narrow bright readiness corridor subtly suggested through material emphasis from memory gateways toward the main compute districts, no actual activity overlays, no text, no logos, no symbols, designed as a clean transition from broad prefill to narrow decode. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no sci fi glow, no shallow depth of field, no fisheye distortion, no extreme perspective, no accidental heat maps, no extra memory stacks, no additional chips, no floating UI.',
} as const;
