export const SCENE_FOUR_ASSET_PROMPTS = {
  packageToDieBridge:
    'Exact top orthographic macro view of a modern AI accelerator package transitioning into an exposed bare silicon die, package frame and on-package HBM stacks barely visible as dim ghosted silhouettes around the die, central die perfectly centered and dominant, neutral dark graphite and silicon palette, no labels, no logos, no text, no fantasy circuitry, no glowing sci-fi effects, museum quality technical realism, designed as a transition plate from package scale to die scale. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
  bareDieMaterial:
    'Top orthographic macro of a large advanced compute die with realistic bare silicon surface, subtle metal routing sheen, faint reticle-like texture, crisp rectangular outline, dark neutral background, absolutely no labels, no logos, no etched text, no dramatic reflections, no shallow depth of field, premium semiconductor photography merged with restrained engineering illustration. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
  dieUnderlay:
    'Ultra clean top orthographic bare silicon underlay for a large rectangular accelerator die, uniform neutral silicon tone with very subtle internal texture only, designed to accept vector overlays for compute districts, cache corridor, edge memory controllers, and interconnect ports, no visible blocks, no labels, no logos, no text, no perspective distortion, no color cast. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
  smTexture:
    'Orthographic macro crop of an advanced compute die region with repeated dense silicon structures suggesting a tiled compute neighborhood, highly regular and precise, suitable as a background texture behind vector overlays for one streaming multiprocessor reveal, no labels, no logos, no readable text, no fantasy patterns, no consumer GPU styling, calm scientific realism. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
  heatTexture:
    'Abstract but physically plausible semiconductor heat map texture for a large compute die, smooth gradients with clustered hotspot regions and cooler interconnect corridors, dark background, no labels, no numbers, no legend, no fire effects, no thermal camera gimmicks, designed as an underlay for a web-based vector heat overlay. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
  sceneFiveBridge:
    'Top orthographic advanced compute die with package context faded away, repeated compute districts visible as clean geometric fields, central corridor subtly emphasized, overall image intentionally calm and ready for animated token activity overlays, no labels, no logos, no text, no science fiction glow, premium technical illustration. No text generation inside image, no numbers, no brand marks, no fantasy circuitry, no neon, no steam, no liquid channels, no exposed coolant, no shallow depth of field, no fisheye distortion, no dramatic perspective, no decorative particle effects.',
} as const;
