import fs from'node:fs';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{gzipSync}from'node:zlib';import{build}from'esbuild';import*as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.DOCK_APPROACH_WORK??'/private/tmp/webster-finished-game/dock-approaches';fs.mkdirSync(work,{recursive:true});const read=p=>JSON.parse(fs.readFileSync(p)),release=read(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=read(base+'manifest.json');
fs.writeFileSync(work+'/entry.ts',['bridge-surface','terrain-finish','environment-ground','dock-approaches'].map(n=>`export * from '${root}/src/lib/town/${n}';`).join('\n'));await build({entryPoints:[work+'/entry.ts'],outfile:work+'/api.mjs',bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'three',setup(b){b.onResolve({filter:/^three$/},()=>({path:fileURLToPath(import.meta.resolve('three')),external:true}));}}]});const api=await import(pathToFileURL(work+'/api.mjs'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1))}}));const asset=r=>r?read(root+'/public'+r.url):undefined;
const report=[];for(const tile of manifest.tiles.filter(t=>['2_-3','2_-4'].includes(t.id)))for(const lod of tile.lods){const bytes=fs.readFileSync(base+lod.url),group=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;api.applyMeasuredBridgeSurface(group,tile.id,tile.origin);api.applyTerrainFinish(group,tile.id,tile.origin,lod.level,asset(api.terrainFinishAsset(tile.id,lod.level)));api.applyEnvironmentGround(group,tile.id,tile.origin,lod.level,asset(api.environmentGroundAsset(tile.id,lod.level)));const source=[];group.traverse(o=>{if(o.isMesh)source.push({o,g:o.geometry,m:o.material,attributes:{...o.geometry.attributes},index:o.geometry.index});});
if(!api.applyDockApproaches(group,tile.id,tile.origin,lod.level,'0'.repeat(64)).rejected)throw Error('Wrong SHA accepted');const began=performance.now(),result=api.applyDockApproaches(group,tile.id,tile.origin,lod.level,lod.sha256);if(!result.applied)throw Error('Correct source rejected '+tile.id);const ms=performance.now()-began;if(api.applyDockApproaches(group,tile.id,tile.origin,lod.level,lod.sha256)!==result)throw Error('Not idempotent');
for(const r of source){if(r.o.geometry!==r.g||r.o.material!==r.m||r.g.index!==r.index||Object.entries(r.attributes).some(([k,a])=>r.g.getAttribute(k)!==a))throw Error('Source changed');}group.updateMatrixWorld(true);const emitted=[],q=new THREE.Vector3();let volume=0;group.getObjectByName('Mapped dock shore approaches').traverse(m=>{if(!m.isMesh)return;const p=m.geometry.getAttribute('position'),n=m.geometry.getAttribute('normal');for(let i=0;i<p.count;i+=3){const v=[0,1,2].map(k=>new THREE.Vector3().fromBufferAttribute(p,i+k)),cross=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0]));if(!v.every(v=>v.toArray().every(Number.isFinite))||cross.length()<1e-9||cross.clone().normalize().dot(new THREE.Vector3().fromBufferAttribute(n,i))<.45)throw Error('Bad emitted face');volume+=v[0].dot(v[1].clone().cross(v[2]))/6;emitted.push({material:m.material.name,triangle:v.map(v=>[v.x+tile.origin[0],-v.z-tile.origin[2],v.y+tile.origin[1]])});}});if(volume<0)throw Error('Inward body');fs.writeFileSync(`${work}/emitted-${tile.id}-${lod.level}.json.gz`,gzipSync(JSON.stringify(emitted)));report.push({tileId:tile.id,level:lod.level,ms,...result,sourceUnchanged:true,positiveVolumeM3:volume});
group.updateMatrixWorld(true);const terrain=[],guards=[],p=new THREE.Vector3();group.traverse(m=>{if(!m.isMesh||!/^terrain(?:\b|_)/.test(m.name))return;guards.push({name:m.name,geometryStamp:api.terrainGeometryStamp(m.geometry)});const g=m.geometry,position=g.getAttribute('position'),count=g.index?.count??position.count;for(let i=0;i<count;i+=3)terrain.push([0,1,2].map(k=>{p.fromBufferAttribute(position,g.index?.getX(i+k)??i+k).applyMatrix4(m.matrixWorld);return[p.x+tile.origin[0],-p.z-tile.origin[2],p.y+tile.origin[1]];}));});fs.writeFileSync(`${work}/${tile.id}-${lod.level}.json.gz`,gzipSync(JSON.stringify({tileId:tile.id,level:lod.level,origin:tile.origin,sourceSha256:lod.sha256,guards,terrain})));}

fs.writeFileSync(work+'/native-report.json',JSON.stringify({passed:true,rows:report},null,2));console.log(JSON.stringify(report,null,2));
