import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash}from'node:crypto';import{build}from'esbuild';import * as THREE from 'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..'),work=process.env.WEBSTER_COMMERCIAL_QA||'/private/tmp/webster-final-details/commercial';fs.mkdirSync(work,{recursive:true});
const sha=x=>createHash('sha256').update(x).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p));
await build({stdin:{contents:`export{applyCommercialCompletion,COMMERCIAL_COMPLETION}from'${root}/src/lib/town/commercial-completion';`,resolveDir:root},outfile:work+'/compiled.mjs',bundle:true,platform:'node',format:'esm',external:['three'],logLevel:'silent'});
const{applyCommercialCompletion,COMMERCIAL_COMPLETION:data}=await import(work+'/compiled.mjs'),release=json(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=json(base+'manifest.json');
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'QA_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const report={moduleSHA256:sha(fs.readFileSync(root+'/src/lib/town/commercial-completion.ts')),dataSHA256:sha(fs.readFileSync(root+'/data/derived/town/commercial-completion.json')),rows:[],passed:false},geometry=[];
const hash=g=>sha(Buffer.concat([...Object.values(g.attributes),...(g.index?[g.index]:[])].map(a=>Buffer.from(a.array.buffer,a.array.byteOffset,a.array.byteLength))));
for(const tile of manifest.tiles.filter(t=>data.rows.some(r=>r.tileId===t.id)))for(const lod of tile.lods){
 const raw=fs.readFileSync(base+lod.url);assert.equal(sha(raw),lod.sha256);const scene=(await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),'')).scene;
 const original=[];scene.traverse(o=>{if(o instanceof THREE.Mesh)original.push({mesh:o,geometry:o.geometry,material:o.material,hash:hash(o.geometry)});});
 const mismatch=applyCommercialCompletion(scene,tile.id,tile.origin,lod.level,'wrong');assert.equal(mismatch.status,'source-mismatch');assert.equal(scene.children.length,original[0]?.mesh.parent===scene?scene.children.length:scene.children.length);
 const start=performance.now(),result=applyCommercialCompletion(scene,tile.id,tile.origin,lod.level,lod.sha256),elapsedMs=performance.now()-start;assert.equal(result.status,'applied',tile.id);assert.deepEqual(result.buildingIds.sort(),data.rows.filter(r=>r.tileId===tile.id).map(r=>r.id).sort(),tile.id+' all native building matches');assert.equal(applyCommercialCompletion(scene,tile.id,tile.origin,lod.level,lod.sha256),result);
 let unchanged=0;for(const o of original){if(o.mesh.geometry===o.geometry&&o.mesh.material===o.material){assert.equal(hash(o.geometry),o.hash);unchanged++;}else assert.equal(tile.id,'-13_-4','Only Gilles/Tiffany body may change');}
 let triangles=0,bad=0,degenerate=0,minArea=Infinity,peak=-Infinity;const meshes=[];scene.getObjectByName('Commercial research completion').traverse(o=>{if(!(o instanceof THREE.Mesh))return;const p=o.geometry.getAttribute('position'),n=o.geometry.getAttribute('normal');for(let i=0;i<p.count;i+=3){const a=new THREE.Vector3().fromBufferAttribute(p,i),b=new THREE.Vector3().fromBufferAttribute(p,i+1),c=new THREE.Vector3().fromBufferAttribute(p,i+2),normal=new THREE.Vector3().fromBufferAttribute(n,i);assert.ok([...a,...b,...c,...normal].every(Number.isFinite));peak=Math.max(peak,a.y+tile.origin[1],b.y+tile.origin[1],c.y+tile.origin[1]);const cross=b.sub(a).cross(c.sub(a)),area=cross.length();minArea=Math.min(minArea,area);if(area<1e-9)degenerate++;else if(cross.dot(normal)<=0)bad++;triangles++;}meshes.push({name:o.name,sourceIds:o.userData.sourceIds??o.userData.structIds??[],position:Array.from(p.array)});});
 report.rows.push({tileId:tile.id,level:lod.level,origin:tile.origin,...result,sourceMeshesUnchanged:unchanged,sourceMeshes:original.length,bad,degenerate,minArea,peak,elapsedMs});geometry.push({tileId:tile.id,level:lod.level,origin:tile.origin,geometry:meshes});console.log(tile.id,lod.level,result.ids.join(','),triangles,'bad',bad,degenerate,'ms',elapsedMs.toFixed(1));
 const gs=new Set(),ms=new Set(),ts=new Set();scene.traverse(o=>{if(!(o instanceof THREE.Mesh))return;gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v instanceof THREE.Texture)ts.add(v);}});for(const g of gs)g.dispose();for(const m of ms)m.dispose();for(const t of ts)t.dispose();
}
report.passed=report.rows.every(r=>!r.bad&&!r.degenerate);fs.writeFileSync(work+'/native-audit.json',JSON.stringify(report,null,2));fs.writeFileSync(work+'/all-lod-overlay-geometry.json',JSON.stringify(geometry));assert.ok(report.passed);console.log('PASS',report.rows.length);
