"""Evidence-to-runtime dispositions; directory facts are not exterior photographs."""
import json, os, re, hashlib, collections, gzip
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RESEARCH=Path(os.environ.get('WEBSTER_RESEARCH','/Users/andy/Documents/New project/webster-blender/research'));QA=Path(os.environ.get('WEBSTER_COMMERCIAL_QA','/private/tmp/webster-final-details/commercial'))
read=lambda p:json.loads(Path(p).read_bytes());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
data=read(ROOT/'data/derived/town/commercial-completion.json');ledger=read(RESEARCH/'implementation/landmark-evidence.json');businesses=read(RESEARCH/'data/businesses.json')['records'];buildings={r['id']:r for r in read(RESEARCH/'data/building-register.json')};old=read(ROOT/'data/derived/town/landmark-evidence.json');new={r['id']:r for r in data['rows']};oldRows={r['id']:r for r in old['rows']};protected={r['structId']:r for r in old['retainedProtected']};applications=read(QA/'coverage-ledger.json')['applications'];currentIds={f['id']for r in data['rows']for f in r['frames']};dispositions={r['id']:r for r in applications}
otherDomain={'MS-X-000','MS-N-001','MS-S-013','IND-01','IND-04','IND-06','IND-09','IND-15','IND-16','IND-17','IND-18','IND-19','IND-20','IND-21','IND-22','IND-23','IND-24','IND-25','IND-26','IND-34','CC-THOMP-010','CC-THOMP-011','CC-THOMP-012','CC-THOMP-025','CC-GORE-010','CC-WORC-007'}
institutions={r['id']:r for r in read(ROOT/'data/derived/town/institutional-completion.json')['rows']}
recordRows=[]
def binding(sid):
 if sid in institutions:return {'structId':sid,'status':'institutional-completion','reason':'Dedicated institutional geometry and facade treatment in this same release; excluded from commercial duplication.'}
 if sid in new:return{'structId':sid,'status':'implemented-commercial','tileId':new[sid]['tileId'],'facades':len(new[sid]['frames']),'bodyRebuilt':bool(new[sid]['bodyParts'])}
 if sid in protected:return{'structId':sid,'status':'retained-named-landmark','reason':'Named/photo-derived landmark source geometry is deliberately protected from generic replacement.'}
 if sid in oldRows:return{'structId':sid,'status':'existing-landmark-evidence','applicationIds':oldRows[sid]['applicationIds']}
 b=buildings.get('BLD-'+sid,{});p=Path('/private/tmp/webster-realism-v2-building/townwide-assets')/(sid+'.report.json');report=read(p)if p.exists()else{}
 reason='Current source uses a residential or specialized non-shop plan; no independently established commercial entrance or wall segment supports replacing it with a retail skin.'
 specific={'168023_866559':'The research explicitly identifies this as the adjacent 1840 tenement at26Chase Avenue (current3.5-story apartments). It states no current outline for the distinct historic56Main block. No old storefront description is transferred to the tenement.','169680_867626':'The source record is explicitly the0EastMain commercial parking parcel. A residual roofprint is not qualified as a current shop; no tenant façade is invented over a parking-only use.','170015_865919':'The source is a converted residential form at169Thompson; the record groups several different162–170properties and a Dunkin at170. The dated storefront/drive-through statement cannot be transferred to this different apartment conversion.','170746_864545':'Current mapped1968garden-apartment complex; its separate cell tower belongs to environment detail. Retain residential window/roof treatment instead of commercial storefronts.'}
 if sid in specific:reason=specific[sid]
 if not report:reason='No available matching native V2 source asset; no inferred facade attached to an unrelated building.'
 elif report.get('mode')=='principal_residential':reason='Retain the residential architectural renderer and its roof/window proportions; assessor business use does not establish a commercial storefront.'
 elif not b.get('principalStructureInferred'):reason='Ancillary/shared-parcel structure: principal business appearance is not transferred blindly.'
 elif report.get('mode')=='accessory':reason='Accessory structure; no independent exterior description.'
 elif report.get('eave_z',0)-report.get('floor_z',0)<2.35:reason='No reliable wall height for a full facade skin; retain source geometry.'
 elif b.get('assessorStyle')in ['SERVICE STATION','UTILITY BLD']:reason='Fuel canopy/utility function requires a specific structure allocation; retained source cannot safely receive shop wall panels.'
 return{'structId':sid,'status':'retained-source-with-limit','parcelAddress':b.get('parcelAddress'),'assessorStyle':b.get('assessorStyle'),'sourceMode':report.get('mode'),'reason':reason}
for r in ledger['records']:
 if not r['evidenceId'].startswith(('MS-','IND-','CC-')):continue
 ids=list(r['buildingIds'])
 if not ids and r['facts']:
  m=re.match(r'(BLD-\d+_\d+)',r['facts'][0]['statement'])
  if m:ids=[m[1]]
 binds=[binding(bid.removeprefix('BLD-'))for bid in ids];aid=r['evidenceId']
 if aid in currentIds:status='implemented-specific-or-program-inferred'
 elif any(b['status']=='implemented-commercial'for b in binds):status='implemented-through-alias'
 elif aid in dispositions:status=dispositions[aid]['status']
 elif r['presentState']=='demolished_or_removed':status='inapplicable-demolished'
 elif aid in otherDomain:status='other-domain-coverage'
 elif any(b['status']in['retained-named-landmark','existing-landmark-evidence','institutional-completion']for b in binds):status='existing-landmark-renderer'
 elif binds:status='retained-source-with-documented-limit'
 else:status='unresolved-current-registration'
 recordRows.append({'id':aid,'title':r['title'],'status':status,'source':r['source'],'presentState':r['presentState'],'bindings':binds,'explicitLimits':dispositions.get(aid,{}).get('limits',[]),'reason':dispositions.get(aid,{}).get('reason'),'factsReviewed':len(r['facts']),'businessIds':sorted(set(re.findall(r'BIZ-\d+',' '.join(f['statement']for f in r['facts'])))),'appearanceCaution':'Dated source statements and current assessor program are distinct. Window counts, entrances, unobserved paints and small trim are authored game choices; no new claim of current tenant signs.'})
master=[]
for app in ledger['reviewedApplications']:
 aid=app['id'];bids=app['targetBuildingIds'];binds=[binding(bid[4:])for bid in bids]
 status=dispositions.get(aid,{}).get('status')or('retained-named-landmark'if any(b['status']=='retained-named-landmark'for b in binds)else'existing-landmark-evidence'if any(b['status']=='existing-landmark-evidence'for b in binds)else'other-domain-or-unresolved')
 master.append({'id':aid,'name':app['name'],'status':status,'bindings':binds,'reviewedTraits':app['renderHints'],'sourceEvidenceIds':app['sourceEvidenceIds'],'caution':app['caution']})
bizRows=[]
for b in businesses:
 links=[r for r in recordRows if b['id']in r['businessIds']];bindings=[x for r in links for x in r['bindings']];applied=sorted({x['structId']for x in bindings if x['status']=='implemented-commercial'});hasWritten=bool(b['appearance_observations'])
 bizRows.append({'id':b['id'],'name':b['name'],'address':b['street_address'],'status':'program-interpreted-on-joined-building'if applied else'context-only-no-exterior-reproduction','recordIds':[r['id']for r in links],'renderedBuildingIds':applied,'appearanceObservations':b['appearance_observations'],'appearanceEvidence':b['appearance_evidence'],'citations':b['citations'],'limits':b['gaps'],'interpretation':'Written service/access notes preserved as evidence. Unlocated drive-up lane geometry, exact entrance position and changing tenant signs are not treated as observed exterior shapes.'if hasWritten else'Directory name/address supplies context but no inspected exterior; no unsupported current sign reproduction.'})
summary={'commercialRecords':len(recordRows),'reviewedMasterApplications':len(master),'businessRecords':len(bizRows),'businessRecordsWithWrittenAppearanceOrAccess':sum(bool(b['appearance_observations'])for b in businesses),'runtimeBuildings':len(data['rows']),'runtimeFacades':sum(len(r['frames'])for r in data['rows']),'runtimeTiles':len(set(r['tileId']for r in data['rows'])),'recordStatusCounts':dict(collections.Counter(r['status']for r in recordRows)),'businessStatusCounts':dict(collections.Counter(r['status']for r in bizRows))}
report={'summary':summary,'sourceLedgerSHA256':sha(RESEARCH/'implementation/landmark-evidence.json'),'businessSourceSHA256':sha(RESEARCH/'data/businesses.json'),'runtimeDataSHA256':sha(ROOT/'data/derived/town/commercial-completion.json'),'commercialRecords':recordRows,'masterApplications':master,'businessRecords':bizRows}
(QA/'complete-corpus-coverage.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Commercial research implementation coverage','',f"Reviewed all {len(recordRows)} Main Street / mill / commercial records, all {len(master)} master landmark applications, and all {len(bizRows)} business entries.",'',f"The commercial renderer adds {len(data['rows'])} exact-source buildings / {summary['runtimeFacades']} facade segments in {summary['runtimeTiles']} streamed scenery tiles. Twenty-four original targeted applications and the dated lake-plaza photograph provide specific architectural choices. Other premises receive clearly labeled program-based entry/window inference within their retained source envelope.",'','The machine-readable `complete-corpus-coverage.json` records every disposition, citation, stable BLD join, source limitation and business reference. Context-only directory entries are not claimed as exact exterior reproductions. Current-source gaps remain explicit.','', '## Specific corrections','', '- Gilles/Tiffany: three classified 2021 LiDAR roof levels, exact shared source plan, separate two/three-storey red/buff facades. The lower rear Gilles wing remains low.','- 242/248/260 Main: parcel-allocated classical brick / pale Moderne with dark stone base / gray-brick facades. No whole shared-footprint recolor.','- Patenaude: exact 293 Main parcel + MHC reference; conflicting dated yellow brick and vinyl reports remain uncertainty, not an invented current yellow face.','- Mills: long industrial opening rhythms, segmental-arched weave-mill openings and documented brick; warehouse/repair doors fitted to real source walls.','- 170 Gore: viewed cited 2017 exterior supports a teal sloped fascia, brick piers, storefront glass and original raised yellow lake-name lettering. No current tenant logo claims.','- Four close street-side facade portions omit new detail where the padded guided-car clearance envelope reaches retained source walls. The source body and all road geometry are preserved.','', '## Records','', '| ID | Status | Native buildings |','|---|---|---|']
for r in recordRows:lines.append('| '+r['id']+' | '+r['status']+' | '+', '.join(b['structId']for b in r['bindings'])+' |')
lines+=['','## Limits','', 'Cook Block: current exact parcel is commercial open parking; no historical reconstruction. Columbia and Hall: current source registration unresolved. Named landmarks, civic campuses, utility facilities, bridges and residential roof forms retain their specialized renderers; this commercial module does not duplicate or overwrite them.','', 'Business-only written claims of drive-up services, curbside collection, an interior open kitchen or a rear parking lot do not establish exact exterior geometry. Their full statements and citations remain in the coverage JSON. Existing roads/parking and sensible facade interpretations provide game context without assigning unverified tenant signage.']
(QA/'COVERAGE.md').write_text('\n'.join(lines)+'\n');print(json.dumps(summary,indent=2))
