/** Real source GLBs, exact source preservation, and emitted paint for GEOS QA. */
import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{fileURLToPath,pathToFileURL}from'node:url';import{gzipSync}from'node:zlib';import{build}from'esbuild';
import*as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.RAMP_APRON_WORK??'/private/tmp/webster-finished-game/ramp-apron',read=p=>JSON.parse(fs.readFileSync(p)),release=read(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=read(base+'manifest.json'),index=read(root+'/data/derived/town/ramp-apron.json'),roadIndex=read(root+'/data/derived/town/road-finish-index.json');
const imports=['road-finish','road-material-finish','terrain-finish','environment-ground','bridge-surface','ramp-apron-finish'];fs.writeFileSync(work+'/audit-entry.ts',imports.map(n=>`export * from '${root}/src/lib/town/${n}';`).join('\n'));
await build({entryPoints:[work+'/audit-entry.ts'],outfile:work+'/audit-api.mjs',bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'shared-three',setup(b){b.onResolve({filter:/^three$/},()=>({path:fileURLToPath(import.meta.resolve('three')),external:true}))}}]});const api=await import(pathToFileURL(work+'/audit-api.mjs'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1))}}));const asset=r=>r?read(root+'/public'+r.url):undefined,report=[];
for(const tile of manifest.tiles.filter(t=>t.id===index.tileId))for(const lod of tile.lods){
 const bytes=fs.readFileSync(base+lod.url),scene=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),pathToFileURL(path.dirname(base+lod.url)+'/').href)).scene;
 api.applyMeasuredBridgeSurface(scene,tile.id,tile.origin);api.applyTerrainFinish(scene,tile.id,tile.origin,lod.level,asset(api.terrainFinishAsset(tile.id,lod.level)));api.applyEnvironmentGround(scene,tile.id,tile.origin,lod.level,asset(api.environmentGroundAsset(tile.id,lod.level)));api.applyRoadFinish(scene,tile.id,tile.origin,lod.level,asset(roadIndex.tiles[tile.id])?.rows??[]);api.applyRoadMaterialFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,asset(api.roadMaterialAsset(tile.id,lod.level)));
 const before=[];scene.traverse(mesh=>{if(mesh.isMesh)before.push({mesh,g:mesh.geometry,material:mesh.material,attributes:{...mesh.geometry.attributes},index:mesh.geometry.index});});
 assert.ok(api.applyRampApronFinish(scene,tile.id,tile.origin,lod.level,'0'.repeat(64)).rejected);assert.ok(before.every(r=>r.mesh.geometry===r.g&&r.mesh.material===r.material));
 const began=performance.now(),result=api.applyRampApronFinish(scene,tile.id,tile.origin,lod.level,lod.sha256);assert.ok(result.applied);const ms=performance.now()-began,children=scene.children.length;assert.equal(api.applyRampApronFinish(scene,tile.id,tile.origin,lod.level,lod.sha256),result);assert.equal(scene.children.length,children);
 for(const r of before){assert.equal(r.mesh.geometry,r.g);assert.equal(r.mesh.material,r.material);assert.equal(r.g.index,r.index);for(const[name,a]of Object.entries(r.attributes))assert.equal(r.g.getAttribute(name),a);}
 const mesh=scene.getObjectByName('finished_ramp_2431_135_apron'),p=mesh.geometry.getAttribute('position'),normal=mesh.geometry.getAttribute('normal'),added=[];assert.ok(before.some(r=>(Array.isArray(r.material)?r.material:[r.material]).includes(mesh.material)));
 for(let i=0;i<p.count;i+=3){const v=[0,1,2].map(k=>new THREE.Vector3().fromBufferAttribute(p,i+k)),cross=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0]));assert.ok(cross.y>1e-9);for(let k=0;k<3;k++)assert.ok(cross.clone().normalize().dot(new THREE.Vector3().fromBufferAttribute(normal,i+k))>.99999);added.push(v.map(a=>[a.x+tile.origin[0],-a.z-tile.origin[2],a.y+tile.origin[1]]));}
 fs.writeFileSync(`${work}/output-${lod.level}.json`,JSON.stringify({tileId:tile.id,level:lod.level,added}));report.push({tileId:tile.id,level:lod.level,ms,sourceMeshes:before.length,sourcePreserved:true,materialReused:true,...result});
 const geometries=new Set(),materials=new Set();scene.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();});
}
fs.writeFileSync(work+'/native-report.json',JSON.stringify({passed:true,rows:report},null,2));console.log(JSON.stringify(report,null,2));
