/** A bounded infill at the source ramp 2431 → 135; road paths remain unchanged. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {build} from 'esbuild';
import * as THREE from 'three';import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.RAMP_APRON_WORK??'/private/tmp/webster-finished-game/ramp-apron';fs.mkdirSync(work,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p)),release=read(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=read(base+'manifest.json'),tile=manifest.tiles.find(t=>t.id==='-5_1');
// Union of the 5.2 × 2.4 m guided-car sweep, plus 6 cm, clipped to the empty
// source wedge. These are authored repair limits, not new survey observations.
const outline=[[-1162.257694970854,273.7012477215038],[-1162.2360991630899,273.6967132467308],[-1162.2176031373288,273.684678405415],[-1162.20470868849,273.6667710448167],[-1160.7409002231689,271.56181789635787],[-1160.7357883064217,271.5472960888224],[-1161.3117613443767,271.3924121213311],[-1161.6632152772254,271.3705849389272],[-1161.8777313232422,272.1881103515625],[-1162.274050039467,273.698559323672]];
fs.writeFileSync(work+'/entry.ts',`export {terrainGeometryStamp} from '${root}/src/lib/town/terrain-finish';`);await build({entryPoints:[work+'/entry.ts'],outfile:work+'/api.mjs',bundle:true,platform:'node',format:'esm',logLevel:'silent'});const{terrainGeometryStamp}=await import(pathToFileURL(work+'/api.mjs'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1))}}));
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const weights=(p,t)=>{const d=cross(...t);return [cross(t[1],t[2],p)/d,cross(t[2],t[0],p)/d,cross(t[0],t[1],p)/d];};
const rows=[],proof=[];
for(const lod of tile.lods){const bytes=fs.readFileSync(base+lod.url);assert.equal(createHash('sha256').update(bytes).digest('hex'),lod.sha256);const scene=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'')).scene;scene.updateMatrixWorld(true);const faces=[],guards=[],v=new THREE.Vector3();
 scene.traverse(m=>{if(!m.isMesh||m.parent?.name!=='roads')return;const g=m.geometry,p=g.getAttribute('position'),uv=g.getAttribute('uv'),materials=Array.isArray(m.material)?m.material:[m.material],count=g.index?.count??p.count;let used=false;for(const group of g.groups.length?g.groups:[{start:0,count,materialIndex:0}]){if(materials[group.materialIndex??0].name!=='Drive road | asphalt')continue;for(let i=group.start;i<Math.min(count,group.start+group.count);i+=3){const ids=[0,1,2].map(k=>g.index?.getX(i+k)??i+k),t=ids.map(k=>{v.fromBufferAttribute(p,k).applyMatrix4(m.matrixWorld);return[v.x+tile.origin[0],-v.z-tile.origin[2],v.y+tile.origin[1]]});if(Math.min(...t.map(v=>v[0]))>-1160||Math.max(...t.map(v=>v[0]))<-1163||Math.min(...t.map(v=>v[1]))>274||Math.max(...t.map(v=>v[1]))<271||Math.abs(cross(...t))<1e-9)continue;faces.push({t,uv:uv?ids.map(k=>[uv.getX(k),uv.getY(k)]):null});used=true;}}if(used)guards.push({name:m.name,parent:'roads',geometryStamp:terrainGeometryStamp(g)});});
 const vertices=outline.map(p=>[...p,NaN]),supports=[];for(let k=5;k<10;k++){const candidates=faces.map(f=>({...f,w:weights(outline[k],f.t)})).filter(f=>Math.min(...f.w)>-1e-5);assert.ok(candidates.length);const chosen=candidates.sort((a,b)=>b.w.reduce((n,w,i)=>n+w*b.t[i][2],0)-a.w.reduce((n,w,i)=>n+w*a.t[i][2],0))[0];vertices[k][2]=chosen.w.reduce((n,w,i)=>n+w*chosen.t[i][2],0);supports.push({vertex:k,height:vertices[k][2]});}
 const run=[9,0,1,2,3,4,5],station=[0];for(let i=1;i<run.length;i++)station.push(station.at(-1)+Math.hypot(...outline[run[i]].map((v,k)=>v-outline[run[i-1]][k])));for(let i=1;i<run.length-1;i++)vertices[run[i]][2]=vertices[9][2]+(vertices[5][2]-vertices[9][2])*station[i]/station.at(-1);
 const triangles=THREE.ShapeUtils.triangulateShape(outline.map(p=>new THREE.Vector2(...p)),[]),positions=triangles.flatMap(t=>t.map(i=>vertices[i]));assert.equal(triangles.length,outline.length-2);
 const template=faces.find(f=>f.uv),uv=template?positions.map(p=>{const w=weights(p,template.t);return[0,1].map(k=>w.reduce((n,v,i)=>n+v*template.uv[i][k],0));}):null;
 rows.push({level:lod.level,sourceSha256:lod.sha256,guards,positions,uv});proof.push({level:lod.level,sourceSha256:lod.sha256,supports,triangles:triangles.length});
 const geometries=new Set(),materials=new Set();scene.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{for(const t of Object.values(m))if(t?.isTexture)t.dispose();m.dispose();});
}
const catalog={version:1,tileId:tile.id,origin:tile.origin,sourceManifestSha256:release.manifestSha256,fromEdge:2431,toEdge:135,outline,material:'Drive road | asphalt',evidence:'1.2105 m² inferred paved infill in an existing ramp/road ribbon gap. Five actual source-pavement boundary heights retained; other boundary heights interpolated. Guided network, source terrain and source pavement unchanged.',levels:rows};fs.writeFileSync(root+'/data/derived/town/ramp-apron.json',JSON.stringify(catalog)+'\n');fs.writeFileSync(work+'/preparation-report.json',JSON.stringify({proof,outline,areaM2:Math.abs(outline.reduce((n,p,i)=>n+p[0]*outline[(i+1)%outline.length][1]-p[1]*outline[(i+1)%outline.length][0],0))/2},null,2));console.log(JSON.stringify(proof,null,2));
