import fs from 'node:fs';import path from 'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{build}from'esbuild';import * as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..'),work=process.env.WEBSTER_LANDMARK_QA||'/private/tmp/webster-research-completion/landmarks';fs.mkdirSync(work,{recursive:true});if(!fs.existsSync(path.join(work,'node_modules')))fs.symlinkSync(path.join(repo,'node_modules'),path.join(work,'node_modules'));
const compiled=path.join(work,'landmark-compiled.mjs');await build({entryPoints:[path.join(here,'entry.ts')],outfile:compiled,bundle:true,platform:'node',format:'esm',external:['three'],logLevel:'silent'});const{applyLandmarkCompletion,planDistanceSquared}=await import(pathToFileURL(compiled).href);
const read=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex');const data=read(path.join(repo,'data/derived/town/landmark-completion.json')),rel=read(path.join(repo,'data/derived/town/release.json')),base=path.join(repo,'public/town-assets',rel.directory),manifest=read(path.join(base,'manifest.json'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'REFERENCE_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const report={version:1,sourceManifestSha256:sha(fs.readFileSync(path.join(base,'manifest.json'))),runtimeSha256:sha(fs.readFileSync(path.join(repo,'src/lib/town/landmark-completion.ts'))),dataSha256:sha(fs.readFileSync(path.join(repo,'data/derived/town/landmark-completion.json'))),scope:'Actual GLTFLoader at all 3 LODs, before evidence recoloring. Every source triangle outside the four selected V2 inferred envelopes retains exact attributes and persistent source material identity. Reconciliation tower has an explicit historical 52 ft height exception. Texture pixels stubbed.',results:[],failures:[]};
function eachTri(scene,origin,fn){scene.updateMatrixWorld(true);scene.traverse(o=>{if(!(o instanceof THREE.Mesh)||o.userData.townCrafted)return;const g=o.geometry,p=g.getAttribute('position'),ix=g.index,mats=Array.isArray(o.material)?o.material:[o.material],count=ix?.count??p.count;for(const part of g.groups.length?g.groups:[{start:0,count,materialIndex:0}])for(let i=part.start;i<part.start+part.count;i+=3){const ids=[0,1,2].map(k=>ix?ix.getX(i+k):i+k),world=ids.map(k=>new THREE.Vector3().fromBufferAttribute(p,k).applyMatrix4(o.matrixWorld).add(new THREE.Vector3(...origin))),centroid=world.reduce((a,b)=>a.add(b),new THREE.Vector3()).multiplyScalar(1/3);const mat=mats[part.materialIndex??0];const values=ids.map(k=>Object.entries(g.attributes).sort(([a],[b])=>a.localeCompare(b)).flatMap(([name,a])=>[name,...Array.from({length:a.itemSize},(_,j)=>a.getComponent(k,j))]));const key=sha(Buffer.from(JSON.stringify([mat.uuid,o.matrixWorld.toArray(),values])));fn({key,mat,centroid,o});}});}
for(const row of data.rows){const tile=manifest.tiles.find(t=>t.id===row.tileId);for(const lod of tile.lods){const raw=fs.readFileSync(path.join(base,lod.url));if(sha(raw)!==lod.sha256)throw Error('Source SHA mismatch');const scene=(await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),'')).scene;const protectedSet=new Map(),expectedRemove=new Map();
 const isSelected=t=>t.mat.name.startsWith('V2 inferred | ')&&t.centroid.y>=row.base-1&&t.centroid.y<=row.sourcePeak+12&&planDistanceSquared(row.outline,t.centroid.x,-t.centroid.z)<.85*.85;
 eachTri(scene,tile.origin,t=>{const target=isSelected(t)?expectedRemove:protectedSet;target.set(t.key,(target.get(t.key)??0)+1);});
 const result=applyLandmarkCompletion(scene,tile.id,tile.origin,lod.level,lod.sha256),failures=[];if(result?.ids.join()!==row.id)failures.push('Source matching failed');let remainingSelected=0,unknown=0;eachTri(scene,tile.origin,t=>{if(isSelected(t))remainingSelected++;const n=protectedSet.get(t.key);if(n)protectedSet.set(t.key,n-1);else unknown++;});const missing=[...protectedSet.values()].reduce((a,b)=>a+b,0);if(missing||unknown||remainingSelected)failures.push(`Source preservation missing=${missing} new=${unknown} oldSelected=${remainingSelected}`);
 let triangles=0,minZ=Infinity,maxZ=-Infinity,maxDistance=0,maxNormalError=0,minWinding=1,degenerate=0,inwardRoofSlopeVertices=0,fireDoorVertices=0,interiorFireDoorVertices=0,wrongFireDoorNormals=0,worst=null;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),normal=new THREE.Vector3();scene.traverse(o=>{if(!(o instanceof THREE.Mesh)||!o.userData.townCrafted)return;const p=o.geometry.getAttribute('position'),n=o.geometry.getAttribute('normal');triangles+=p.count/3;for(let i=0;i<p.count;i++){const point=[p.getX(i)+tile.origin[0],-p.getZ(i)-tile.origin[2],p.getY(i)+tile.origin[1]];if(!point.every(Number.isFinite))failures.push('Nonfinite');if(row.recipe==='fire'&&o.name.endsWith('door | #b1b3a4')){fireDoorVertices++;if(planDistanceSquared(row.outline,point[0],point[1])<.01)interiorFireDoorVertices++;if(n.getX(i)*row.frame.outward[0]-n.getZ(i)*row.frame.outward[1]<.999)wrongFireDoorNormals++;}minZ=Math.min(minZ,point[2]);maxZ=Math.max(maxZ,point[2]);maxDistance=Math.max(maxDistance,Math.sqrt(planDistanceSquared(row.outline,point[0],point[1])));maxNormalError=Math.max(maxNormalError,Math.abs(Math.hypot(n.getX(i),n.getY(i),n.getZ(i))-1));if(o.name.includes(' | roof | ')&&n.getY(i)<-.001&&n.getY(i)>-.999)inwardRoofSlopeVertices++;}for(let i=0;i<p.count;i+=3){a.fromBufferAttribute(p,i);b.fromBufferAttribute(p,i+1).sub(a);c.fromBufferAttribute(p,i+2).sub(a);normal.crossVectors(b,c);if(normal.length()<1e-8){degenerate++;continue;}normal.normalize();const dot=normal.dot(a.fromBufferAttribute(n,i));if(dot<minWinding){minWinding=dot;worst={mesh:o.name,index:i,positions:[0,1,2].map(k=>[p.getX(i+k),p.getY(i+k),p.getZ(i+k)]),normal:[n.getX(i),n.getY(i),n.getZ(i)]};}}});
 if(row.recipe==='fire'&&(fireDoorVertices!==60||interiorFireDoorVertices||wrongFireDoorNormals))failures.push('Apparatus door exterior placement/normals failed');if(inwardRoofSlopeVertices)failures.push('Inward/downward sloped roof faces');if(maxNormalError>1e-5)failures.push('Nonunit normals');if(minWinding<.994)failures.push('Winding mismatch');if(degenerate)failures.push('Degenerate faces');if(maxDistance>.8)failures.push('Outside source envelope '+maxDistance);if(minZ<row.base-.01||maxZ>row.peak+.15)failures.push('Height exceeds documented envelope');if(result?.removedTriangles!==[...expectedRemove.values()].reduce((a,b)=>a+b,0))failures.push('Removal count mismatch');if(applyLandmarkCompletion(scene,tile.id,tile.origin,lod.level,lod.sha256)!==result)failures.push('Not idempotent');
 const out={id:row.id,name:row.name,tileId:tile.id,level:lod.level,...result,minZ,maxZ,maxOutsetM:maxDistance,maxNormalError,minWinding,degenerate,inwardRoofSlopeVertices,fireDoorVertices,interiorFireDoorVertices,wrongFireDoorNormals,worst,protectedSourceTriangles:[...protectedSet.keys()].length,heightException:row.heightException,failures};report.results.push(out);if(failures.length)report.failures.push(out);console.log(JSON.stringify(out));
 const gs=new Set(),ms=new Set(),ts=new Set();scene.traverse(o=>{if(o instanceof THREE.Mesh){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v instanceof THREE.Texture)ts.add(v);}}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());
}}
report.status=report.failures.length?'FAIL':'PASS';fs.writeFileSync(path.join(work,'landmark-native-audit.json'),JSON.stringify(report,null,2));console.log('FINAL',report.status);if(report.failures.length)process.exitCode=1;
