/** Read-only native source application audit; actual GLTFLoader geometry, texture-only stubs. */
import fs from'node:fs';import path from'node:path';import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{build}from'esbuild';import*as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const site=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.WEBSTER_ENVIRONMENT_WORK??'/private/tmp/webster-research-completion/environment';fs.mkdirSync(work,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex'),release=read(site+'/data/derived/town/release.json'),base=site+'/public/town-assets/'+release.directory+'/',rawManifest=fs.readFileSync(base+'manifest.json'),manifest=JSON.parse(rawManifest),index=read(site+'/data/derived/town/additional-environment-index.json'),terrainIndex=read(site+'/data/derived/town/terrain-finish-index.json');
if(hash(rawManifest)!==release.manifestSha256||index.sourceManifestSha256!==release.manifestSha256)throw new Error('Source manifest pin');
const entry=work+'/native-entry.ts',bundle=work+'/native-bundle.mjs';fs.writeFileSync(entry,`export{applyAdditionalEnvironment}from${JSON.stringify(site+'/src/lib/town/additional-environment')};export{applyTerrainFinish}from${JSON.stringify(site+'/src/lib/town/terrain-finish')};export{applyMeasuredBridgeSurface}from${JSON.stringify(site+'/src/lib/town/bridge-surface')};export{GrassTerrain}from${JSON.stringify(site+'/src/lib/town/grass')};`);
await build({entryPoints:[entry],outfile:bundle,bundle:true,format:'esm',platform:'node',plugins:[{name:'shared-three',setup(b){b.onResolve({filter:/^three$/},()=>({path:fileURLToPath(import.meta.resolve('three')),external:true}));}}],logLevel:'silent'});
const{applyAdditionalEnvironment,applyTerrainFinish,applyMeasuredBridgeSurface,GrassTerrain}=await import(pathToFileURL(bundle).href+'?'+Date.now()),loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'ENVIRONMENT_AUDIT_TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1));}}));
const bytes=a=>Buffer.from(a.array.buffer,a.array.byteOffset,a.array.byteLength),report={version:1,created:new Date().toISOString(),sourceManifestSha256:release.manifestSha256,indexSha256:hash(fs.readFileSync(site+'/data/derived/town/additional-environment-index.json')),basis:'Native actual source geometry with only texture pixels stubbed, existing measured bridge and terrain repair applied first. Runtime added objects only; no source mutations.',rows:[],failures:[]};
for(const[tileId,ref]of Object.entries(index.tiles)){const encoded=fs.readFileSync(site+'/public'+ref.url);if(hash(encoded)!==ref.sha256||encoded.length!==ref.bytes)throw new Error('Packet hash');const packet=JSON.parse(encoded),tile=manifest.tiles.find(t=>t.id===tileId);
 for(const asset of tile.lods){const raw=fs.readFileSync(base+asset.url);if(hash(raw)!==asset.sha256)throw new Error('Source GLB hash');const gltf=await loader.parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength),pathToFileURL(path.dirname(base+asset.url)+'/').href),scene=gltf.scene;
  applyMeasuredBridgeSurface(scene,tileId,tile.origin);const terrain=terrainIndex.tiles[tileId]?.levels[String(asset.level)];if(terrain)applyTerrainFinish(scene,tileId,tile.origin,asset.level,read(site+'/public'+terrain.url));
  const source=[];scene.traverse(o=>{if(o instanceof THREE.Mesh)source.push({object:o,geometry:o.geometry,material:o.material,attributes:Object.fromEntries(Object.entries(o.geometry.attributes).map(([name,a])=>[name,hash(bytes(a))])),index:o.geometry.index?hash(bytes(o.geometry.index)):null});});
  const start=performance.now(),result=applyAdditionalEnvironment(scene,tileId,tile.origin,asset.level,packet),elapsed=performance.now()-start,bad=[];
  for(const before of source){const o=before.object;if(o.geometry!==before.geometry||o.material!==before.material)bad.push('Protected source reference changed');for(const[name,sha]of Object.entries(before.attributes))if(hash(bytes(o.geometry.getAttribute(name)))!==sha)bad.push('Protected source attribute changed');if(before.index&&hash(bytes(o.geometry.index))!==before.index)bad.push('Protected source index changed');}
  let faces=0,zero=0,backward=0,nonfinite=0,normalError=0;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),n=new THREE.Vector3();
  scene.getObjectByName('Additional researched environment')?.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const g=o.geometry,p=g.getAttribute('position'),normal=g.getAttribute('normal');for(const attribute of Object.values(g.attributes))for(const value of attribute.array)if(!Number.isFinite(value))nonfinite++;
   for(let i=0;i<normal.count;i++)normalError=Math.max(normalError,Math.abs(Math.hypot(normal.getX(i),normal.getY(i),normal.getZ(i))-1));
   for(let i=0;i<p.count;i+=3){faces++;a.fromBufferAttribute(p,i);b.fromBufferAttribute(p,i+1);c.fromBufferAttribute(p,i+2);const cross=b.sub(a).cross(c.sub(a));if(cross.length()<1e-9){zero++;continue;}n.fromBufferAttribute(normal,i);if(cross.dot(n)<-1e-9)backward++;}
  });
  if(zero||backward||nonfinite||normalError>1e-4||result.rejected)bad.push('Invalid new geometry');if(applyAdditionalEnvironment(scene,tileId,tile.origin,asset.level,packet)!==result)bad.push('Non-idempotent overlay');
  const launchClearance=[];
  if(packet.objects.some(r=>r.kind==='boat-ramp')){
   scene.updateMatrixWorld(true);
   const matches=(o,name)=>{for(let p=o;p&&p!==scene;p=p.parent)if(p.name===name||p.name.startsWith(name+'_'))return true;return false;};
   const ground=new GrassTerrain(source.filter(r=>matches(r.object,'terrain')).map(r=>r.object)),newMeshes=[];
   scene.getObjectByName('Additional researched environment')?.traverse(o=>{if(o instanceof THREE.Mesh)newMeshes.push(o);});const top=new GrassTerrain(newMeshes);
   for(const r of packet.objects.filter(r=>r.kind==='boat-ramp')){
    const angle=r.angle??0,tx=Math.cos(angle),tn=Math.sin(angle),range=r.rampRange??[-6,7],middles=r.lanes===1?[0]:[-1.65,1.65];let samples=0,missing=0,min=Infinity,max=-Infinity,protrusions=0;
    for(const middle of middles)for(let u=range[0]+.023;u<range[1];u+=.071)for(let v=middle-1.55+.017;v<middle+1.55;v+=.073){
     const x=r.point[0]+tx*u+tn*v-tile.origin[0],z=-r.point[1]-tn*u+tx*v-tile.origin[2],a=ground.sample(x,z),b=top.sample(x,z);samples++;if(!a||!b){missing++;continue;}const delta=b.y-a.y;min=Math.min(min,delta);max=Math.max(max,delta);if(delta<.009)protrusions++;
    }
    launchClearance.push({id:r.id,samples,missing,protrusions,minimumM:min,maximumM:max});if(missing||protrusions)bad.push('Launch terrain/top clearance failure');
   }
  }
  const row={tileId,level:asset.level,applyMs:Math.round(elapsed*100)/100,faces,zero,backward,nonfinite,normalError,launchClearance,...result,failures:bad};report.rows.push(row);if(bad.length)report.failures.push({tileId,level:asset.level,failures:bad});
  const geometries=new Set(),materials=new Set(),textures=new Set();scene.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const x of Object.values(m))if(x instanceof THREE.Texture)textures.add(x);}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());
 }
}
report.summary={tiles:Object.keys(index.tiles).length,levels:report.rows.length,failedLevels:report.failures.length,zeroFaces:report.rows.reduce((s,r)=>s+r.zero,0),backwardFaces:report.rows.reduce((s,r)=>s+r.backward,0),nonfinite:report.rows.reduce((s,r)=>s+r.nonfinite,0),maxTileTriangles:Math.max(...report.rows.map(r=>r.addedTriangles)),maxTileBytes:Math.max(...report.rows.map(r=>r.geometryBytes)),maxApplyMs:Math.max(...report.rows.map(r=>r.applyMs)),lods:[0,1,2].map(level=>{const rows=report.rows.filter(r=>r.level===level);return{level,objects:rows.reduce((s,r)=>s+r.ids.length,0),triangles:rows.reduce((s,r)=>s+r.addedTriangles,0),bytes:rows.reduce((s,r)=>s+r.geometryBytes,0),skipped:rows.flatMap(r=>r.skipped)}})};
fs.writeFileSync(work+'/native-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report.summary,lods:report.summary.lods.map(({skipped,...rest})=>({...rest,skipped:skipped.length}))}));if(report.failures.length)process.exitCode=1;
