"""Exhaustive line-level coverage ledger for the five assigned research chapters.

Every substantive source line is retained with its source section, line, URLs,
evidence/date labels, and an explicit render disposition. Partial coverage is
never described as an exact current survey or complete feature reconstruction.
"""
import hashlib,json,re,os
from pathlib import Path
SITE=Path(__file__).resolve().parents[2];RESEARCH=Path(os.environ.get('WEBSTER_RESEARCH','/Users/andy/Documents/New project/webster-blender/research'));WORK=Path(os.environ.get('WEBSTER_ENVIRONMENT_WORK','/private/tmp/webster-research-completion/environment'))
FILES=['terrain-ground-vegetation','light-season-weather','lake-and-shoreline-detail','infrastructure-landscape','institutions-utilities-sites']
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def classify(stem,heading,text):
 h=heading.lower();s=text.lower()
 if 'bridge'in h or re.search(r'\bINF-BR-',heading):return'inapplicable','Owned by bridge agent; cross-reference retained in the overall research ledger, no duplicate nonbridge object.'
 if any(x in h for x in ['sources','open questions','not reachable','coverage and evidence','conventions','method and reproducibility']):return'inapplicable','Research provenance/method/open question; retained as evidence, not a standalone visible object.'
 if any(x in s for x in ['not established','unverified','unresolved','unreachable','requiring verification','no exact','no mapped webster occurrence','no contemporary botanical']):return'uncertain','The source itself limits identity, present condition or placement. No exact appearance is promoted from this line.'
 if any(x in h for x in ['sun geometry','lgt-0','lgt-10','lgt-11','lgt-12','lgt-13','lgt-14','lgt-15','lgt-16','lgt-17','lgt-21','lgt-27','lgt-28','lgt-29','lgt-30','lgt-31']):return'inapplicable','Static green late-summer game uses authored lighting; calculation tables, weather histories and alternative night/drought modes are retained for reference, not implemented as simulation systems.'
 if any(x in s for x in ['pea soup','rouge','1974 report','drawdown ring','farmed bog','hay bales','golf course','frost','no farm fields','no autumn colour','no autumn color']):return'inapplicable','Historical/alternative/negative constraint. Default mode does not add obsolete pollution, drawdown, winter/autumn or unsupported agricultural scenery.'
 if 'invasive' in s and any(x in s for x in ['herbicide','fluridone','diquat','flumioxazin','hydro-raking','raking']):return'inapplicable','Management history is not a visual abundance measurement. No chemical treatment, current bloom or dense weed extent is inferred solely from it.'
 if any(x in h for x in ['ter-019','site-063','inf-rec-lakeside-cemetery','inf-rec-mount-zion']):
  if any(x in s for x in ['wall','fence','gate','crucifix','shrine','inscription','4,204','228 memorial']):return'uncertain','Mapped cemetery fields now have anonymous authored stones, but no exact wall/gate/shrine, individual grave layout or inventory count is fabricated.'
  return'implemented','Partial: five source-mapped cemetery grounds contain anonymous stone fields, clear of mapped roads, buildings, water, paved mask cells and source tree anchors. Shapes/count/spacing are explicit inference; retained source terrain, tree canopy and buildings remain intact.'
 if any(x in h for x in ['eco-plant-018','eco-plant-019','eco-plant-022','ter-014','eco-hab-04']):return'implemented','Partial: sparse broad fern, rounded wet shrub and notched floating-pad forms are gated to mapped wet habitat and actual sheltered source water. Species allocation, individual positions and abundance remain inferred.'
 if 'ernie benoit rain garden' in s:return'supported-remaining','The 2024 rain garden is documented, but its exact bed footprint and planting arrangement have not been resolved or rendered. This is a known supported omission.'
 if any(x in h for x in ['lk-007','inf-rec-memorial','ter-013']):
  if any(x in s for x in ['ramp','launch']):return'implemented','Partial: the documented double concrete launch is anchored to the current mapped slipway and follows retained terrain; width, lane separation, extent and orientation remain authored. The DCR single launch is separately registered to the observed 2025 aerial run; its residual source shoreline mismatch remains documented.'
  if any(x in s for x in ['pavilion','snack','lifeguard','swim line','roped','courtesy dock']):return'uncertain','Amenities may be proposed or unverified. No unconfirmed beach furniture or operating condition is asserted.'
  return'already-present','Partial: retained beach terrain/water, pine-like tree forms, bathhouse massing and researched flagpole are present. Exact beach facilities and shore furniture need additional evidence.'
 if re.search(r'INF-DAM-(MA00108|MA00107|MA00216|MA00953)',text):return'implemented','Partial: the confirmed current mapped dam line receives only restrained water-supported crest fragments. No complete hydraulic structure, gate, exact masonry or flowing waterfall is claimed.'
 if any(x in h for x in ['eco-hab-07','dams, millraces']):return'implemented','Partial: four confirmed mapped dam lines gain low crest fragments; existing mapped river/impoundment surfaces remain unchanged. Other dams and canal architecture lack safely resolved geometry.'
 if any(x in h for x in ['ter-001','ter-002','ter-003','ter-004','ter-026','ter-027','lk-001','lk-003','lk-029','lk-030','lgt-24','eco-hab-01','eco-hab-10','eco-hab-11','eco-hab-13']):return'already-present','Setting-level: immutable mapped terrain, water, roads and building geometry supply geographic relief and density; authored road-edge corrections preserve them. Individual numeric source samples are not asserted to equal every rendered point.'
 if any(x in h for x in ['ter-007','ter-008','ter-009','ter-010','ter-011','ter-015','ter-023','ter-024','eco-hab-02','eco-hab-03','eco-hab-09','lgt-19','lgt-20']):return'already-present','Setting-level: finished asphalt/sidewalk/parking materials, lawn/soil/litter separation and habitat-informed broadleaf/conifer forms already exist. Exact species, drought state, individual plantings and minor furniture are not a surveyed inventory.'
 if 'eco-plant-'in h:return'remaining-review','General tree/ground forms exist; detailed species-form coverage remains incomplete. Species occurrence, authored form and exact specimen placement require separate judgments; sensitive/rare plants are not broadcast across the town.'
 if any(x in h for x in ['lk-004','lgt-23','eco-hab-06','eco-hab-14']):return'implemented','Partial: source lake remains full-pool; sheltered patches gain sparse lily-form foliage and wet-margin plants. Exact current clarity, blooms, invasive biomass, private docks and all shoreline structures remain unverified.'
 if any(x in h for x in ['lk-017','inf-rec-lakeside-ramp']):return'implemented','Partial: OFBA site 50 is now registered to the visible 2025 aerial run; one 3.1m concrete lane over 20m follows actual source terrain. Current source shoreline/terrain mismatch remains explicitly recorded; no longer guessed strip crosses adjacent shore lots.'
 if any(x in h for x in ['lk-031','game-asset implications','cross-cutting summary']):return'remaining-review','Mixed proposal/checklist, partially represented by existing and new scenery. Each supported component is tracked separately; the whole passage is not marked complete.'
 if any(x in h for x in ['inf-wat-','inf-rail-','inf-util-','site-','lk-','ter-','inf-rec-']):return'remaining-review','Mapped site/water/building/road context is retained where present. Detailed site furnishing/appearance has not been fully reconciled or reconstructed in this nonbridge pass. This is an implementation/review gap, not a conclusion that all source claims are uncertain.'
 return'remaining-review','Context/proposal retained for further component-level review. No completion or uncertainty conclusion is implied by absence from this implementation.'

def main():
 WORK.mkdir(parents=True,exist_ok=True);rows=[];sections=[]
 for stem in FILES:
  path=RESEARCH/'sections'/(stem+'.md');lines=path.read_text().splitlines();heading=stem;block=[];start=1
  def flush(end):
   if block:sections.append({'source':stem+'.md','heading':heading,'lineStart':start,'lineEnd':end,'text':'\n'.join(block)})
  for n,line in enumerate(lines,1):
   if line.startswith('#'):
    flush(n-1);heading=line.lstrip('# ').strip();start=n;block=[line];continue
   block.append(line)
   if not line.strip()or re.fullmatch(r'[|\s:\-]+',line)or line.strip().startswith('```'):continue
   status,reason=classify(stem,heading,line)
   rows.append({'id':stem+':'+str(n),'source':str(path),'sourceSha256':sha(path),'section':heading,'line':n,'text':line,'status':status,'coverageBasis':reason,'urls':re.findall(r'https?://[^\s<>\]]+',line),'dates':sorted(set(re.findall(r'\b(?:19|20)\d{2}(?:[‑-]\d{2}(?:[‑-]\d{2})?)?\b',line))),'sourceLabels':[label for label in ['Documented','Derived','Inferred','Historical','Unverified','Not established']if label.lower()in line.lower()]})
  flush(len(lines))
 issues=[{'id':'ENV-REVIEW-01','source':'terrain-ground-vegetation.md:5','issue':'Chapter advertises 38 TER entries but actual numbered section headings run TER-001 through TER-028. Ledger covers all actual lines, not the claimed count.'},
 {'id':'ENV-REVIEW-02','source':'institutions-utilities-sites.md:201','issue':'A square bounding box does not prove a circular treatment tank. No cylindrical basin replaces source geometry without actual shape/appearance evidence.'},
 {'id':'ENV-REVIEW-03','source':'terrain-ground-vegetation.md:312','issue':'The 2018/2019 plan statement about no tree program since 2004 cannot establish the complete 2026 planting history or age of every present tree.'},
 {'id':'ENV-REVIEW-04','source':'light-season-weather.md:LGT-23','issue':'Suspended hydro-raking alone does not establish fuller 2026 weed extent; herbicide treatment and ecological variation remain. Sparse contextual plants do not assert measured biomass.'},
 {'id':'ENV-REVIEW-05','source':'light-season-weather.md:LGT-19/LGT-30','issue':'User chose a green late-summer art direction. Historical drought alternatives do not override that preference or justify browning every lawn.'},
 {'id':'ENV-REVIEW-06','source':'infrastructure-landscape.md:Dams','issue':'Dam points, reported type/inspection/hazard and waterway labels do not establish current visible gates, flow, crest cross-section, or public access. Mapped line and actual water support gate the bounded additions.'}]
 known=[
 {'id':'ENV-REMAIN-01','feature':'DCR Lakeside Avenue single concrete launch','source':'lake-and-shoreline-detail.md','lines':[265,267,269],'supported':'One concrete lane and trailer parking are documented by MassWildlife/OFBA; agency access point is known.','remaining':'The single 20m concrete strip is now implemented against the 2025 aerial run. Original source shoreline is about9m from the aerial bank and has raised submerged terrain; that residual source alignment remains for a separate ground correction.','reason':'partial implementation; residual source shoreline alignment','owner':'environment'},
 {'id':'ENV-REMAIN-02','feature':'Ernie Benoit Rain Garden, Memorial Beach','source':'lake-and-shoreline-detail.md','lines':[149],'supported':'WLA documents the garden as a 2024 addition.','remaining':'Fresh dedication photograph (April5 2025; Yankee Xpress April25 p15) establishes trees/sign/shelter/bathhouse context, but no exact bed boundary can be registered through aerial tree cover. Existing wet-margin plants are not claimed as this named garden.','reason':'placement unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-03','feature':'French River Park / Davis Street reconstructed public edge','source':'infrastructure-landscape.md','lines':[358,360,362],'supported':'2025 annual report documents reconstructed curbs, sidewalks, drainage, streetlighting and outdoor-dining provision.','remaining':'Reconcile final extents/fixtures against current ground evidence. Existing road/parking finish is setting coverage, not completion of the entire phase.','reason':'implementation and final-layout reconciliation','owner':'root roadside / environment'},
 {'id':'ENV-REMAIN-04','feature':'May Street Park reconstruction','source':'infrastructure-landscape.md','lines':[366,368,370],'supported':'2025 report records reconstruction assistance; earlier OSRP records basketball/skate/play uses.','remaining':'Separate built final layout from earlier proposal before reconstructing individual play equipment or loop.','reason':'current layout unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-05','feature':'Webster Lake Dam MA02924 and Mill Brook Canal Dam MA02922','source':'infrastructure-landscape.md','lines':[159,161,176,177],'supported':'Current state/federal inventories identify both dams and points; lake regulation is documented.','remaining':'Resolve actual crest/gate geometry. The four new mapped dam treatments do not cover these two identities.','reason':'source geometry unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-06','feature':'Other inventoried dam structures beyond the four treated mapped lines','source':'infrastructure-landscape.md','lines':[146,147,148,150,152,153,154,155,156,157,158,160,162],'supported':'The chapter retains current point inventories as well as two explicitly unresolved draft-only records.','remaining':'Check scene boundary and present geometry one identity at a time; no arbitrary walls across inferred drainage. Draft-only Storage/Fish-and-Game records remain genuinely uncertain.','reason':'boundary and geometry reconciliation','owner':'environment'},
 {'id':'ENV-REMAIN-07','feature':'Ray Street, Little League and smaller recreation grounds','source':'institutions-utilities-sites.md','lines':[279,281,288,289,290,297,298,299],'supported':'Named fields, approach roads and principal footprints are mapped/documented.','remaining':'Full athletic-ground treatment, exact diamonds/court geometry and documented furniture are not completed here. Generic backstops, lighting poles and a duplicate fieldhouse are not established by the source.','reason':'implementation and exact field-layout reconciliation','owner':'environment / civic campus'},
 {'id':'ENV-REMAIN-08','feature':'Cudworth landfill solar site and public-works compounds','source':'institutions-utilities-sites.md','lines':[234,236,237],'supported':'Dated MassDEP permit describes array, ballasts, perimeter fencing and emergency access road.','remaining':'Reconcile present array footprints, rows and perimeter; a permit specification is not proof that every current panel position is rendered. Older proposed salt shed remains unverified.','reason':'dated evidence and current geometry reconciliation','owner':'environment / building evidence'},
 {'id':'ENV-REMAIN-09','feature':'Water-system sites and wastewater plant hardware','source':'institutions-utilities-sites.md','lines':[209,210,211,225,226,227],'supported':'Plant operations and water-system facilities are documented, and original building geometry is retained.','remaining':'Current tanks, railing, fencing and equipment appearance are not fully reconstructed. Square envelope cannot prove cylinder, and process function cannot place exact hardware.','reason':'appearance and geometry reconciliation','owner':'environment / building evidence'},
 {'id':'ENV-REMAIN-10','feature':'Lake businesses, boat slips and private shoreline hardware','source':'lake-and-shoreline-detail.md','lines':[184,194,244,246,344,346],'supported':'Indian Ranch venue features, restaurant slips and Point Breeze docking are documented.','remaining':'Exact current venue/dock layouts need additional placement evidence; general regional dock forms are inference. Buildings covered by facade work do not by themselves complete waterfront facilities.','reason':'implementation and placement reconciliation','owner':'landmarks / environment'},
 {'id':'ENV-REMAIN-11','feature':'Rail ballast, disused alignments and historic stone-wall segments','source':'terrain-ground-vegetation.md','lines':[209,211,275,283,285],'supported':'Rail corridors, protected scenic-road character and specific historical stone structures are documented at differing precision/vintages.','remaining':'Check actual segment geometry/current retention before adding individual ties, rail crossings or wall runs; no continuous invented roadside wall.','reason':'geometry and current-condition reconciliation','owner':'environment / root roadside'}]
 for k in known:
  p=RESEARCH/'sections'/k['source'];ls=p.read_text().splitlines();k['sourcePath']=str(p);k['sourceSha256']=sha(p);k['sourceExcerpts']=[{'line':n,'text':ls[n-1]}for n in k['lines']];k['urls']=sorted(set(re.findall(r'https?://[^\s<>\]]+', '\n'.join(x['text']for x in k['sourceExcerpts']))))
 issues.append({'id':'ENV-REVIEW-07','source':'institutions-utilities-sites.md:307','issue':'Two assessor structures on opposite sides of Worcester Road do not establish Mount Zion ownership of both grounds. Named current cemetery polygons are used separately, including St. Anthony east of Mount Zion.'})
 counts={key:sum(r['status']==key for r in rows)for key in ['implemented','already-present','inapplicable','supported-remaining','remaining-review','uncertain']}
 result={'version':2,'scope':FILES,'completeness':'Every substantive non-heading line in the five assigned source chapters is retained, including table records and uncertainty notes. Status is a render disposition, not a claim that every scientific/textual assertion was independently reverified. Setting-level and partial coverage are explicit. remaining-review means further decomposition or implementation is still needed; it must not be read as an uncertainty finding. supported-remaining tracks established features not yet fully rendered. uncertain is reserved for an explicit source limitation.','counts':counts,'sourceSections':len(sections),'sourceLines':len(rows),'reviewCorrections':issues,'knownSupportedRemaining':known,'details':rows}
 (WORK/'research-to-render-ledger.json').write_text(json.dumps(result,indent=2)+'\n');(WORK/'source-section-transcription.json').write_text(json.dumps(sections,indent=2)+'\n')
 out=['# Nonbridge research-to-render ledger','',result['completeness'],'',f"Coverage: {len(rows)} substantive source lines across {len(sections)} sections. Dispositions: {counts}.",'','## Corrections and limits','']
 for r in issues:out+=['- '+r['id']+' — '+r['source']+': '+r['issue']]
 (WORK/'known-supported-remaining.json').write_text(json.dumps(known,indent=2)+'\n')
 out+=['','## Known supported details still not completed','']
 for k in known:out+=['- **'+k['id']+' — '+k['feature']+'**: '+k['supported']+' Remaining: '+k['remaining']+' ('+k['reason']+'; '+k['owner']+'). Source: '+k['source']+':'+','.join(map(str,k['lines']))]
 last=None
 for r in rows:
  key=(r['source'],r['section'])
  if key!=last:out+=['','## '+r['section'],'','Source: '+r['source'],''];last=key
  out+=['- **'+r['status']+' · line '+str(r['line'])+'** — '+r['coverageBasis'],'  Source detail: '+r['text']]
 (WORK/'research-to-render-ledger.md').write_text('\n'.join(out)+'\n');print(json.dumps({'sourceLines':len(rows),'sourceSections':len(sections),'counts':counts,'corrections':len(issues)}))
if __name__=='__main__':main()
