"""Exhaustive line-level coverage ledger for the five assigned research chapters.

Every substantive source line is retained with its source section, line, URLs,
evidence/date labels, and an explicit render disposition. Partial coverage is
never described as an exact current survey or complete feature reconstruction.
"""
import hashlib,json,re,os
from pathlib import Path
SITE=Path(__file__).resolve().parents[2];RESEARCH=Path(os.environ.get('WEBSTER_RESEARCH','/Users/andy/Documents/New project/webster-blender/research'));WORK=Path(os.environ.get('WEBSTER_ENVIRONMENT_WORK','/private/tmp/webster-final-details/environment'))
FILES=['terrain-ground-vegetation','light-season-weather','lake-and-shoreline-detail','infrastructure-landscape','institutions-utilities-sites']
def urls(text):return sorted(set(u.rstrip(').,;')for u in re.findall(r'https?://[^\s<>\]]+',text)))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def classify(stem,heading,text):
 h=heading.lower();s=text.lower()
 if 'site-052'in h and any(x in s for x in ['not buildings','solar/electrical pads']):return'already-present','Source correction: electric-generation parcel coding does not make every outline a panel. Reviewed 2025 aerial and non-overlap with the mapped array retain the five actual yard structures. Registered rack axes are added separately.'
 if any(x in h for x in ['site-052','inf-util-solar'])and any(x in s for x in ['array','panel','solar']):return'implemented','Partial: 2025 aerial rack axes at Cudworth and Webster Solar receive authored tilted panels and support legs. Current rack placement is registered independently of the 2015 permit. Cudworth gains a source-registered perimeter and two open gate leaves with inferred height/hardware; exact wiring, ballast and gas vents remain unregistered. No fence is inferred at Webster Solar without equivalent evidence.'
 if 'site-051'in h and any(x in s for x in ['park road','standpipe']):return'already-present','Park Road source ID169571_866732 has an actual circular footprint and a 31m LiDAR-derived utility body with no residential openings. A new mapped storage-tank polygon and 2025 aerial corroborate the identity; the chapter square-envelope inference is not used as sole proof.'
 if any(x in s for x in ['basketball','tennis','futsal','baseball','football'])and any(x in h for x in ['inf-rec','site-05','site-06','lk-007']):return'implemented','Partial: mapped courts and field footprints receive grounded authored surfaces, regulation-style lines, hoops/nets/goals or inferred diamond markers where source support exists, plus four baseball backstops, nine benches and four football goals inside registered field boundaries. This does not establish every named fixture or a surveyed current equipment inventory; May Street reconstruction-era court is excluded.'
 if any(x in s for x in ['dock','slip','pier'])and any(x in h for x in ['lk-','inf-rec']):return'implemented','Partial: current mapped pier centerlines receive 126 water-supported deck segments, with authored width, boards, posts and elevation. Unsupported source-shore portions are withheld. Named commercial ownership, boat occupancy and exact current dock construction remain unverified.'
 if 'bridge'in h or re.search(r'\bINF-BR-',heading):return'inapplicable','Owned by bridge agent; cross-reference retained in the overall research ledger, no duplicate nonbridge object.'
 if any(x in h for x in ['sources','open questions','not reachable','coverage and evidence','conventions','method and reproducibility']):return'inapplicable','Research provenance/method/open question; retained as evidence, not a standalone visible object.'
 if any(x in s for x in ['not established','unverified','unresolved','unreachable','requiring verification','no exact','no mapped webster occurrence','no contemporary botanical']):return'uncertain','The source itself limits identity, present condition or placement. No exact appearance is promoted from this line.'
 if any(x in h for x in ['sun geometry','lgt-0','lgt-10','lgt-11','lgt-12','lgt-13','lgt-14','lgt-15','lgt-16','lgt-17','lgt-21','lgt-27','lgt-28','lgt-29','lgt-30','lgt-31']):return'inapplicable','Static green late-summer game uses authored lighting; calculation tables, weather histories and alternative night/drought modes are retained for reference, not implemented as simulation systems.'
 if any(x in s for x in ['pea soup','rouge','1974 report','drawdown ring','farmed bog','hay bales','golf course','frost','no farm fields','no autumn colour','no autumn color']):return'inapplicable','Historical/alternative/negative constraint. Default mode does not add obsolete pollution, drawdown, winter/autumn or unsupported agricultural scenery.'
 if 'invasive' in s and any(x in s for x in ['herbicide','fluridone','diquat','flumioxazin','hydro-raking','raking']):return'inapplicable','Management history is not a visual abundance measurement. No chemical treatment, current bloom or dense weed extent is inferred solely from it.'
 if any(x in h for x in ['ter-019','site-063','inf-rec-lakeside-cemetery','inf-rec-mount-zion']):
  if any(x in s for x in ['wall','fence','gate','crucifix','shrine','inscription','4,204','228 memorial']):return'uncertain','Mapped cemetery fields now have anonymous authored stones, but no exact wall/gate/shrine, individual grave layout or inventory count is fabricated.'
  return'implemented','Partial: five source-mapped cemetery grounds contain anonymous stone fields, clear of mapped roads, buildings, water, paved mask cells and source tree anchors. Shapes/count/spacing are explicit inference; retained source terrain, tree canopy and buildings remain intact. Inferred double-yellow lines on mapped unnamed cemetery drives are removed inside protected cemetery domains; public roads and white paint remain intact.'
 if any(x in h for x in ['eco-plant-018','eco-plant-019','eco-plant-022','ter-014','eco-hab-04']):return'implemented','Partial: sparse broad fern, rounded wet shrub and notched floating-pad forms are gated to mapped wet habitat and actual sheltered source water. Species allocation, individual positions and abundance remain inferred.'
 if 'ernie benoit rain garden' in s:return'unregistered-detail','ENV-REMAIN-02: the named 2024 garden exists, but its actual bed boundary is obscured in the reviewed dedication photo/aerial. Exact planting cannot be registered safely. Generic wet-margin plants are not attributed to this named garden.'
 if any(x in h for x in ['lk-007','inf-rec-memorial','ter-013']):
  if any(x in s for x in ['ramp','launch']):return'implemented','Partial: the documented double concrete launch is anchored to the current mapped slipway and follows retained terrain; width, lane separation, extent and orientation remain authored. The DCR single launch is separately registered to the observed 2025 aerial run; its source shoreline is now locally registered to the 2025 bank, with lowering-only terrain repair and a short traced gray access apron.'
  if any(x in s for x in ['pavilion','snack','lifeguard','swim line','roped','courtesy dock']):return'uncertain','Amenities may be proposed or unverified. No unconfirmed beach furniture or operating condition is asserted.'
  return'already-present','Partial: retained beach terrain/water, pine-like tree forms, bathhouse massing and researched flagpole are present. Exact beach facilities and shore furniture need additional evidence.'
 if re.search(r'INF-DAM-(MA00108|MA00107|MA00216|MA00953)',text):return'implemented','Partial: the confirmed current mapped dam line receives only restrained water-supported crest fragments. No complete hydraulic structure, gate, exact masonry or flowing waterfall is claimed.'
 if any(x in h for x in ['eco-hab-07','dams, millraces']):return'implemented','Partial: four confirmed mapped dam lines gain low crest fragments; existing mapped river/impoundment surfaces remain unchanged. Other dams and canal architecture lack safely resolved geometry.'
 if any(x in h for x in ['ter-001','ter-002','ter-003','ter-004','ter-026','ter-027','lk-001','lk-003','lk-029','lk-030','lgt-24','eco-hab-01','eco-hab-10','eco-hab-11','eco-hab-13']):return'already-present','Setting-level: immutable mapped terrain, water, roads and building geometry supply geographic relief and density; authored road-edge corrections preserve them. Individual numeric source samples are not asserted to equal every rendered point.'
 if any(x in h for x in ['ter-007','ter-008','ter-009','ter-010','ter-011','ter-015','ter-023','ter-024','eco-hab-02','eco-hab-03','eco-hab-09','lgt-19','lgt-20']):return'already-present','Setting-level: finished asphalt/sidewalk/parking materials, lawn/soil/litter separation and habitat-informed broadleaf/conifer forms already exist. Exact species, drought state, individual plantings and minor furniture are not a surveyed inventory.'
 if 'eco-plant-'in h:return'remaining-review','General tree/ground forms exist; detailed species-form coverage remains incomplete. Species occurrence, authored form and exact specimen placement require separate judgments; sensitive/rare plants are not broadcast across the town.'
 if any(x in h for x in ['lk-004','lgt-23','eco-hab-06','eco-hab-14']):return'implemented','Partial: source lake remains full-pool; sheltered patches gain sparse lily-form foliage and wet-margin plants. Exact current clarity, blooms, invasive biomass, private docks and all shoreline structures remain unverified.'
 if any(x in h for x in ['lk-017','inf-rec-lakeside-ramp']):return'implemented','Partial: OFBA site 50 is now registered to the visible 2025 aerial run; one 3.1m concrete lane over 20m follows actual source terrain. The small water extension and shallow bank correction now connect the run to the retained lake plane; a traced gray apron connects its upper end toward Lakeside Avenue. Source geometry outside this registered corridor remains unchanged.'
 if any(x in h for x in ['lk-031','game-asset implications','cross-cutting summary']):return'remaining-review','Mixed proposal/checklist, partially represented by existing and new scenery. Each supported component is tracked separately; the whole passage is not marked complete.'
 if any(x in h for x in ['inf-wat-','inf-rail-','inf-util-','site-','lk-','ter-','inf-rec-']):return'remaining-review','Mapped site/water/building/road context is retained where present. Detailed site furnishing/appearance has not been fully reconciled or reconstructed in this nonbridge pass. This is an implementation/review gap, not a conclusion that all source claims are uncertain.'
 return'remaining-review','Context/proposal retained for further component-level review. No completion or uncertainty conclusion is implied by absence from this implementation.'

def close_review(stem,heading,text):
 """Component review of the prior generic queue; does not assert total completion.

 Source/bibliography and shape inventories are separated from authored visual
 options. Every surviving visual omission points to a named component backlog.
 """
 h=heading.lower();s=text.lower();t=text.strip();bare=re.sub(r'\[[^\]]*\]\([^)]*\)','',t).strip(' *.;,')
 if not bare or t.startswith(('Source:','Source for all','Table source:'))or any(x in h for x in ['source register','scope','method','known missing work','conventions'])or t.startswith(('**Scope.','**What was','**What is here','Compiled ','As of ')):
  return'source-context','Source scope, provenance, bibliography or explicit limitation. Retained for traceability; it is not an unbuilt scenery object.'
 if t.startswith(('*History and dates*','*The building','*The amphitheatre*','*The campground*','*Samuel Slater','*The Indian Princess*','**Site layout','**Derived (site geometry)','**Derived** ranking','**Location'))and len(t)<100:
  return'source-context','Section/table label; appearance claims are handled on the substantive lines that follow.'
 if ('|' in t and not re.search(r'\d',t))or t.startswith(('**Derived (totals).','**Derived — the five','**Site geometry (Derived).','**Derived (site).','**Derived. Total')):
  return'source-context','Table heading or aggregate derived scale/count. Underlying object identities and visual proposals are reconciled separately.'
 if 'eco-plant-'in h:
  if t.startswith(('**Local confidence:','**Botanical basis:')):return'source-context','Regional/local botanical evidence, retained with its stated confidence. Current broadleaf/conifer and wet-plant families do not claim a surveyed species at any source tree anchor.'
  return'authored-option-unimplemented','ENV-REMAIN-12: species-specific leaves/needles and branching remain authored options beyond broadleaf/conifer habits. This pass improves bark shading and replaces one existing Cedar Swamp wet-shrub anchor with a Joe-Pye-like flower form; no new planting domain or surveyed species location is claimed. These are usable regional art options; individual specimen placement is inferred.'
 if stem=='light-season-weather':
  if 'espy' in h or 'magnus' in h:return'inapplicable','Atmospheric calculation or dawn-only fog proposal. The selected green warm-afternoon game does not implement weather/daylight progression; dawn fog is explicitly off at this time.'
  if 'lgt-18'in h:return'authored-option-unimplemented','ENV-REMAIN-12: one Joe-Pye-like wet-margin form is now applied at an existing qualified Cedar Swamp anchor. Goldenrod/aster and other distinct flower forms remain regional authored options without registered abundance or new planting beds. The Central-region phenology reports do not locate specimens or prove every named bloom in Webster.'
  if 'lgt-22'in h:return'inapplicable','Negative agricultural evidence or historical farmland context. No working crops, silos, livestock or hayfields are added from former farm names or Chapter 61 coding.'
  if 'lgt-25'in h:return'already-present','Setting-level: retained three-basin lake geometry, shore buildings and tree silhouettes bound the water horizon. Current water material supplies glints; the numerical fetch-dependent glitter model is an unimplemented authored option, not an exact observed feature.'
  if 'lgt-26'in h:return'authored-option-unimplemented','ENV-REMAIN-16: separate tannic-river absorption, foam/tributary mixing and low-flow hydraulics are not modeled. The source explicitly infers these visual states; no present water-color or discharge observation is promoted.'
  return'source-context','Season/lighting method and art-direction framing. Numerical alternatives are not additional physical objects or a claim about the actual chosen day.'
 if stem=='terrain-ground-vegetation':
  if 'ter-005'in h:return'unregistered-detail','ENV-REMAIN-13: exposed eastern ledge and rocky WMA terrain are supported regionally, but individual cut faces, talus and roots are not registered. Existing terrain/stone/litter provides setting only; no particular rock outcrop is claimed reconstructed.'
  if 'ter-006'in h:return'already-present','Setting-level: source elevation, water and woodland preserve the glacial landform/topographic context. Underground springs, aquifer genesis and ownership history add no visible mesh.'
  if 'ground surfaces by setting'in h:return'implemented','ENV-RESOLVED-14: verified MassDOT surface codes1/2/5 now supply restrained earth/gravel/surface-treated material variants on exact original ribbon triangles, all251 tiles and3LODs. Unknown0/missing/conflicting codes retain asphalt. Palette/roughness and coarse aggregate remain art inference, not measured current pavement color; entire named roads are never recolored from a table summary. Whole yellow/white paint triangles are removed only inside exact same-height earth/gravel source coverage, with paved/unknown overlap vetoes and conservative retained transitions.'
  if 'ter-012'in h:return'unregistered-detail','ENV-REMAIN-11: mapped rail/grade context is retained, but exact current ballast, ties, crossing panels and surviving abandoned rails have not been fully registered or added.'
  if 'ter-016'in h:return'source-context','Historic farm/forestry land-use evidence is not proof of current cultivated fields. Source buildings and land cover remain; active crops or farm operations are not invented.'
  if 'ter-017'in h:return'unregistered-detail','ENV-REMAIN-13: quarry parcels/building footprints identify the setting, but stockpile faces, conveyors, scales and gates are inferred and unregistered. The source terrain and roofed structures are retained.'
  if 'ter-018'in h:return'implemented','Partial: 2025 aerial-registered solar rows are rendered separately from the five retained roofed yard structures. The old assessor-code inference that all five outlines are panels is rejected. Cudworth has registered perimeter fencing and open gate leaves; ENV-REMAIN-08 records unregistered vents/wiring and unsupported fencing elsewhere.'
  if 'ter-020'in h:return'source-context','Scenic-road designation and mapped surface classes are setting/protection context, not surveyed wall or tree coordinates. ENV-REMAIN-11 tracks individual wall runs; ENV-RESOLVED-14 records implemented source-triangle road material distinctions.'
  if 'ter-021'in h or 'ter-022'in h:return'unregistered-detail','ENV-REMAIN-11: specific School Street source-photo frontages are protected in their authored module; additional historical wall/fence runs and inferred regional fence kits require separate current placement. This line does not prove an entire continuous wall or fence.'
  if 'ter-025'in h:return'source-context','Regional invasive list/local dated occurrence is biological context. It neither establishes a current abundance map nor authorizes painting every verge with that species.'
  if 'ter-028'in h:return'authored-option-unimplemented','ENV-REMAIN-17: regional/local wildlife presence is supported at differing dates, but animated fauna is not part of this driving scenery pass; no animal is pinned to a specific household.'
  if 'game-asset implications'in h:
   if any(x in s for x in ['**relief','**density']):return'already-present','Setting-level source terrain/building density is retained; tabulated average elevations and density are not exact per-vertex assertions.'
   if '**surfaces'in s:return'implemented','ENV-RESOLVED-14: road/parking/turf separation and exact source-triangle inventory material distinctions are implemented without road topology or geometry changes.'
   if '**walls'in s:return'unregistered-detail','ENV-REMAIN-11: generic retaining/field/fence proposals are not a registered current inventory; source-photo frontages remain separately protected.'
   if '**trees'in s:return'authored-option-unimplemented','ENV-REMAIN-12: broadleaf/conifer habits, habitat placement, improved bark and one qualified wet-margin flower form exist; exact species branching, utility pruning and invasive growth forms remain authored options; absence of a past tree program cannot prove no present young trees.'
   return'authored-option-unimplemented','ENV-REMAIN-17: optional wildlife/ambience proposal; no current exact locations or animations are implemented.'
 if stem=='lake-and-shoreline-detail':
  if 'lk-002'in h:return'unregistered-detail','ENV-REMAIN-05: mapped outlet/water level setting is retained, but current Webster Lake Dam crest/gate/enclosure geometry is unregistered. No low weir is inferred solely from the two-foot regulated head.'
  if 'lk-005'in h or 'lk-006'in h:return'other-domain','Named markers and the 170 Gore lake-name frontage are reconciled by the roadside/commercial catalogs. The plaza apron is now registered to 2025 aerial/2017 photo; historical naming/cultural facts are context, not new scenery.'
  if 'lk-010'in h or 'lk-015'in h or 'lk-020'in h:
   if any(x in s for x in ['**location','**derived','footprint','assessor','building','restaurant']):return'other-domain','Mapped building masses and selected exterior identities are covered by residential/commercial catalogs, with exact-ID matches attached below. This does not complete Indian Ranch/restaurant waterfront seating, event equipment or boat occupancy; see ENV-REMAIN-10/15.'
   if any(x in s for x in ['history','1946','1897','trolley','1881','1920','horse-drawn']):return'source-context','Dated venue/cultural history. Obsolete resort equipment and prior transport are not reinstated in the present game.'
   return'unregistered-detail','ENV-REMAIN-15: present venue amenities are documented, but exact benches, pavilions, gate equipment, RV furnishings are not fully reconstructed; the separate lake-life catalog provides an explicitly inferred Indian Princess boat scene. The author’s uncertain building-role assignments remain unverified.'
  if 'lk-026'in h:return'authored-option-unimplemented','ENV-REMAIN-10: no-wake/recreational use is documented; exact buoy, swim-line, mooring and boat positions are unregistered. Suggested red/green cans and boat mix are authored options, not fixed current observations.'
  if 'lk-027'in h:return'other-domain','Source shore-building footprints remain; classification as boathouse/cabana/garage follows residential/commercial identity evidence only. Added mapped pier decks do not establish all private shore hardware.'
  if 'lk-028'in h:return'other-domain','Residential evidence/source geometry handles the cottage, ranch and replacement-home mix. These historical/count/code summaries do not require independent duplicate buildings or underground utility models.'
  if 'lk-031'in h:return'source-context','Driving-camera route checklist, supported by the retained legal road graph and existing shoreline/building context. Individual markers, bridge families and facilities are tracked in their corresponding module ledgers; the route paragraph is not marked wholly reconstructed.'
  return'already-present','Setting-level lake peninsula/island/road/building geometry is retained. The source street/building statistics describe the neighborhood; fine retaining walls, fences and named-building appearance are separately limited, not asserted from this general setting.'
 if stem=='infrastructure-landscape':
  if 'span and railing' in h or 'brandon road' in h:return'other-domain','Bridge inventory/reopening/geometry evidence belongs to the bridge implementation ledger. Legacy inspection appraisal codes are not material observations and do not create duplicate bridge geometry.'
  if 'nid companion'in h:return'source-context','Dam identity/date/ownership and inventory-label reconciliation. Four current mapped crest families are rendered; ENV-REMAIN-05/06 retain the unresolved remaining geometry without fabricating hydraulic structures.'
  if 'inf-wat-'in h:return'source-context','Mapped waterbody identity, geometry and evidence context. Retained source hydrography supplies the setting; a named map feature is not a requirement for new water, dams, access claims or invented flow.'
  if any(x in h for x in ['inf-rail-','inf-rec-qvrt']):return'unregistered-detail','ENV-REMAIN-11: active/disused/proposed rail and trail identities are kept separate; exact surviving ballast/crossings/rails and completed public route geometry remain unregistered.'
  if 'inf-util-streets'in h or 'inf-util-sewer'in h:return'other-domain','Roadside utilities, mapped furniture and surface finish are root-owned. Pipe lengths and projected completion dates do not prove individual current poles, drains, manholes or underground layouts.'
  if 'inf-util-water'in h:return'unregistered-detail','Partial source utility masses are retained, including the verified Park Road standpipe. Nine aerial-registered open wastewater basins now occupy actual plan gaps; ENV-REMAIN-09 tracks remaining unregistered rails/fences/process hardware and avoids inventing the underground Rawson tank above ground.'
  if 'inf-rec-french-river'in h:return'unregistered-detail','ENV-REMAIN-03: finished base road/parking supports the public edge, but the final Davis Street phase extent, dining provision and exact furniture have not been fully registered.'
  if 'inf-rec-may'in h:return'unregistered-detail','ENV-REMAIN-04: old and proposed play equipment are distinct vintages; the reviewed spring 2025 aerial invalidates the old mapped basketball surface, and final replacement geometry is unresolved.'
  if any(x in h for x in ['inf-rec-berthol','inf-rec-starzec','inf-rec-bartlett','inf-rec-park-ave','inf-rec-slater-field','inf-rec-george']):return'implemented','Partial: mapped supported sports footprints receive appropriate authored court/field surfaces and linework; original sheds and trees outside exact exclusions remain. ENV-REMAIN-07 tracks unregistered equipment/fencing/seating.'
  if 'inf-rec-chase-access'in h or 'inf-rec-perryville-access'in h:return'unregistered-detail','ENV-REMAIN-18: documented modest car-top access lacks a registered current landing/run geometry; no duplicate marina, road ramp or causeway is invented.'
  if 'inf-rec-collins'in h:return'source-context','Historical meadow/rail resource and studied access candidate. A proposed public launch is not built; existing river/vegetation setting is retained.'
  if 'inf-rec-douglas'in h:return'inapplicable','Adjacent forest supplies a regional wooded-horizon context; detailed Douglas facilities are outside the present Webster source boundary.'
  if any(x in h for x in ['inf-rec-fenner','inf-rec-school','inf-rec-minebrook','inf-rec-slater']):return'already-present','Setting-level existing woodland/lawn/terrain and named source buildings remain, without inventing public paths or joining disconnected parcels. Fine rocks/roots/understory are ENV-REMAIN-12/13; named memorials are root-owned.'
  if 'eco-hab-05'in h or 'eco-hab-12'in h:return'source-context','Dated habitat/vernal-pool evidence has explicit current-map and taxonomic limits. General source canopy/wetland setting is retained; no exact rare-species or current protected-area boundary is fabricated.'
  if 'eco-hab-08'in h:return'authored-option-unimplemented','ENV-REMAIN-12: mown turf and bare/litter masks are present, but distinct tall bunchgrass, seedhead and late-summer flower morphology is not fully authored. Current abundance and exact patch identity remain inferred.'
  if 'terrain, soils'in h:return'source-context','Planning elevation/soil-map date/peak-label context. Existing elevation mesh remains the geometric authority; old labels do not overwrite individual terrain vertices.'
  return'source-context','Evidence framing or cross-cutting source limitation. This is not a newly located visible object; specific unresolved physical components are listed in the named environmental backlog.'
 if stem=='institutions-utilities-sites':
  if any(x in h for x in ['site-050','site-051','site-055']):
   if any(x in s for x in ['mgd','permit','phase ii','capacity','bod','full-time','phase-three','expir','demolition and replacement','chlorine','linear miles','history and capacity']):return'source-context','Operational/capacity/permit history. It cannot place above-ground equipment, prove present basin shape, or authorize an underground system reconstruction.'
   return'implemented','Partial: nine clear aerial-registered open wastewater basins (three circles, six central cells) occupy gaps disjoint from every mapped building. All original utility structures remain, including unresolved SID167878_865088. Park Road standpipe is already represented. ENV-REMAIN-09 tracks unregistered rails/fences/process hardware; square bounding boxes do not prove circular tanks.'
  if 'site-060'in h or 'site-061'in h or 'site-062'in h:return'implemented','Partial: mapped sports-ground surfaces/lines and original support buildings are present. Four inferred backstops, nine benches and four football goals are now contained within registered field footprints; ENV-REMAIN-07 tracks exact observed equipment placement, bleachers and individual lights; duplicate fieldhouses are prohibited by conflicting identity evidence.'
  if 'site-065'in h:return'unregistered-detail','ENV-REMAIN-15: source campground/pavilion masses and current mapped decks are retained, but all 200 transient RV sites, event gate/bench/pool equipment are not fully reconstructed; the separate lake-life catalog authors the documented two-deck/twin-wheel Indian Princess form with inferred berth and dimensions. No tentative role assignment is treated as a current survey.'
  if 'site-071'in h and any(x in s for x in ['ground and edges','game','trailer','apron']):return'other-domain','Industrial facade/source building geometry and selected loading-door treatments are commercial-owned. Full yard trailer ranks, fence runs and exact pole lights remain unregistered authored options, not guaranteed by the warehouse shape.'
  return'other-domain','Source building/campus geometry and selected appearance are handled by residential, commercial, institutional and civic catalogs; exact stable-ID catalog matches are attached to this line. Counts, use codes and broad inferred campus furnishings do not mean every detail has been rendered.'
 return'source-context','Non-object context retained without a new geometry claim.'

def main():
 WORK.mkdir(parents=True,exist_ok=True);rows=[];sections=[]
 release=json.loads((SITE/'data/derived/town/release.json').read_text());manifest_path=SITE/'public/town-assets'/release['directory']/'manifest.json'
 if sha(manifest_path)!=release['manifestSha256']:raise ValueError('Source manifest identity changed')
 manifest=json.loads(manifest_path.read_text());owners={}
 for tile in manifest['tiles']:
  for sid in tile.get('sourceIds',[]):owners.setdefault(str(sid),[]).append(tile['id'])
 catalogs={}
 for name in ['commercial-completion','institutional-completion','landmark-completion']:
  data=json.loads((SITE/'data/derived/town'/(name+'.json')).read_text())
  for row in data['rows']:
   sid=str(row.get('structId',row.get('id',''))).removeprefix('BLD-');catalogs.setdefault(sid,[]).append(name)
 def building_matches(text):
  return[{'id':sid,'sourceOwnerTiles':owners.get(sid,[]),'appearanceCatalogs':catalogs.get(sid,[]),'basis':'Exact stable ID only; source presence is not proof that every appearance detail is implemented.'}for sid in sorted(set(re.findall(r'BLD-(\d{6}_\d{6})',text)))]
 for stem in FILES:
  path=RESEARCH/'sections'/(stem+'.md');lines=path.read_text().splitlines();heading=stem;block=[];start=1
  def flush(end):
   if block:sections.append({'source':stem+'.md','heading':heading,'lineStart':start,'lineEnd':end,'text':'\n'.join(block)})
  for n,line in enumerate(lines,1):
   if line.startswith('#'):
    flush(n-1);heading=line.lstrip('# ').strip();start=n;block=[line];continue
   block.append(line)
   if not line.strip()or re.fullmatch(r'[|\s:\-]+',line)or line.strip().startswith('```'):continue
   status,reason=classify(stem,heading,line)
   if status=='remaining-review':status,reason=close_review(stem,heading,line)
   rows.append({'id':stem+':'+str(n),'source':str(path),'sourceSha256':sha(path),'section':heading,'line':n,'text':line,'status':status,'coverageBasis':reason,'urls':urls(line),'dates':sorted(set(re.findall(r'\b(?:19|20)\d{2}(?:[‑-]\d{2}(?:[‑-]\d{2})?)?\b',line))),'buildingMatches':building_matches(line),'sourceLabels':[label for label in ['Documented','Derived','Inferred','Historical','Unverified','Not established']if label.lower()in line.lower()]})
  flush(len(lines))
 issues=[{'id':'ENV-REVIEW-01','source':'terrain-ground-vegetation.md:5','issue':'Chapter advertises 38 TER entries but actual numbered section headings run TER-001 through TER-028. Ledger covers all actual lines, not the claimed count.'},
 {'id':'ENV-REVIEW-02','source':'institutions-utilities-sites.md:201','issue':'A square bounding box does not prove a circular treatment tank. Most listed source outlines are real roofed buildings; a square bounding box does not establish a circular tank. Nine separately aerial-registered open basins now occupy unbuilt gaps while every source structure remains. The dark southern SID167878_865088 remains unresolved and retained.'},
 {'id':'ENV-REVIEW-03','source':'terrain-ground-vegetation.md:312','issue':'The 2018/2019 plan statement about no tree program since 2004 cannot establish the complete 2026 planting history or age of every present tree.'},
 {'id':'ENV-REVIEW-04','source':'light-season-weather.md:LGT-23','issue':'Suspended hydro-raking alone does not establish fuller 2026 weed extent; herbicide treatment and ecological variation remain. Sparse contextual plants do not assert measured biomass.'},
 {'id':'ENV-REVIEW-05','source':'light-season-weather.md:LGT-19/LGT-30','issue':'User chose a green late-summer art direction. Historical drought alternatives do not override that preference or justify browning every lawn.'},
 {'id':'ENV-REVIEW-06','source':'infrastructure-landscape.md:Dams','issue':'Dam points, reported type/inspection/hazard and waterway labels do not establish current visible gates, flow, crest cross-section, or public access. Mapped line and actual water support gate the bounded additions.'}]
 known=[
 {'id':'ENV-REMAIN-01','feature':'DCR Lakeside Avenue single concrete launch','source':'lake-and-shoreline-detail.md','lines':[265,267,269],'supported':'One concrete lane and trailer parking are documented by MassWildlife/OFBA; agency access point is known.','remaining':'The single 20m concrete strip is now implemented against the 2025 aerial run. Original source shoreline is about9m from the aerial bank and has raised submerged terrain; that residual source alignment remains for a separate ground correction.','reason':'partial implementation; residual source shoreline alignment','owner':'environment'},
 {'id':'ENV-REMAIN-02','feature':'Ernie Benoit Rain Garden, Memorial Beach','source':'lake-and-shoreline-detail.md','lines':[148],'supported':'WLA documents the garden as a 2024 addition.','remaining':'Fresh dedication photograph (April5 2025; Yankee Xpress April25 p15) establishes trees/sign/shelter/bathhouse context, but no exact bed boundary can be registered through aerial tree cover. Existing wet-margin plants are not claimed as this named garden.','reason':'placement unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-03','feature':'French River Park / Davis Street reconstructed public edge','source':'infrastructure-landscape.md','lines':[358,360,362],'supported':'2025 annual report documents reconstructed curbs, sidewalks, drainage, streetlighting and outdoor-dining provision.','remaining':'Reconcile final extents/fixtures against current ground evidence. Existing road/parking finish is setting coverage, not completion of the entire phase.','reason':'implementation and final-layout reconciliation','owner':'root roadside / environment'},
 {'id':'ENV-REMAIN-04','feature':'May Street Park reconstruction','source':'infrastructure-landscape.md','lines':[366,368,370],'supported':'2025 report records reconstruction assistance; earlier OSRP records basketball/skate/play uses.','remaining':'Separate built final layout from earlier proposal before reconstructing individual play equipment or loop.','reason':'current layout unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-05','feature':'Webster Lake Dam MA02924 and Mill Brook Canal Dam MA02922','source':'infrastructure-landscape.md','lines':[159,161,176,177],'supported':'Current state/federal inventories identify both dams and points; lake regulation is documented.','remaining':'Resolve actual crest/gate geometry. The four new mapped dam treatments do not cover these two identities.','reason':'source geometry unresolved','owner':'environment'},
 {'id':'ENV-REMAIN-06','feature':'Other inventoried dam structures beyond the four treated mapped lines','source':'infrastructure-landscape.md','lines':[146,147,148,150,152,153,154,155,156,157,158,160,162],'supported':'The chapter retains current point inventories as well as two explicitly unresolved draft-only records.','remaining':'Check scene boundary and present geometry one identity at a time; no arbitrary walls across inferred drainage. Draft-only Storage/Fish-and-Game records remain genuinely uncertain.','reason':'boundary and geometry reconciliation','owner':'environment'},
 {'id':'ENV-REMAIN-07','feature':'Ray Street, Little League and smaller recreation grounds','source':'institutions-utilities-sites.md','lines':[279,281,288,289,290,297,298,299],'supported':'Named fields, approach roads and principal footprints are mapped/documented.','remaining':'Full athletic-ground treatment, exact diamonds/court geometry and documented furniture are not completed here. Generic backstops, lighting poles and a duplicate fieldhouse are not established by the source.','reason':'implementation and exact field-layout reconciliation','owner':'environment / civic campus'},
 {'id':'ENV-REMAIN-08','feature':'Cudworth landfill solar site and public-works compounds','source':'institutions-utilities-sites.md','lines':[234,236,237],'supported':'Dated MassDEP permit describes array, ballasts, perimeter fencing and emergency access road.','remaining':'Reconcile present array footprints, rows and perimeter; a permit specification is not proof that every current panel position is rendered. Older proposed salt shed remains unverified.','reason':'dated evidence and current geometry reconciliation','owner':'environment / building evidence'},
 {'id':'ENV-REMAIN-09','feature':'Water-system sites and wastewater plant hardware','source':'institutions-utilities-sites.md','lines':[209,210,211,225,226,227],'supported':'Plant operations and water-system facilities are documented, and original building geometry is retained.','remaining':'Current tanks, railing, fencing and equipment appearance are not fully reconstructed. Square envelope cannot prove cylinder, and process function cannot place exact hardware.','reason':'appearance and geometry reconciliation','owner':'environment / building evidence'},
 {'id':'ENV-REMAIN-10','feature':'Lake businesses, boat slips and private shoreline hardware','source':'lake-and-shoreline-detail.md','lines':[184,194,244,246,344,346],'supported':'Indian Ranch venue features, restaurant slips and Point Breeze docking are documented.','remaining':'Exact current venue/dock layouts need additional placement evidence; general regional dock forms are inference. Buildings covered by facade work do not by themselves complete waterfront facilities.','reason':'implementation and placement reconciliation','owner':'landmarks / environment'},
 {'id':'ENV-REMAIN-11','feature':'Rail ballast, disused alignments and historic stone-wall segments','source':'terrain-ground-vegetation.md','lines':[209,211,275,283,285],'supported':'Rail corridors, protected scenic-road character and specific historical stone structures are documented at differing precision/vintages.','remaining':'Check actual segment geometry/current retention before adding individual ties, rail crossings or wall runs; no continuous invented roadside wall.','reason':'geometry and current-condition reconciliation','owner':'environment / root roadside'}]
 resolved=[known.pop(0)]
 resolved[0].update(remaining='Resolved: source-registered 20m single concrete run, 167m² water-edge extension, lowering-only bank transaction and traced gray road-side apron are implemented and tested at all three LODs.',reason='implemented with documented geometric inference')
 updates={
 'ENV-REMAIN-04':'The reviewed spring 2025 aerial does not show a playable court at the old OSM basketball footprint. That stale footprint is explicitly excluded; a newer dated final equipment plan is still needed.',
 'ENV-REMAIN-06':'Nipmuck Pond line is now fetched and source-matched, but no safe visible crest span survives the existing road/building/water clearance gates. Western Dudley dams are beyond reliable current source support. Do not create a wall through a road solely to tick a dam inventory row.',
 'ENV-REMAIN-07':'Mapped court/field surfaces, inferred diamonds, four backstops, nine benches and four football goals are implemented and independently clear of the guided car at allLODs. These are restrained regional equipment shapes inside supported footprints, not surveyed current positions. Exact bleacher/light/fence configurations remain unregistered; no duplicate fieldhouse was added.',
 'ENV-REMAIN-08':'Visible 2025 rack axes at Cudworth and Webster Solar now have source-supported panels. Existing yard buildings remain because actual aerial roofs contradict the blanket not-buildings inference. Cudworth perimeter and two open gate leaves now follow the mapped plant boundary and reviewed current access with road/building exclusions. Height/hardware/open state are inferred. Exact ballast, wiring and gas vents remain unregistered; the Webster Solar fence lacks equivalent source support and is not fabricated.',
 'ENV-REMAIN-09':'Park Road standpipe retains its actual circular footprint and31m LiDAR body. Nine aerial-registered open wastewater basins (three circles/six central cells) are implemented in gaps disjoint from every mapped building; all original structures remain. Most listed outlines are real roofed buildings; SID167878_865088 remains unresolved. Exact railings/process hardware/current fences remain unregistered; underground Rawson tank must not become an invented visible cylinder.',
 'ENV-REMAIN-10':'Current mapped pier lines now receive 126 water-supported deck segments. Unsupported shore portions are withheld against the current source shoreline. Regional width, posts and decking are explicit inference; exact private/commercial ownership, boats and full current venue equipment remain unresolved.'}
 for k in known:
  if k['id']in updates:k['remaining']=updates[k['id']]

 extras=[
 ('12','Regional species morphology and late-summer flowers','terrain-ground-vegetation.md',[319,321,325],'Regional/local occurrence supports art families at differing confidence.','Broadleaf/conifer families, improved bark and one Joe-Pye-like existing wet-margin anchor are implemented. Exact leaf/needle branching, goldenrod/aster, blueberry/laurel and invasive growth forms remain optional regional assets without registered individual specimens.','regional authored options, not located omitted objects'),
 ('13','Individual rock cuts and quarry equipment','terrain-ground-vegetation.md',[136,249],'Ledge/quarry setting is documented.','Terrain and source roofed structures remain; individual exposed faces, roots, talus, conveyors and gates lack current registered geometry.','unregistered current detail'),
 ('15','Indian Ranch and waterfront venue fixtures','lake-and-shoreline-detail.md',[184,194],'Venue facilities and the two-deck/twin-wheel Indian Princess are documented.','Source venue masses/decks remain, and the lake-life catalog adds a boat with inferred berth/dimensions. Exact RV pads, event benches/gates, restaurant/pavilion identities and occupancy remain unregistered. Tentative assessor-role assignments are not current appearance evidence.','unregistered venue layout and occupancy'),
 ('16','Alternative water/atmosphere simulation','light-season-weather.md',[527,528],'The chapter describes regional and explicitly inferred water/lighting behavior.','Static afternoon water ripples and glints are present. Separate tannin absorption, tributary mixing/foam, dawn fog and weather progression are unimplemented inferred simulation options, not measured missing physical objects.','authored dynamic options outside selected static afternoon'),
 ('17','Animated regional wildlife','terrain-ground-vegetation.md',[380,382],'Dated local/regional fauna occurrence supports contextual possibilities.','No animated animals are placed from general occurrence alone. The driving scene does not simulate a current wildlife census.','regional animation option, no exact placement evidence'),
 ('18','Chase and Perryville car-top river access','infrastructure-landscape.md',[502,504,506,510,512,514],'Small car-top access sites are named.','Current landing/run outlines are not registered. A point or access label cannot justify a new marina, concrete trailer ramp or causeway.','unregistered landing geometry')]
 for number,feature,source,lines,supported,remaining,reason in extras:
  known.append({'id':'ENV-REMAIN-'+number,'feature':feature,'source':source,'lines':lines,'supported':supported,'remaining':remaining,'reason':reason,'owner':'environment'})
 resolved.append({'id':'ENV-RESOLVED-14','feature':'Exact road-inventory surface distinctions','source':'terrain-ground-vegetation.md','lines':[156,162,163,165],'supported':'Retained MassDOT per-edge surface_type and official numeric meanings identify earth/soil1, gravel/stone2 and surface-treated5.','remaining':'Resolved: exact original ribbon triangles receive restrained normalized-art material variants at251 tiles/all3LODs. All67,982 eligible physical triangles match at eachLOD; unknown0/missing/conflicting codes retain the original. Road surface topology/attributes/elevation and driving behavior remain unchanged. Only wholly supported earth/gravel yellow/white paint triangles are removed, with independent whole-area and same-height paved/unknown veto proof.','reason':'implemented; palette/roughness inferred from verified class, not measured current color','owner':'environment'})
 for k in known:
  if k['id']=='ENV-REMAIN-07':k['reason']='exact observed equipment positions and unregistered remaining fixtures'
  if k['id']=='ENV-REMAIN-08':k['reason']='unregistered fine hardware and unsupported fence claims elsewhere'
  if k['id']=='ENV-REMAIN-09':k['reason']='remaining unregistered process hardware; supported basin geometry implemented'
 issues.append({'id':'ENV-REVIEW-08','source':'institutions-utilities-sites.md:SITE-052','issue':'Electric Generation Plants coding does not establish that all five 23 Cudworth outlines are panels. Reviewed 2025 aerial shows real roofed yard buildings, separate from the mapped solar plant; source structures are protected.'})
 for k in known+resolved:
  p=RESEARCH/'sections'/k['source'];ls=p.read_text().splitlines();k['sourcePath']=str(p);k['sourceSha256']=sha(p);k['sourceExcerpts']=[{'line':n,'text':ls[n-1]}for n in k['lines']];k['urls']=urls('\n'.join(x['text']for x in k['sourceExcerpts']))
 issues.append({'id':'ENV-REVIEW-07','source':'institutions-utilities-sites.md:307','issue':'Two assessor structures on opposite sides of Worcester Road do not establish Mount Zion ownership of both grounds. Named current cemetery polygons are used separately, including St. Anthony east of Mount Zion.'})
 counts={key:sum(r['status']==key for r in rows)for key in sorted(set(r['status']for r in rows))}
 result={'version':4,'sourceManifestSha256':release['manifestSha256'],'scope':FILES,'completeness':'Every substantive non-heading line in the five assigned source chapters is retained, including table records and uncertainty notes. Status is a render disposition, not a claim that every scientific/textual assertion was independently reverified. Setting-level and partial coverage are explicit. The former generic remaining-review queue has been decomposed into source-context, other-domain, supported-unimplemented, authored-option-unimplemented and unregistered-detail. None means complete: supported-unimplemented identifies real omitted components, authored-option-unimplemented identifies regional model options, and unregistered-detail identifies known features lacking current precise placement. Exact building catalog matches are recorded separately from full appearance coverage. uncertain retains explicit source limitations. This ledger audits render applicability and implementation coverage, not the truth of every research sentence.','counts':counts,'sourceSections':len(sections),'sourceLines':len(rows),'reviewCorrections':issues,'resolvedThisPass':resolved,'knownSupportedRemaining':known,'details':rows}
 (WORK/'research-to-render-ledger.json').write_text(json.dumps(result,indent=2)+'\n');(WORK/'source-section-transcription.json').write_text(json.dumps(sections,indent=2)+'\n')
 out=['# Nonbridge research-to-render ledger','',result['completeness'],'',f"Coverage: {len(rows)} substantive source lines across {len(sections)} sections. Dispositions: {counts}.",'','## Corrections and limits','']
 for r in issues:out+=['- '+r['id']+' — '+r['source']+': '+r['issue']]
 (WORK/'resolved-this-pass.json').write_text(json.dumps(resolved,indent=2)+'\n')
 (WORK/'known-supported-remaining.json').write_text(json.dumps(known,indent=2)+'\n')
 out+=['','## Known supported details still not completed','']
 for k in known:out+=['- **'+k['id']+' — '+k['feature']+'**: '+k['supported']+' Remaining: '+k['remaining']+' ('+k['reason']+'; '+k['owner']+'). Source: '+k['source']+':'+','.join(map(str,k['lines']))]
 last=None
 for r in rows:
  key=(r['source'],r['section'])
  if key!=last:out+=['','## '+r['section'],'','Source: '+r['source'],''];last=key
  out+=['- **'+r['status']+' · line '+str(r['line'])+'** — '+r['coverageBasis'],'  Source detail: '+r['text']]
 (WORK/'research-to-render-ledger.md').write_text('\n'.join(out)+'\n');print(json.dumps({'sourceLines':len(rows),'sourceSections':len(sections),'counts':counts,'corrections':len(issues)}))
if __name__=='__main__':main()
