import * as THREE from 'three';
import catalog from '../../../data/derived/town/arrival-grounds.json';
import {PavementIndex,clipRoadPaintPolygon,roadPaintHeightAt} from './road-finish';
import type {V3} from './contracts';
import {Batch,type Frame} from './crafted-frontages';
export type GroundedSiteFeature={id:string;sid:string;site:string;kind:string;triangles:number[][][];basis:string;areaM2:number;color?:string;plantScale?:number};
export type GroundedSiteRecord={origin:number[];lods:{level:number;sha256:string}[];features:GroundedSiteFeature[]};
export type ArrivalGroundReport={status:'applied'|'source-mismatch'|'no-support';ids:string[];triangles:number;plantings:number;geometryBytes:number};
const tiles=catalog.tiles as Record<string,GroundedSiteRecord>;
const cross=(a:number[],b:number[],c:number[])=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const contains=(tri:number[][],point:number[])=>{const s=[cross(tri[0],tri[1],point),cross(tri[1],tri[2],point),cross(tri[2],tri[0],point)];return s.every(v=>v>=-1e-8)||s.every(v=>v<=1e-8);};
const noise=(x:number,y:number)=>{const n=Math.sin(x*12.9898+y*78.233)*43758.5453;return n-Math.floor(n);};
/** Grounded campus walks and modest foundation planting. Current driving
 * envelopes, source footprints and mapped water were subtracted offline. */
export function applyArrivalGrounds(group:THREE.Group,tileId:string,origin:V3,level:number,sha256:string):ArrivalGroundReport|undefined{
 return applyGroundedSiteFeatures(group,tileId,origin,level,sha256,tiles[tileId],'arrivalGrounds','Photo-informed campus arrivals');
}
/** Shared source-preserving terrain drape. Catalogs retain their own provenance
 * and transaction key; no geometry is moved to fit an annotation. */
export function applyGroundedSiteFeatures(group:THREE.Group,tileId:string,origin:V3,level:number,sha256:string,record:GroundedSiteRecord|undefined,stateKey:string,displayName:string):ArrivalGroundReport|undefined{
 if(!record)return;const prior=group.userData[stateKey] as ArrivalGroundReport|undefined;if(prior)return prior;
 const empty=(status:ArrivalGroundReport['status']):ArrivalGroundReport=>({status,ids:[],triangles:0,plantings:0,geometryBytes:0});
 if(record.lods.find(l=>l.level===level)?.sha256!==sha256||record.origin.some((v,i)=>v!==origin[i]))return empty('source-mismatch');
 const points=record.features.flatMap(f=>f.triangles.flat()),bounds=[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];
 const terrain:number[][][]=[],normalSource=new Map<number[][],number[][]>(),v=new THREE.Vector3(),n=new THREE.Vector3();group.updateMatrixWorld(true);const rootInverse=group.matrixWorld.clone().invert();
 group.traverse(o=>{if(!(o instanceof THREE.Mesh)||!/^terrain(?:\b|_)/i.test(o.name))return;const g=o.geometry,p=g.getAttribute('position'),normal=g.getAttribute('normal'),ix=g.index,matrix=rootInverse.clone().multiply(o.matrixWorld),nm=new THREE.Matrix3().getNormalMatrix(matrix);if(!p)return;for(let i=0;i<(ix?.count??p.count);i+=3){const tri=[0,1,2].map(k=>{v.fromBufferAttribute(p,ix?ix.getX(i+k):i+k).applyMatrix4(matrix);return[v.x+origin[0],-v.z-origin[2],v.y+origin[1]];});if(Math.max(...tri.map(p=>p[0]))<bounds[0]||Math.min(...tri.map(p=>p[0]))>bounds[2]||Math.max(...tri.map(p=>p[1]))<bounds[1]||Math.min(...tri.map(p=>p[1]))>bounds[3])continue;if(Math.abs(cross(...tri as[number[],number[],number[]]))<1e-7)continue;terrain.push(tri);if(normal)normalSource.set(tri,[0,1,2].map(k=>n.fromBufferAttribute(normal,ix?ix.getX(i+k):i+k).applyNormalMatrix(nm).toArray()));}});
 if(!terrain.length)return empty('no-support');const ground=new PavementIndex(terrain),batch=new Batch(new THREE.Vector3(...origin),level),ids=new Set<string>(),exclusions:number[][][]=[],bedShapes:{f:GroundedSiteFeature;tri:number[][]}[]=[];
 const emitted=new Set<string>();let groundFaces=0;
 for(const f of record.features){const positions:number[]=[],normals:number[]=[],frame:Frame={structId:f.sid,tileId,start:[0,0],tangent:[1,0],outward:[0,1]};for(const shape of f.triangles){for(const support of ground.candidates(shape)){const clipped=clipRoadPaintPolygon(shape,support.triangle);if(clipped.length<3)continue;if(cross(clipped[0],clipped[1],clipped[2])<0)clipped.reverse();for(let j=1;j<clipped.length-1;j++){
 const points=[clipped[0],clipped[j],clipped[j+1]].map(q=>[Math.fround(q[0]-origin[0])+origin[0],Math.fround(q[1]+origin[2])-origin[2]]);const area=cross(points[0],points[1],points[2]);if(Math.abs(area)<1e-7)continue;if(area<0)[points[1],points[2]]=[points[2],points[1]];const key=points.map(p=>p.map(v=>v.toFixed(4)).join(',')).sort().join('|');if(emitted.has(key))continue;emitted.add(key);const ns=normalSource.get(support.triangle),[a,b,c]=support.triangle,det=cross(a,b,c),heightOffset=f.kind==='bed'?.018:.012;
 for(const p of [points[0],points[2],points[1]]){const height=roadPaintHeightAt(support.triangle,p)+heightOffset;positions.push(p[0],height,p[1]);if(ns){const u=cross(a,p,c)/det,w=cross(a,b,p)/det;n.set(ns[0][0]*(1-u-w)+ns[1][0]*u+ns[2][0]*w,ns[0][1]*(1-u-w)+ns[1][1]*u+ns[2][1]*w,-ns[0][2]*(1-u-w)-ns[1][2]*u-ns[2][2]*w).normalize();normals.push(n.x,n.y,n.z);}else normals.push(0,1,0);}
 exclusions.push(points);groundFaces++;ids.add(f.id);if(f.kind==='bed')bedShapes.push({f,tri:points});
 }}}
 if(positions.length)batch.geometry(frame,'paving',positions,normals,f.color??(f.kind==='bed'?'#625546':'#aaa697'));}
 let plantings=0;if(level<2){const shrub=new THREE.SphereGeometry(1,level===0?7:5,level===0?5:4),p=shrub.getAttribute('position'),norm=shrub.getAttribute('normal'),ix=shrub.index,seen=new Set<string>();for(const{f,tri}of bedShapes){const spacing=1.7*(f.plantScale??1);const minX=Math.floor(Math.min(...tri.map(p=>p[0]))/spacing),maxX=Math.ceil(Math.max(...tri.map(p=>p[0]))/spacing),minN=Math.floor(Math.min(...tri.map(p=>p[1]))/spacing),maxN=Math.ceil(Math.max(...tri.map(p=>p[1]))/spacing);for(let x=minX;x<=maxX;x++)for(let y=minN;y<=maxN;y++){const key=spacing+':'+x+','+y;if(seen.has(key))continue;const seed=noise(x,y),point=[x*spacing+(seed-.5)*.4*(f.plantScale??1),y*spacing+(noise(y,x)-.5)*.4*(f.plantScale??1)];const s=[cross(tri[0],tri[1],point),cross(tri[1],tri[2],point),cross(tri[2],tri[0],point)];if(!(s.every(v=>v>=0)||s.every(v=>v<=0)))continue;const plantScale=f.plantScale??1;const radius=(.37+seed*.15)*plantScale+.08;if(!Array.from({length:12},(_,i)=>{const a=i*Math.PI/6;return[point[0]+Math.cos(a)*radius,point[1]+Math.sin(a)*radius];}).every(p=>f.triangles.some(t=>contains(t,p))))continue;seen.add(key);const hit=ground.candidates([point]).find(s=>{const t=s.triangle,q=[cross(t[0],t[1],point),cross(t[1],t[2],point),cross(t[2],t[0],point)];return q.every(v=>v>=0)||q.every(v=>v<=0);});if(!hit)continue;const height=roadPaintHeightAt(hit.triangle,point),size=(.37+seed*.15)*plantScale,positions:number[]=[],normals:number[]=[];for(let i=0;i<(ix?.count??p.count);i++){const k=ix?ix.getX(i):i;positions.push(point[0]+p.getX(k)*size,height+plantScale*(.36+norm.getY(k)*(.36+seed*.13)),point[1]+p.getZ(k)*size);n.set(norm.getX(k)/size,norm.getY(k)/((.36+seed*.13)*plantScale),norm.getZ(k)/size).normalize();normals.push(n.x,n.y,n.z);}batch.geometry({structId:f.sid,tileId,start:[0,0],tangent:[1,0],outward:[0,1]},'leaf',positions,normals,seed<.5?'#596b40':'#4b613c');plantings++;}}shrub.dispose();}
 if(!groundFaces)return empty('no-support');const built=batch.finish();built.group.name=displayName;group.add(built.group);group.userData.environmentGrassExclusions=[...(group.userData.environmentGrassExclusions??[]),...exclusions];const result:ArrivalGroundReport={status:'applied',ids:[...ids],triangles:built.triangles,plantings,geometryBytes:built.bytes};group.userData[stateKey]=result;return result;
}
