import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
const moduleName=process.env.PLAYWRIGHT_MODULE||'/Users/andy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const {chromium}=await import(moduleName.startsWith('/')?pathToFileURL(moduleName).href:moduleName);
if(!process.env.TOWN_URL)throw new Error('Set TOWN_URL to the local or immutable hosted candidate.');
import { writeFile, mkdir } from 'node:fs/promises';
const out=process.env.TOWN_MOBILE_OUT||'/private/tmp/webster-crafted-acceptance/mobile-'+new Date().toISOString().replace(/[:.]/g,'-');await mkdir(out,{recursive:true});
const report={started:new Date().toISOString(),url:process.env.TOWN_URL,configuration:{viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,physicalPhone:false,performanceBenchmark:false,injectedCurrentScopedCSS:false,captureScreenshots:process.env.TOWN_SCREENSHOTS!=='0',playwrightModule:moduleName},checks:[],screenshots:[],captureErrors:[],screenshotSkips:[],pageErrors:[],assetFailures:[],consoleErrors:[]};
let browser;
const record=(name,pass,evidence)=>{report.checks.push({name,pass,evidence});console.log(`${pass?'PASS':'FAIL'} ${name}`);};
try {
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--disable-dev-shm-usage']});
 report.browser=browser.version();
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,serviceWorkers:'block'});
 const page=await context.newPage();page.setDefaultTimeout(90000);
 page.on('pageerror',e=>report.pageErrors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});
 page.on('response',r=>{if(r.url().includes('/town-assets/')&&r.status()>=400)report.assetFailures.push({url:r.url(),status:r.status()})});
 const gated=[];page.on('request',r=>{if(/\/town-assets\/.*(?:manifest\.json|network\.json|\.glb)$/.test(r.url()))gated.push(r.url())});
 const shot=async(name,fullPage=false)=>{if(!report.configuration.captureScreenshots){report.screenshotSkips.push({name,reason:'TOWN_SCREENSHOTS=0; functional assertions unchanged.'});return;}const path=`${out}/${name}.png`;try{const bytes=await page.screenshot({fullPage,timeout:10000});await writeFile(path,bytes);report.screenshots.push({path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}catch(error){report.captureErrors.push({name,error:error.message,scope:'Optional artifact; functional assertions unchanged.'});}};
 const state=()=>page.evaluate(()=>{const g=window.__webster;if(!g)return null;const e=g.engine;return{ready:g.ready,edge:e.edgeId,road:e.edge.name,phase:e.phase,speed:e.speed,cruise:e.cruise,distance:e.distance,paused:e.paused,queued:e.queued,camera:g.cameraMode,frames:g.metrics.frames,contextLost:g.renderer.getContext().isContextLost(),pilot:g.world.manifest.stats.pilot,world:{...g.world.metrics},status:document.querySelector('[data-town-status]').textContent}});
 const layout=()=>page.evaluate(()=>{
   const r=el=>{const b=el.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom}};
   const stage=document.querySelector('.town-stage'),sr=r(stage),root=document.querySelector('[data-town-root]');
   const hud=[...document.querySelectorAll('.town-route,.town-directions,.town-instruments')].filter(e=>e.checkVisibility()).map(r);
   const touch=[...document.querySelectorAll('[data-town-input]')].map(el=>{const b=r(el),s=getComputedStyle(el),hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return{input:el.dataset.townInput,...b,visible:el.getClientRects().length>0&&s.display!=='none',withinStage:b.x>=sr.x-.5&&b.right<=sr.right+.5&&b.y>=sr.y-.5&&b.bottom<=sr.bottom+.5,hit:!!hit&&(hit===el||el.contains(hit)),touchAction:s.touchAction,overlapsHud:hud.some(h=>b.x<h.right&&b.right>h.x&&b.y<h.bottom&&b.bottom>h.y)}});
   const elements=[...document.querySelectorAll('[data-town-root] button,[data-town-root] select')].filter(e=>e.checkVisibility({checkVisibilityCSS:true,checkOpacity:true})).map(el=>({label:el.getAttribute('aria-label')||el.textContent.trim(),...r(el)}));
   return{viewport:{width:innerWidth,height:innerHeight},documentWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,coarse:matchMedia('(pointer: coarse)').matches,stage:sr,root:r(root),rootPosition:getComputedStyle(root).position,rootClass:root.className,hudOverlap:hud.some((b,i)=>hud.some((h,j)=>j>i&&b.x<h.right&&b.right>h.x&&b.y<h.bottom&&b.bottom>h.y)),fullscreen:document.fullscreenElement===root,bodyOverflow:getComputedStyle(document.body).overflow,fullscreenControl:{label:document.querySelector('[data-town-fullscreen]').textContent,pressed:document.querySelector('[data-town-fullscreen]').getAttribute('aria-pressed')},touch,elements,canvas:{width:document.querySelector('[data-town-canvas]').width,height:document.querySelector('[data-town-canvas]').height},theme:document.documentElement.dataset.theme};
 });
 const stageTop=()=>page.evaluate(()=>document.querySelector('[data-town-root]').scrollIntoView({block:'start',behavior:'instant'}));
 const response=await page.goto(report.url,{waitUntil:'domcontentloaded'});if(response.status()!==200)throw new Error(`Preview is not stable: HTTP ${response.status()}`);console.log('Loaded current static town HTML');
 await page.locator('[data-town-play]').waitFor({state:'visible'});
 // Use only the candidate's actual delivered CSS, with no stylesheet injection.
 await shot('01-portrait-before-play');
 record('Heavy game assets stay unloaded before Play',gated.length===0,{requests:gated.slice()});
 let l=await layout();record('Portrait has no horizontal page overflow',l.documentWidth<=l.viewport.width&&l.bodyWidth<=l.viewport.width,l);
 await page.locator('[data-town-play]').tap();
 await page.waitForFunction(()=>window.__webster?.ready&&window.__webster.metrics.frames>=3,null,{timeout:90000});
 await page.waitForFunction(()=>window.__webster.world.metrics.loaded>0&&window.__webster.world.metrics.pending===0,null,{timeout:60000});await stageTop();await page.waitForTimeout(400);
 await shot('02-portrait-ready');
 let s=await state();record('Touch Play creates running WebGL town',s.ready&&!s.contextLost,s);
 report.release=await page.evaluate(()=>{const g=window.__webster,m=g.world.manifest;return{manifestUrl:g.world.manifestUrl,tiles:m.tiles.length,buildings:m.stats.buildings,pilot:m.stats.pilot,sourceSha256:m.source?.sha256??m.sourceSha256,network:m.network,treePrototypes:m.trees.prototypes,surfaceMasks:Object.keys(m.surfaces?.masks??{}).length};});
 const mobileShadows=await page.evaluate(()=>{const g=window.__webster;let castingTreeGroups=0;g.world.root.traverse(o=>{if(o.isInstancedMesh&&o.userData.treeKind&&o.castShadow)castingTreeGroups++;});return{rendererShadowEnabled:g.renderer.shadowMap.enabled,worldTreeShadows:g.world.treeShadows,castingTreeGroups};});record('Mobile profile disables ordinary tree and renderer shadows',!mobileShadows.rendererShadowEnabled&&!mobileShadows.worldTreeShadows&&mobileShadows.castingTreeGroups===0,mobileShadows);
 l=await layout();record('Portrait touch controls visible, hit-testable and within stage',l.coarse&&l.touch.every(x=>x.visible&&x.hit&&x.withinStage&&x.width>=44&&x.height>=44),l);
 const before=await state();await page.locator('[data-town-input="up"]').tap();
 await page.waitForTimeout(1800);const moving=await state();
 record('Touch Go starts cruise and advances after finger release',moving.cruise>0&&moving.speed>0&&moving.distance>before.distance,{before,after:moving});
 await page.locator('[data-town-input="left"]').tap();const left=await state();
 record('Touch left queues a left turn',left.queued==='LEFT',left);
 await page.locator('[data-town-input="right"]').tap();const right=await state();
 record('Touch right replaces queued turn',right.queued==='RIGHT',right);
 await page.locator('[data-town-pause]').tap();await page.waitForTimeout(100);const paused=await state();
 await page.waitForTimeout(650);const still=await state();
 record('Touch Pause stops travel',paused.paused&&still.paused&&Math.abs(still.distance-paused.distance)<1e-6,{paused,after:still});
 await stageTop();await shot('03-portrait-paused');
 await page.locator('[data-town-pause]').tap();await page.waitForTimeout(100);const resumed=await state();record('Touch Resume restarts',!resumed.paused,resumed);
 const cdp=await context.newCDPSession(page);const brake=await page.locator('[data-town-input="down"]').boundingBox();const beforeBrake=await state();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:brake.x+brake.width/2,y:brake.y+brake.height/2}]});
 await page.waitForFunction(()=>window.__webster.engine.speed<.05,null,{timeout:12000});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const stopped=await state();record('Held touchscreen Brake slows/stops car',beforeBrake.speed>1&&stopped.speed<.05&&stopped.cruise===0,{before:beforeBrake,after:stopped});
 await page.locator('[data-town-pause]').tap();
 await page.setViewportSize({width:844,height:390});await stageTop();await page.waitForTimeout(500);
 await shot('04-landscape-inline');l=await layout();
 record('Landscape has no horizontal page overflow',l.documentWidth<=l.viewport.width&&l.bodyWidth<=l.viewport.width,l);
 record('Landscape inline controls fit inside game stage',l.coarse&&l.touch.every(x=>x.visible&&x.withinStage&&x.width>=44&&x.height>=44),l);record('Landscape inline touch controls visible in viewport',l.touch.every(x=>x.hit&&x.y>=0&&x.bottom<=l.viewport.height),l);
 await page.locator('[data-town-fullscreen]').tap();await page.waitForTimeout(500);l=await layout();await shot('05-landscape-fullscreen');
 record('Native fullscreen or expanded fallback fills viewport',l.root.width>=l.viewport.width-1&&l.root.height>=l.viewport.height-1&&Math.abs(l.root.x)<1&&Math.abs(l.root.y)<1,l);
 record('Landscape fullscreen controls visible without clipping',l.coarse&&l.touch.every(x=>x.hit&&x.withinStage&&x.y>=0&&x.bottom<=l.viewport.height),l);
 if(l.fullscreen)await page.evaluate(()=>document.exitFullscreen());
 else await page.locator('[data-town-fullscreen]').tap();
 await page.setViewportSize({width:390,height:844});await stageTop();await page.waitForTimeout(300);
 // Bounded fault injection exercises browsers where Element.requestFullscreen is unavailable.
 await page.evaluate(()=>Object.defineProperty(document.querySelector('[data-town-root]'),'requestFullscreen',{value:undefined,configurable:true}));
 await page.locator('[data-town-fullscreen]').tap();await page.waitForTimeout(350);l=await layout();await shot('06-portrait-fullscreen-fallback');
 record('Fullscreen unavailable fallback expands the game',l.rootClass.includes('town-expanded')&&l.rootPosition==='fixed'&&l.root.width>=l.viewport.width-1&&l.root.height>=l.viewport.height-1&&l.bodyOverflow==='hidden',l);
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(350);l=await layout();await shot('06b-landscape-fullscreen-fallback');record('Landscape fallback controls and toolbar fit viewport',l.coarse&&l.touch.every(x=>x.hit&&x.withinStage&&x.bottom<=l.viewport.height)&&l.elements.every(x=>x.y>=0&&x.bottom<=l.viewport.height+.5),l);
 await page.locator('.town-radio > summary').tap();await page.waitForTimeout(250);l=await layout();await shot('06c-landscape-open-radio');record('Expanded landscape radio keeps driving controls accessible',!l.hudOverlap&&l.stage.height>=180&&l.touch.every(x=>x.hit&&x.withinStage&&!x.overlapsHud&&x.bottom<=l.viewport.height),l);
 const radio=await page.locator('.town-radio__body').evaluate(e=>({height:e.clientHeight,scrollHeight:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));record('Expanded radio panel can scroll to all stations',radio.scrollHeight>radio.height&&radio.overflow==='auto',radio);
 await page.locator('.town-radio > summary').tap();
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);
 await page.locator('[data-town-fullscreen]').tap();
 await page.emulateMedia({colorScheme:'dark'});await page.waitForTimeout(300);await stageTop();await shot('07-portrait-dark');
 const colors=await page.evaluate(()=>{
   const get=s=>{const el=document.querySelector(s),c=getComputedStyle(el);return{foreground:c.color,background:c.backgroundColor,fontSize:c.fontSize}};
   return{theme:document.documentElement.dataset.theme,body:get('body'),heading:get('.town-heading h1'),status:get('[data-town-status]'),pause:get('[data-town-pause]'),touch:get('[data-town-input="up"]'),panel:get('.town-directions')};
 });record('Dark preference applies to page and controls',colors.theme==='dark',colors);
 const fin=await state();record('Rotate/fullscreen/dark operations keep WebGL active',fin.ready&&!fin.contextLost,fin);
 record('No page errors or failed town assets',report.pageErrors.length===0&&report.assetFailures.length===0&&report.consoleErrors.length===0,{pageErrors:report.pageErrors,assets:report.assetFailures,console:report.consoleErrors});
 report.completed=new Date().toISOString();report.passed=report.checks.every(c=>c.pass);
}catch(e){report.error=e.stack;console.error(e.stack)}finally{if(browser)await browser.close();await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(`REPORT ${out}/report.json checks=${report.checks.filter(c=>c.pass).length}/${report.checks.length} passed=${Boolean(report.passed)}`);if(!report.passed)process.exitCode=1;}
