#!/usr/bin/env node
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const moduleName=process.env.PLAYWRIGHT_MODULE||'/Users/andy/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const {chromium}=await import(moduleName.startsWith('/')?pathToFileURL(moduleName).href:moduleName);
const url=process.env.TOWN_URL;if(!url)throw Error('Set TOWN_URL to the frozen candidate');
const out=process.env.TOWN_UX_OUT||'/private/tmp/webster-finished-game/ux/browser';await mkdir(out,{recursive:true});
const report={url,started:new Date().toISOString(),passed:false,checks:[],screenshots:[],errors:[],physicalPhone:false,screenReader:false,externalStationsTested:false};let browser;
const check=async(name,fn)=>{const began=Date.now();try{const evidence=await fn();report.checks.push({name,passed:true,ms:Date.now()-began,evidence});console.log('PASS '+name)}catch(error){report.checks.push({name,passed:false,error:String(error)});throw error}};
try{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:2,serviceWorkers:'block'});
 await context.addInitScript(()=>{window.__uxAudioContexts=0;const Original=window.AudioContext;window.AudioContext=class extends Original{constructor(...args){super(...args);window.__uxAudioContexts++}}});
 const page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>report.errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>window.__webster?.ready&&window.__webster.metrics.frames>3);
 const shot=async name=>{await page.locator('[data-town-canvas]').screenshot({path:`${out}/${name}.png`});report.screenshots.push(`${out}/${name}.png`)};
 const state=()=>page.evaluate(()=>{const g=window.__webster,e=g.engine;return{road:e.edge.name,edge:e.edgeId,s:e.s,speed:e.speed,distance:e.distance,paused:e.paused,queued:e.queued,queuedEdge:e.queuedEdge,camera:g.cameraMode,dpr:g.renderer.getPixelRatio(),status:document.querySelector('[data-town-status]').textContent,contexts:window.__uxAudioContexts,presentation:g.presentation,metrics:g.metrics}});
 await page.goto(url,{waitUntil:'domcontentloaded'});
 await check('No game or audio activation before Play',async()=>{const s=await page.evaluate(()=>({game:!!window.__webster,contexts:window.__uxAudioContexts}));assert.equal(s.game,false);assert.equal(s.contexts,0);return s});
 await page.locator('[data-town-location]').selectOption('BEACH');await page.locator('[data-town-play]').click();await ready();
 await check('Preselected Beach start, readable full name and opt-in sound',async()=>{const s=await state();assert.match(s.road,/MEMORIAL BEACH/);assert.equal(s.contexts,0);assert.doesNotMatch(s.status,/Ready on Main Street/);assert.equal(await page.locator('[data-town-road]').textContent(),'Memorial Beach Drive');assert.match(await page.locator('[data-town-choices]').textContent(),/Memorial Beach Drive/);return s});
 await shot('beach-readable-hud');
 await check('Branch button retains keyboard focus on exact selection',async()=>{const button=page.locator('[data-town-choices] button').first();const id=await button.getAttribute('data-edge');await button.focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.edge),id);assert.equal((await state()).queuedEdge,Number(id));await page.locator('[data-town-clear]').click();assert.equal((await state()).queuedEdge,null);return{id}});
 await check('Quality, camera and comfort preferences are persisted',async()=>{await page.locator('[data-town-quality]').selectOption('low');await page.locator('[data-town-camera]').click();await page.locator('[data-town-comfort]').selectOption('steady');const s=await state();assert.equal(s.dpr,1);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('webster-drive-preferences-v1')));assert.equal(saved.comfort,'steady');assert.equal(saved.camera,s.camera);return{s,saved}});
 await check('Explore map and report generate a local exact location payload',async()=>{await page.locator('[data-town-explore] > summary').click();await page.waitForFunction(()=>window.__webster.engine.paused);assert.equal((await state()).paused,true);assert.equal(await page.locator('[data-town-place]').count(),6);await page.locator('[data-town-report]').click();await page.locator('[data-town-report-note]').fill('Native UX regression: this is a local-only note.');await page.locator('[data-town-report-copy]').click();const data=JSON.parse(await page.locator('[data-town-report-output]').inputValue());assert.equal(data.edge,(await state()).edge);assert.match(data.note,/local-only/);assert.ok(data.pose.flat().every(Number.isFinite));await page.locator('[data-town-explore] > summary').click();return data});
 await check('Driving sound can activate and all-sound mute disables its control',async()=>{await page.locator('[data-town-sound]').click();assert.equal(await page.locator('[data-town-sound]').getAttribute('aria-pressed'),'true');await page.locator('[data-town-mute]').click();assert.equal(await page.locator('[data-town-sound]').getAttribute('aria-pressed'),'false');assert.equal((await state()).contexts,1);return{contexts:(await state()).contexts}});
 await check('Pause saves a road position; reload offers a safe explicit resume',async()=>{await page.locator('[data-town-canvas]').focus();await page.keyboard.press('ArrowUp');await page.waitForTimeout(1500);await page.locator('[data-town-pause]').click();const before=await state();assert.equal(before.paused,true);await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-town-resume]').waitFor({state:'visible'});assert.equal(await page.locator('[data-town-quality]').inputValue(),'low');await page.locator('[data-town-resume]').click();await ready();const after=await state();assert.equal(after.paused,true);assert.equal(after.speed,0);assert.equal(after.edge,before.edge);assert.ok(Math.abs(after.s-before.s)<.001);assert.equal(after.dpr,1);assert.equal(after.contexts,0);return{before,after}});
 await check('Paused rendering is bounded and camera controls remain responsive',async()=>{await page.waitForTimeout(250);const before=await state();assert.equal(before.paused,true);await page.waitForTimeout(650);const after=await state();const draws=after.metrics.frames-before.metrics.frames;assert.ok(draws>=2&&draws<=8,`Paused draws in650ms: ${draws}`);const camera=after.camera;await page.locator('[data-town-camera]').click();await page.waitForFunction(frames=>window.__webster.metrics.frames>frames,after.metrics.frames);assert.notEqual((await state()).camera,camera);assert.equal((await state()).distance,before.distance);return{draws,milliseconds:650,camera:(await state()).camera}});
 await check('WebGL context loss can restart locally into one paused game',async()=>{await page.evaluate(()=>window.__webster.renderer.getContext().getExtension('WEBGL_lose_context').loseContext());await page.locator('[data-town-restart]').waitFor({state:'visible'});await page.locator('[data-town-restart]').click();await ready();const s=await state();assert.equal(s.paused,true);assert.equal(s.speed,0);assert.equal(await page.locator('[data-town-canvas]').count(),1);assert.equal(await page.evaluate(()=>window.__webster.renderer.getContext().isContextLost()),false);return s});
 await check('Desktop choices have full text and bounded target geometry',async()=>{const rows=await page.locator('[data-town-choices] button').evaluateAll(buttons=>buttons.map(b=>{const r=b.getBoundingClientRect(),n=b.querySelector('.town-choice__name');return{text:n.textContent,width:r.width,height:r.height,overflow:getComputedStyle(n).textOverflow}}));assert.ok(rows.every(r=>r.width>44&&r.height>=44&&r.overflow!=='ellipsis'));return rows});
 await page.locator('[data-town-location]').selectOption('DOWNTOWN');await page.waitForFunction(()=>window.__webster?.engine.edge.name==='MAIN STREET');await page.waitForTimeout(1000);await shot('downtown-finished-hud');
 for(const [width,height,name]of[[390,844,'portrait'],[844,390,'landscape']]){await page.setViewportSize({width,height});await page.waitForTimeout(300);await check(`${name} has readable controls and a clear road viewport`,async()=>{const s=await page.evaluate(()=>{const canvas=document.querySelector('[data-town-canvas]').getBoundingClientRect(),directions=document.querySelector('.town-directions').getBoundingClientRect(),instruments=document.querySelector('.town-instruments').getBoundingClientRect();return{viewport:innerWidth,width:document.documentElement.scrollWidth,canvasHeight:canvas.height,clearRoadHeight:instruments.top-directions.bottom,choices:[...document.querySelectorAll('[data-town-choices] button')].map(b=>({text:b.textContent,width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height}))}});assert.ok(s.width<=width+1);assert.ok(s.choices.every(b=>b.width>=44&&b.height>=44));if(name==='portrait')assert.ok(s.clearRoadHeight>=180,`Only${s.clearRoadHeight}px of clear road`);return s});await shot(`${name}-hud`)}
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(error){report.error=String(error);process.exitCode=1;console.error(error)}finally{report.finished=new Date().toISOString();await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));await browser?.close()}
