/** Real source GLBs, exact source preservation, and emitted paint for GEOS QA. */
import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{fileURLToPath,pathToFileURL}from'node:url';import{gzipSync}from'node:zlib';import{build}from'esbuild';
import*as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.ROAD_DASH_WORK??'/private/tmp/webster-finished-game/road-dashes',read=p=>JSON.parse(fs.readFileSync(p)),release=read(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=read(base+'manifest.json'),index=read(root+'/data/derived/town/road-dash-index.json'),roadIndex=read(root+'/data/derived/town/road-finish-index.json');
const imports=['road-finish','road-material-finish','terrain-finish','environment-ground','bridge-surface','road-dash-finish'];fs.writeFileSync(work+'/audit-entry.ts',imports.map(n=>`export * from '${root}/src/lib/town/${n}';`).join('\n'));
await build({entryPoints:[work+'/audit-entry.ts'],outfile:work+'/audit-api.mjs',bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'shared-three',setup(b){b.onResolve({filter:/^three$/},()=>({path:fileURLToPath(import.meta.resolve('three')),external:true}))}}]});const api=await import(pathToFileURL(work+'/audit-api.mjs'));
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1))}}));const asset=r=>r?read(root+'/public'+r.url):undefined,report=[];
for(const tile of manifest.tiles.filter(t=>index.tiles[t.id]))for(const lod of tile.lods){
 const bytes=fs.readFileSync(base+lod.url),scene=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),pathToFileURL(path.dirname(base+lod.url)+'/').href)).scene;
 api.applyMeasuredBridgeSurface(scene,tile.id,tile.origin);api.applyTerrainFinish(scene,tile.id,tile.origin,lod.level,asset(api.terrainFinishAsset(tile.id,lod.level)));api.applyEnvironmentGround(scene,tile.id,tile.origin,lod.level,asset(api.environmentGroundAsset(tile.id,lod.level)));api.applyRoadFinish(scene,tile.id,tile.origin,lod.level,asset(roadIndex.tiles[tile.id])?.rows??[]);api.applyRoadMaterialFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,asset(api.roadMaterialAsset(tile.id,lod.level)));
 const packet=asset(api.roadDashAsset(tile.id,lod.level));assert.ok(api.validRoadDashPacket(packet,tile.id,lod.level));
 const before=[];scene.traverse(mesh=>{if(mesh.isMesh){const g=mesh.geometry;before.push({mesh,g,material:mesh.material,attributes:{...g.attributes},index:g.index?Array.from(g.index.array):null});}});
 const snapshot=()=>before.every(r=>r.mesh.geometry===r.g&&r.mesh.material===r.material);assert.ok(api.applyRoadDashFinish(scene,tile.id,tile.origin,lod.level,'0'.repeat(64),packet).rejected);assert.ok(snapshot());const wrong=structuredClone(packet);wrong.guards[0].geometryStamp='00000000';assert.ok(api.applyRoadDashFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,wrong).rejected);assert.ok(snapshot());
 const began=performance.now(),result=api.applyRoadDashFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,packet);assert.ok(result.applied);const ms=performance.now()-began,children=scene.children.length;assert.equal(api.applyRoadDashFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,packet),result);assert.equal(scene.children.length,children);
 const removed=[],pavement=[],retainedWhite=[],added=[];scene.updateMatrixWorld(true);const pt=new THREE.Vector3();
 for(const r of before){const target=packet.targets.find(t=>t.name===r.mesh.name&&t.parent===r.mesh.parent?.name),g=r.mesh.geometry;assert.equal(r.mesh.material,r.material);for(const[name,a]of Object.entries(r.attributes))assert.equal(g.getAttribute(name),a);const n=r.index?.length??r.g.getAttribute('position').count;
  if(target){const ids=Array.from({length:n},(_,i)=>i).filter(i=>!target.remove.includes(Math.floor(i/3))).map(i=>r.index?.[i]??i);assert.deepEqual(Array.from(g.index.array),ids);}else assert.equal(g,r.g);
  const material=Array.isArray(r.material)?r.material:[r.material],position=r.g.getAttribute('position');for(const part of r.g.groups.length?r.g.groups:[{start:0,count:n,materialIndex:0}]){const name=material[part.materialIndex??0].name;if(!name.startsWith('Drive road | asphalt')&&name!=='Drive road | chalk white paint')continue;for(let i=part.start;i<part.start+part.count;i+=3){const face=[0,1,2].map(k=>{pt.fromBufferAttribute(position,r.index?.[i+k]??i+k).applyMatrix4(r.mesh.matrixWorld);return[pt.x+tile.origin[0],-pt.z-tile.origin[2],pt.y+tile.origin[1]]});if(name.startsWith('Drive road | asphalt'))pavement.push(face);else(target?.remove.includes(i/3)?removed:retainedWhite).push(face);}}
 }
 const mesh=scene.getObjectByName('finished_continuous_center_dashes'),p=mesh.geometry.getAttribute('position'),normal=mesh.geometry.getAttribute('normal');for(let i=0;i<p.count;i+=3){const v=[0,1,2].map(k=>new THREE.Vector3().fromBufferAttribute(p,i+k)),cross=v[1].clone().sub(v[0]).cross(v[2].clone().sub(v[0]));assert.ok(cross.y>1e-9);for(let k=0;k<3;k++)assert.ok(cross.clone().normalize().dot(new THREE.Vector3().fromBufferAttribute(normal,i+k))>.99999);added.push(v.map(a=>[a.x+tile.origin[0],-a.z-tile.origin[2],a.y+tile.origin[1]]));}
 fs.writeFileSync(`${work}/output-${tile.id}-${lod.level}.json.gz`,gzipSync(JSON.stringify({tileId:tile.id,level:lod.level,removed,retainedWhite,added,pavement})));report.push({tileId:tile.id,level:lod.level,ms,sourceMeshes:before.length,...result});
 const geometries=new Set(),materials=new Set();scene.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();});
}
fs.writeFileSync(work+'/native-report.json',JSON.stringify({passed:true,rows:report},null,2));console.log(JSON.stringify(report,null,2));
