/** Rebuild existing one-way center dashes across four source-qualified incidental nodes. */
import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';
import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{gunzipSync,gzipSync}from'node:zlib';import{build}from'esbuild';
import*as THREE from'three';import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';import{MeshoptDecoder}from'three/examples/jsm/libs/meshopt_decoder.module.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),work=process.env.ROAD_DASH_WORK??'/private/tmp/webster-finished-game/road-dashes';fs.mkdirSync(work,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>createHash('sha256').update(p).digest('hex');
const release=read(root+'/data/derived/town/release.json'),base=root+'/public/town-assets/'+release.directory+'/',manifest=read(base+'manifest.json'),network=JSON.parse(gunzipSync(fs.readFileSync(root+'/data/derived/town/engine-network.json.gz'))),edges=new Map(network.edges.map(e=>[e.id,e]));
const pairs=[[733,732],[1314,1330],[2128,2129],[2192,2193]];
const degree=new Map();for(const e of network.edges)for(const node of[e.from,e.to]){const ids=degree.get(node)??new Set();ids.add(e.physical_id);degree.set(node,ids);}
const imports=['road-finish','road-material-finish','terrain-finish','environment-ground','bridge-surface'];fs.writeFileSync(work+'/entry.ts',imports.map(n=>`export * from '${root}/src/lib/town/${n}';`).join('\n'));
await build({entryPoints:[work+'/entry.ts'],outfile:work+'/api.mjs',bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins:[{name:'shared-three',setup(b){b.onResolve({filter:/^three$/},()=>({path:fileURLToPath(import.meta.resolve('three')),external:true}))}}]});const api=await import(pathToFileURL(work+'/api.mjs'));
const length=points=>{const s=[0];for(let i=1;i<points.length;i++)s.push(s.at(-1)+Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]));return s;};
const norm=points=>points.map((p,i)=>{const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],n=Math.hypot(b[0]-a[0],b[1]-a[1]);return[-(b[1]-a[1])/n,(b[0]-a[0])/n];});
const mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const oldTriangles=[],newRows=[],chains=[];
for(const pair of pairs){const[a,b]=pair.map(id=>edges.get(id));assert.equal(a.to,b.from);assert.equal(a.name,b.name);assert.equal(degree.get(a.to).size,2);for(const e of[a,b]){assert.ok(e.width_m>=5.5&&e.road_type<=5);assert.equal(network.edges.filter(r=>r.physical_id===e.physical_id).length,1);}
 const lengths=pair.map(id=>length(edges.get(id).points)),total=lengths[0].at(-1)+lengths[1].at(-1),chain={id:pair.join('-'),name:a.name,edges:pair,joinNode:a.to,lengthM:total,joinStationM:lengths[0].at(-1),dashLengthM:4,periodM:12,trueJunctionSetbackM:10};chains.push(chain);
 let offset=0;
 for(let ei=0;ei<2;ei++){const e=edges.get(pair[ei]),points=e.points,normals=norm(points),s=lengths[ei],w=e.width_m/2;
  for(let i=0;i<points.length-1;i++){
   const p=points[i],q=points[i+1],na=normals[i],nb=normals[i+1],a0=offset+s[i],b0=offset+s[i+1];if(b0-a0<1e-9)continue;
   const xy=(p,n,k)=>[p[0]+n[0]*k,p[1]+n[1]*k,p[2]],road=[xy(p,na,-w),xy(q,nb,-w),xy(q,nb,w),xy(p,na,w)],center=[xy(p,na,-.05),xy(q,nb,-.05),xy(q,nb,.05),xy(p,na,.05)];
   if(s[i]>10&&s[i+1]<s.at(-1)-10&&(s[i]%12)<4)for(const ids of[[0,1,2],[0,2,3]])oldTriangles.push({edge:e.id,triangle:ids.map(k=>center[k])});
   for(let start=Math.floor(a0/12)*12;start<b0;start+=12){const lo=Math.max(a0,start,10),hi=Math.min(b0,start+4,total-10);if(hi-lo<1e-6)continue;
    const ta=(lo-a0)/(b0-a0),tb=(hi-a0)/(b0-a0),polygon=[mix(center[0],center[1],ta),mix(center[0],center[1],tb),mix(center[3],center[2],tb),mix(center[3],center[2],ta)].map(p=>p.slice(0,2));
    for(const ids of[[0,1,2],[0,2,3]]){const surface=ids.map(k=>road[k]),paint=api.clipRoadPaintPolygon(polygon,surface);if(paint.length>=3)newRows.push({chain:chain.id,edge:e.id,start:lo,end:hi,surface,paint});}
   }
  }offset+=s.at(-1);
 }
}
const wanted=new Set();for(const pair of pairs)for(const id of pair){const p=edges.get(id).points;for(let i=0;i<p.length-1;i++){const xs=[p[i][0],p[i+1][0]],ys=[p[i][1],p[i+1][1]];for(let x=Math.floor((Math.min(...xs)-.1)/250);x<=Math.floor((Math.max(...xs)+.1)/250);x++)for(let y=Math.floor((Math.min(...ys)-.1)/250);y<=Math.floor((Math.max(...ys)+.1)/250);y++)wanted.add(x+'_'+y);}}
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);loader.register(()=>({name:'TEXTURE_STUB',loadTexture(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1))}}));
const roadIndex=read(root+'/data/derived/town/road-finish-index.json'),asset=r=>r?read(root+'/public'+r.url):undefined,tiles={},report=[];const dir=root+'/public/town-finish/v1/dashes';fs.mkdirSync(dir,{recursive:true});
const same=(a,b)=>a.every(p=>b.some(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<.003&&Math.abs(p[2]-q[2])<.04));
const containsBuffered=(points,triangle)=>{const sign=cross(...triangle)>=0?1:-1;return points.every(p=>triangle.every((a,i)=>{const b=triangle[(i+1)%3];return sign*cross(a,b,p)>=-.002*Math.hypot(b[0]-a[0],b[1]-a[1]);}));};
const area=p=>Math.abs(p.slice(1,-1).reduce((v,q,i)=>v+cross(p[0],q,p[i+2]),0))/2;
for(const tile of manifest.tiles.filter(t=>wanted.has(t.id)))for(const lod of tile.lods){
 const bytes=fs.readFileSync(base+lod.url),scene=(await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),pathToFileURL(path.dirname(base+lod.url)+'/').href)).scene;
 api.applyMeasuredBridgeSurface(scene,tile.id,tile.origin);api.applyTerrainFinish(scene,tile.id,tile.origin,lod.level,asset(api.terrainFinishAsset(tile.id,lod.level)));api.applyEnvironmentGround(scene,tile.id,tile.origin,lod.level,asset(api.environmentGroundAsset(tile.id,lod.level)));api.applyRoadFinish(scene,tile.id,tile.origin,lod.level,asset(roadIndex.tiles[tile.id])?.rows??[]);api.applyRoadMaterialFinish(scene,tile.id,tile.origin,lod.level,lod.sha256,asset(api.roadMaterialAsset(tile.id,lod.level)));
 scene.updateMatrixWorld(true);const meshes=[],surfaces=[],pt=new THREE.Vector3();scene.traverse(m=>{if(!m.isMesh||m.parent?.name!=='roads')return;const g=m.geometry,p=g.getAttribute('position'),materials=Array.isArray(m.material)?m.material:[m.material],n=g.index?.count??p.count,faces=[];for(const r of g.groups.length?g.groups:[{start:0,count:n,materialIndex:0}])for(let i=r.start;i+2<Math.min(n,r.start+r.count);i+=3){const triangle=[0,1,2].map(k=>{pt.fromBufferAttribute(p,g.index?.getX(i+k)??i+k).applyMatrix4(m.matrixWorld);return[pt.x+tile.origin[0],-pt.z-tile.origin[2],pt.y+tile.origin[1]]}),material=materials[r.materialIndex??0].name;faces.push({i:i/3,triangle,material});if(material.startsWith('Drive road | asphalt'))surfaces.push({triangle,mesh:m});}meshes.push({mesh:m,faces,stamp:api.terrainGeometryStamp(g)});});
 const pavement=new api.PavementIndex(surfaces.map(r=>r.triangle)),positions=[],removed=[],guards=new Map(),used=new Set();let paintMaterial;
 for(const row of meshes){const ids=[];for(const f of row.faces){if(f.material!=='Drive road | chalk white paint')continue;paintMaterial=f.material;const xy=f.triangle.map(p=>p.slice(0,2)),a=area(xy);if(a<1e-8)continue;
  // Old center dashes alone; white travel-edge and crosswalk triangles survive.
  const selected=oldTriangles.some(r=>{if(Math.min(...r.triangle.map(p=>p[0]))>Math.max(...xy.map(p=>p[0]))+.003||Math.max(...r.triangle.map(p=>p[0]))<Math.min(...xy.map(p=>p[0]))-.003)return false;return containsBuffered(xy,r.triangle)&&f.triangle.every(p=>Math.abs(p[2]-api.roadPaintHeightAt(r.triangle,p)-.018)<.6);});if(selected)ids.push(f.i);
 }if(ids.length){removed.push({name:row.mesh.name,parent:'roads',geometryStamp:row.stamp,remove:ids});guards.set(row.mesh.name,row);}}
 for(const row of newRows){const matches=surfaces.filter(s=>same(s.triangle,row.surface));if(!matches.length)continue;used.add(row.edge);for(const match of matches){const m=meshes.find(r=>r.mesh===match.mesh);guards.set(m.mesh.name,m);const polygon=api.clipRoadPaintPolygon(row.paint,match.triangle);if(area(polygon)<1e-8)continue;for(const piece of pavement.conform(polygon,match.triangle).pieces){for(let k=1;k<piece.polygon.length-1;k++){const p=[piece.polygon[0],piece.polygon[k],piece.polygon[k+1]];if(Math.abs(cross(...p))<1e-9)continue;positions.push(...p.map(q=>[q[0],q[1],api.roadPaintHeightAt(piece.plane,q)+.018]));}}}}
 if(positions.length){assert.ok(paintMaterial,'Missing original white material');const packet={version:1,tileId:tile.id,level:lod.level,sourceSha256:lod.sha256,sourceManifestSha256:release.manifestSha256,guards:[...guards.values()].map(r=>({name:r.mesh.name,parent:'roads',geometryStamp:r.stamp})),targets:removed,positions,material:paintMaterial,edgeIds:[...used],evidence:'Existing one-way center-dash source condition retained; global 4m paint / 8m gap across four incidental same-road degree-two nodes. True junction 10m setbacks and all travel-edge lines unchanged.'};const content=Buffer.from(JSON.stringify(packet)+'\n'),hash=sha(content),name=tile.id+'-'+lod.level+'.'+hash.slice(0,16)+'.json';fs.writeFileSync(dir+'/'+name,content);(tiles[tile.id]??={levels:{}}).levels[lod.level]={url:'/town-finish/v1/dashes/'+name,bytes:content.length,sha256:hash};report.push({tileId:tile.id,level:lod.level,removed:removed.reduce((n,r)=>n+r.remove.length,0),added:positions.length/3,bytes:content.length,gzipBytes:gzipSync(content).length,edges:[...used]});}
 const geometries=new Set(),materials=new Set();scene.traverse(o=>{if(o.isMesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();});
}
const catalog={version:1,sourceManifestSha256:release.manifestSha256,chains,tiles};fs.writeFileSync(root+'/data/derived/town/road-dash-index.json',JSON.stringify(catalog)+'\n');const keep=new Set(Object.values(tiles).flatMap(t=>Object.values(t.levels).map(a=>path.basename(a.url))));for(const p of fs.readdirSync(dir))if(p.endsWith('.json')&&!keep.has(p))fs.unlinkSync(dir+'/'+p);fs.writeFileSync(work+'/preparation-report.json',JSON.stringify({chains,rows:report},null,2));fs.writeFileSync(work+'/plan.json',JSON.stringify({chains,oldTriangles,newRows}));console.log(JSON.stringify(report,null,2));
